Jay Force new password for new users
OneCommunityGlobal/HGNRest pull request #1020
Opened 2024-07-04 20:50 UTC by jayyy-s

# Description
High priority issue to force a new password for new users. Previously, users could choose the same default password as their new one
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/71467346/48d890ff-e9ca-44fa-84fc-452a321b18f0)

## Related PRS (if any):
Please test with related frontend PR [to be added]

## Main changes explained:
- Update `src/controllers/forcePwdController.js` to check if the incoming password matches the existing password in MongoDB and send a 400 status if it does

## How to test:
1. check into current branch
2. do `npm install` and `npm run dev` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links→ User Management→Create New User
6. create a new user (any role)
7. log out 
8. log into new user account with default password
9. when prompted to make a new password, attempt to use the default password `123Welcome!`

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HGNRest/assets/71467346/913dcffd-951f-4fb5-9004-8f340c46d057

2024-07-05 20:20 UTC, nikhilpittala16 approved these changes
Changes work as expected. I have left a review with screenshots in Frontend PR. link can be found here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2417#pullrequestreview-2161216244

2024-07-05 23:59 UTC, sahithidhulipala9 approved these changes
Left comment at Frontend PR 2417.

2024-07-06 23:34 UTC, jinxyou approved these changes
I left a review at the frontend: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2417#pullrequestreview-2161679435

2024-07-14 09:44 UTC, aaryaneil approved these changes
Tested the PR and the changes work as expected. Left a review on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2417#pullrequestreview-2176616286)

2024-07-31 13:31 UTC, Annezhang673 approved these changes
Left a review on the frontend PR #2417. Works as expected.

2024-09-05 17:34 UTC, AJAYINAVOLU reviewed
Reviewed the changes on the frontend [repo](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2417#pullrequestreview-2283695061).

2024-09-07 02:10 UTC, sri0606 requested changes
[Please address the issue raised in frontend PR.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2417#pullrequestreview-2287315033)

2025-02-13 03:47 UTC, sri0606 approved these changes

2025-02-28 19:26 UTC, saishekhar10 approved these changes
The changes work as expected, I have left my review and comments on the frontend PR #2417
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2417#pullrequestreview-2651611619

2025-05-02 04:42 UTC, one-community commented
Thank you all, merging!

2025-05-02 04:43 UTC, merged