Sushmitha project controller unit and integration test
OneCommunityGlobal/HGNRest pull request #1021
Opened 2024-07-06 04:46 UTC by SushmithaPrathap

# Description
PR adds integration tests and updates the unit tests for projectController.js

## Main changes explained:
- Added integration test file named: projectController.test.js
- Update unit test file named projectController.spec.js
…

## How to test:
1. check into the current branch
2. do npm install
3. To run the unit tests: do npm run test projectController
4. To run the integration tests: do npm run test projectRouter
5. All test cases should pass

2024-07-06 18:53 UTC, KaushikMreddy approved these changes
Hi, all the test cases work!
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/144624017/1f837800-ce7b-4d1a-86e4-38418a7e4586)

2024-07-06 23:22 UTC, jinxyou approved these changes
All test cases have passed. Great work! 
![Screenshot 2024-07-06 172145](https://github.com/OneCommunityGlobal/HGNRest/assets/13797542/e1016f21-f387-4eb5-a8ce-71ca89f950a6)
![Screenshot 2024-07-06 172215](https://github.com/OneCommunityGlobal/HGNRest/assets/13797542/1e0af3ca-761f-4e02-a38b-54a458edc516)

2024-07-09 02:15 UTC, sahithidhulipala9 approved these changes
All test cases passed!
![PR 1021](https://github.com/OneCommunityGlobal/HGNRest/assets/60340387/c3764210-0933-4011-9e36-c154f6a1561e)

2024-07-09 21:41 UTC, nikhilpittala16 approved these changes
I have tested the PR  and all test cases have passed. Great work!
![Screenshot (44)](https://github.com/OneCommunityGlobal/HGNRest/assets/142841075/0a33f177-0e7f-4ad8-bbc9-f26fc838438b)

2024-07-10 23:24 UTC, nyelmela approved these changes
I have tested this PR, and all test cases have passed.
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/123037122/b30481c1-c6f7-45ca-b682-51b7bb5e788e)

2024-07-11 04:04 UTC, vijay10pk approved these changes
All test cases passed.
<img width="1015" alt="Screenshot 2024-07-10 at 11 56 21 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/40633436/962156a1-aa39-4bc9-8b53-b6fabddac8fe">
<img width="1015" alt="Screenshot 2024-07-10 at 11 57 01 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/40633436/4e643d47-b265-4e81-a963-ac3df4470a27">

2024-07-11 14:25 UTC, gowthamdongari approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/27274513/927e66bd-1c61-4d27-85eb-dc97684d9cdc)
Good work ! All test cases Passed

2024-07-13 01:51 UTC, Rishitha1309 approved these changes
All test cases passed.!

![1021](https://github.com/user-attachments/assets/f3b0952c-87d1-403e-b335-dc1690ab5267)

2024-07-18 15:14 UTC, linkhanthtel approved these changes
All test cases passed!

<img width="966" alt="#1021" src="https://github.com/user-attachments/assets/79d39ed1-edc1-4a59-9969-2c4d994453e7">

2024-07-21 12:25 UTC, aaryaneil approved these changes
Tested the PR and both the unit test and integration tests passed.
![Screenshot 2024-07-21 at 7 25 17 AM](https://github.com/user-attachments/assets/62fe45f3-17e9-4621-a833-720b275963c6)

2024-07-27 03:14 UTC, Annezhang673 approved these changes
All tests cases passed. Worked as expected. Good work.
<img width="1063" alt="PR1021" src="https://github.com/user-attachments/assets/73596c7c-60a3-4822-b9a9-5c7c69e91b99">

2024-08-06 00:33 UTC, SatyashanthiT approved these changes
I reviewed the changes by checking out the current branch, installing dependencies, and running the unit tests and integration tests locally. All test cases passed successfully. The added integration tests and updated unit tests for projectController.js work correctly and ensure comprehensive test coverage.

<img width="951" alt="image" src="https://github.com/user-attachments/assets/4664055c-b654-45e7-900d-bd33334d2bc4">

2024-08-15 18:54 UTC, preethamdnr requested changes
Hello Sushmitha,

I have followed the steps you mentioned, and everything is working as expected.
![image](https://github.com/user-attachments/assets/f01fc908-f433-48f8-8782-564f097cc062)
![image](https://github.com/user-attachments/assets/2dca919c-7c66-4630-930b-a9f3ba4d71aa)

2024-08-15 18:56 UTC, preethamdnr approved these changes

2024-08-16 23:04 UTC, Gmon-k commented
Both the unit tests and integration tests has passed. Below is the screenshot for it.

<img width="1024" alt="5" src="https://github.com/user-attachments/assets/ed7f1569-ef1d-438f-a8f9-ca70be1123de">

2024-08-31 01:28 UTC, AJAYINAVOLU approved these changes
Test Cases are passing without any errors.

![image](https://github.com/user-attachments/assets/0ddfeaac-201c-4c73-bbb4-38eab4692bda)

Thank You

2024-09-06 21:42 UTC, Saniya98 approved these changes
All test cases have passed 
![image](https://github.com/user-attachments/assets/5564d1d1-14cc-4488-ac4d-c95da7ddd8f3)

2024-09-14 23:31 UTC, panchalvatneu approved these changes
unit tests passed
![image](https://github.com/user-attachments/assets/4cae593b-d02b-4069-8a2f-19e93bf16705)

integration tests passed
![image](https://github.com/user-attachments/assets/ed7637d0-11cd-48d3-9d3a-f609ef1f0ff0)

good work!

2024-09-16 19:50 UTC, ishangoel17 reviewed
All unit and integration test cases are passing. Below are the screenshots for reference:
![Capture1021_1](https://github.com/user-attachments/assets/d3c441b1-b5db-4733-8d00-0b2a064e7c1a)
![Capture1021_2](https://github.com/user-attachments/assets/697f34d9-bfc9-4f8c-b8ea-cf0ae6601225)

2024-09-20 03:16 UTC, geetamatkar commented
Hi @SushmithaPrathap ,
Tested this PR and all unit and integration tests have passed.

<img width="995" alt="PR1021" src="https://github.com/user-attachments/assets/a55b5e4e-b4df-453f-a9e4-842840f5eb55">

2024-09-24 18:52 UTC, anirudhsk2107 approved these changes
The tests have passed successfully 
![Screen Shot 2024-09-24 at 2 52 07 PM](https://github.com/user-attachments/assets/4965f483-ec24-47b5-a808-1a46023ceeb4)

2024-10-11 04:48 UTC, neeharikakoniki approved these changes
The integration and unit tests added for `projectController.js` effectively verify functionality and enhance test coverage. I confirmed that all test cases pass as expected when running both unit and integration tests.
![image](https://github.com/user-attachments/assets/b7536716-47ec-4644-9842-b260b7ab66ae)

2024-10-13 05:28 UTC, mianmiantea2019 commented
The tests have passed successfully

![image](https://github.com/user-attachments/assets/56807fa5-3b33-482a-a71f-b960ff2e90df)

2024-10-27 04:08 UTC, RachanaZha approved these changes
Have tested both the files and test cases for both have passed successfully.
![zha_rachana_PR#1021](https://github.com/user-attachments/assets/603a052d-154b-4446-994a-293b846394f7)

2025-02-15 03:01 UTC, Srichand-Medagani approved these changes
I have run the commands and all the test cases have been passed successfully without any errors. 
<img width="740" alt="image" src="https://github.com/user-attachments/assets/b874fc11-a571-4317-991e-57ebfbaea0ce" />

2025-05-02 04:42 UTC, one-community commented
Thank you all, merging!

2025-05-02 04:42 UTC, merged