Changes to return specific error
OneCommunityGlobal/HGNRest pull request #1024
Opened 2024-07-09 05:36 UTC by DiyaWadhwani

# Description
Updating the Last Name on the User Profile to an initial throws a 400 error with a localhost webpage error saying "An error occurred while attempting to save this profile"

## Related PRS (if any):
To test this backend PR you need to checkout the #XXX frontend PR.

## Main changes explained:
- Displaying the error returned from backend

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. View Profile > Change the last name to an initial
6. Verify the localhost:3000 shows the error 'Path 'lastname' ('[_your entered initial_]') is shorter than the minimum allowed length (2).

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/54880903/ff0f7f18-e420-4b00-99b6-11ccb6ae6f3e

2024-07-10 02:55 UTC, vijay10pk approved these changes
Changes work as expected. Left a comment on [PR2440](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2440#pullrequestreview-2167935568)

2024-07-10 22:47 UTC, nikhilpittala16 approved these changes
I have  tested the PR and everything works as expected. left a review on the [front-end](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2440#pullrequestreview-2170509623)

2024-07-11 18:50 UTC, nikethaanand commented
All changes worked as expected. On Editing the username and setting the last name to a size less than two, an error pops up as mentioned above with a warming.


https://github.com/OneCommunityGlobal/HGNRest/assets/47215795/f88df7cb-ace6-4431-a21c-2d86e581c7a0

2024-07-13 04:15 UTC, sahithidhulipala9 approved these changes
Tested this PR and Left comment at Front End PR 2440.

2024-07-13 07:52 UTC, aaryaneil requested changes
Left a review on the [frontend.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2440#pullrequestreview-2176188052)

2024-07-21 12:52 UTC, aaryaneil approved these changes
Tested the PR and left a review on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2440#pullrequestreview-2190323961)

2024-08-02 07:07 UTC, jayyy-s commented
Left PR review on frontend [ticket](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2440#issuecomment-2264715389)

2024-08-15 06:55 UTC, Parth-tech commented on src/controllers/userProfileController.js
> +            console.error('Failed to save record:', error);
Hey @DiyaWadhwani,
I think this console statement wouldn't be needed right? If I have got it wrong sorry for the trouble.

2024-08-15 06:56 UTC, Parth-tech approved these changes
Hey Diya,
Great job done. The PR meets the functionality and the codebase looks good too. Yet I have left a comment. [Frontend Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2440#pullrequestreview-2239831301)

2024-08-16 19:00 UTC, SnelPatare approved these changes
Changes work well. Please find my review on frontend repo .
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2440#pullrequestreview-2243374930

2024-08-16 20:14 UTC, SMitta11 requested changes
I gave my review for changes in frontend PR 2440

2024-08-17 21:44 UTC, adityasure9 approved these changes
I've provided detailed feedback on the frontend PR related.

2024-08-31 19:06 UTC, merged