Parthj unit test time zone api controller.js
OneCommunityGlobal/HGNRest pull request #1027
Opened 2024-07-13 05:08 UTC by Parth-tech

# Description
This pull request consists of unit tests for `timeZoneAPIController.js`

## Related PRS (if any):
None

## Main changes explained:
- Created 2 `.md` files highlighting the test cases to be covered (names of the .md files: `getTimeZoneProfileInitialSetup.md` and `getTimeZone.md`)
- Created a `..../controllers/timeZoneAPIController.spec.js` file containing all the unit tests.

## How to test:
1. check into current branch (i.e. `git checkout parthj_unit_test_timeZoneAPIController.js`)
2. do `npm install` 
3. do `npm run test timeZoneAPIController`

## Screenshots or videos of changes:
After successful execution it might look as follows:
<img width="1042" alt="Screenshot 2024-07-12 at 10 08 27 PM" src="https://github.com/user-attachments/assets/8319343c-65cd-407b-8611-70d9fe699749">

2024-07-13 06:35 UTC, ZhangPeizhou commented
Worked as expected, and passed all the tests. Well done!
![PR#1027](https://github.com/user-attachments/assets/0f6c8c0f-8ecb-4cf9-b782-abcadee07b61)

2024-07-13 07:55 UTC, aaryaneil approved these changes
Tested the PR and all the test cases passed.
<img width="1136" alt="Screenshot 2024-07-13 at 2 54 36 AM" src="https://github.com/user-attachments/assets/3b783ccb-4886-456a-a2f0-163bc81b7c78">

2024-07-13 17:39 UTC, sahithidhulipala9 approved these changes
All test cases passed!
![PR 1027](https://github.com/user-attachments/assets/982874e5-55c3-4fe5-8e10-d1197d4ead0a)

2024-07-13 17:42 UTC, nyelmela approved these changes
I have tested this PR and all test cases have passed.
![image](https://github.com/user-attachments/assets/e94a7f64-0e50-413c-93a4-4adf91dc8def)

2024-07-13 19:10 UTC, Rishitha1309 approved these changes
All test cases passed.

![1027](https://github.com/user-attachments/assets/498c8ab2-de90-40af-b940-6be9c035e17d)

2024-07-13 22:06 UTC, jinxyou approved these changes
All test cases have passed. Great work!
![Screenshot 2024-07-13 160541](https://github.com/user-attachments/assets/a94c0695-2854-4ef9-a36d-4da2273c6a2d)

2024-07-15 20:17 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (91)](https://github.com/user-attachments/assets/73c523af-138b-4957-be22-538a6123d8fe)

2024-07-17 15:47 UTC, linkhanthtel approved these changes
All test cases passed!

<img width="1127" alt="PR #1027" src="https://github.com/user-attachments/assets/2a42af32-0d5b-4e76-9e59-95577608b6d1">

2024-07-18 18:06 UTC, Shadhrush5 approved these changes
Hi, I tested PR #1027 as instructed and all the test cases are passing. Thank you for the great work.

<img width="682" alt="Screenshot 2024-07-18 at 11 05 50 AM" src="https://github.com/user-attachments/assets/c819a9f5-de24-460d-b7d7-f8d05c15450d">

2024-07-18 20:27 UTC, nikethaanand commented
All the test cases are passed and working as expected.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/59080b09-8c77-4c3b-bfda-c53dd43752bb">

2024-07-19 00:45 UTC, ishan-miglani approved these changes
I have tested the changes and all the test cases pass. Nice work!
<img width="1080" alt="Screenshot 2024-07-18 at 8 43 32 PM" src="https://github.com/user-attachments/assets/0f43a2be-a4e9-4a54-9a5b-0d12a2e58b3c">

2024-07-19 00:56 UTC, kabraambika commented on requirements/timeZoneAPIController/getTImeZone.md
Please fix the file name to `getTimeZone.md`. it is currently named `getTImeZone.md`.

2024-07-19 00:59 UTC, kabraambika commented on package-lock.json
If there are no changes in package.json, there's no need to submit package-lock.json.

2024-07-19 01:01 UTC, kabraambika commented
I have tested the changes and all test cases are passing.
<img width="829" alt="PR1027" src="https://github.com/user-attachments/assets/238e4c3d-7a82-4c11-96cc-f426786b5ea3">

2024-07-19 01:02 UTC, kabraambika requested changes
There are two comments provided to fix.

2024-07-19 21:04 UTC, SaiLavanya1 approved these changes
I have tested this PR, it is worked as expected.
<img width="976" alt="Screenshot 2024-07-19 at 2 01 15 PM" src="https://github.com/user-attachments/assets/daff720f-5eb9-498a-91c2-f18e1093cbb3">

2024-07-21 01:43 UTC, jinxyou approved these changes
All test cases have passed. Great work!
![image](https://github.com/user-attachments/assets/88e7c047-74a4-468e-922c-5279b521119b)

2024-07-21 07:13 UTC, cecilia-uu commented
<img width="750" alt="截屏2024-07-21 下午3 12 36" src="https://github.com/user-attachments/assets/9a8817d3-1651-4e2c-88c6-6cd5cf5ab09a">
Tests have passed but the merging process may have some issue.

2024-07-21 23:28 UTC, gowthamdongari approved these changes
test cases works as expected
![image](https://github.com/user-attachments/assets/dab8d8fc-20b3-4758-9c89-741e4c329ea4)

2024-07-22 04:30 UTC, angelalalacheng approved these changes
Hi, 
I use your branch `parthj_unit_test_timeZoneAPIController.js` to test and all pass.

<img width="1134" alt="Screenshot 2024-07-21 at 4 34 03 PM" src="https://github.com/user-attachments/assets/a2d9d40a-e715-42d9-a7c3-68938468d099">

2024-07-24 18:56 UTC, Chetan0606 approved these changes
Everything looks good
![image](https://github.com/user-attachments/assets/278852d0-3ec2-4298-8a17-034006450dd5)

2024-07-25 01:30 UTC, SrikanthChowdary495 approved these changes
I have tested this PR, and passed all the tests. I have reviewed the code. 
![test](https://github.com/user-attachments/assets/bdbc8219-3f25-4784-8086-224ce49aae90)

2024-07-25 04:05 UTC, ReinaT5678 approved these changes
I ran the test and they all passed!

<img width="1085" alt="Screenshot 2024-07-24 at 9 05 39 PM" src="https://github.com/user-attachments/assets/22928713-0f00-499f-a7ed-34b627ad7497">

2024-07-26 03:49 UTC, Annezhang673 approved these changes
All tests cases passed. Works as expected.
<img width="775" alt="PR1027" src="https://github.com/user-attachments/assets/7528d2fa-a243-4e9c-8463-d5803fde27d5">

2024-09-21 00:06 UTC, merged