Abi weekly summary reports page
OneCommunityGlobal/HGNRest pull request #1062
Opened 2024-08-12 23:55 UTC by Abi-Liu

# Description
This PR implements a new aggregation pipeline for volunteer trends data as well as fixes previous queries for the volunteer hours stats and work distribution stats

## Related PRS (if any):
This PR is built off of #994 

## Main changes explained:
- Created a new query to aggregate the monthly volunteer trends data for the past year.
- Fixed bugs for the volunteer hours stats and work distribution stats to now return correct data
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run dev`
3. Query the endpoint with Postman: `http://localhost:4500/api/reports/volunteerstats?startDate=2024-05-26&endDate=2024-06-02`
4. verify the data is correct

## Screenshots or videos of changes:
![Screenshot 2024-08-12 at 4 55 30 PM](https://github.com/user-attachments/assets/883d6abd-0da5-4135-8a5d-4329769d1f22)
![Screenshot 2024-08-12 at 4 55 48 PM](https://github.com/user-attachments/assets/9fdbd73c-16f0-417c-a808-7e77ed1e58d3)

2024-08-16 21:08 UTC, SMitta11 approved these changes
I tested as per given instructions, initially sent a POST request to get a token and then GET request to get this data of volunteer stats for given start and end date and data matches exactly as given here.
Below screenshots:
![PR 1062 FirstScreenshot](https://github.com/user-attachments/assets/5a7b6f31-456b-45f4-ac7f-0a6b9914692a)
![PR 1062 SecondScreenshot](https://github.com/user-attachments/assets/447a2dc9-580a-4cd9-9901-81d20d0234fb)
![PR 1062 ThirdScreenshot](https://github.com/user-attachments/assets/d6d913ab-9590-495b-bac3-328bc758ace9)

2024-08-21 22:34 UTC, nikhilpittala16 approved these changes
I have tested the PR and everything works as expected.
![Screenshot (179)](https://github.com/user-attachments/assets/fe4c7fbd-a876-4ad2-bffb-1d58bf54a4d6)

2024-08-25 02:07 UTC, oliviahyw approved these changes
I have tested this PR and it's working as expected.
![pr1062](https://github.com/user-attachments/assets/249ad460-def6-400a-9018-4133effcb4b4)

2024-08-30 00:09 UTC, Parth-tech approved these changes
Hi Abi,
The the response matches with the provided reference. The API endpoint is working well.

`Reference Images:`
<img width="1301" alt="Screenshot 2024-08-29 at 5 03 53 PM" src="https://github.com/user-attachments/assets/14844f4a-81d1-44f4-8c05-4187a7e09fbf">

2024-08-31 15:36 UTC, yashwanth170 approved these changes
I have tested this PR and it's working as expected. 
![Screenshot 2024-08-31 113408](https://github.com/user-attachments/assets/4cd39392-eb71-4088-84a5-3f0bde7860fe)
![token](https://github.com/user-attachments/assets/1cc3087a-caed-4de1-88a1-3196fbdd4fe9)

2024-09-04 01:16 UTC, vedantg24 approved these changes
Tested the PR as per the instructions. Changes working as expected.

![Screenshot 2024-09-03 at 5 58 01 PM](https://github.com/user-attachments/assets/ba351bd3-6873-4358-85e4-c782ca7d31a8)
![Screenshot 2024-09-03 at 5 57 38 PM](https://github.com/user-attachments/assets/1ad44e73-6404-4f46-b372-76fd97aacfe0)

2024-09-05 19:44 UTC, vishnupriyaatheti requested changes
@Abi-Liu I have reviewed your changes. As per dates given in the description the PR is working as expected. But when I change the dates I am the below error. Can you please check and reply

I am passing below dates:
http://localhost:4500/api/reports/volunteerstats?startDate=2024-09-01&endDate=2024-09-07&comparisonStartDate=2024-09-25&comparisonEndDate=2024-09-31
![BE PR 1075 dates given diferntly](https://github.com/user-attachments/assets/d4ba1b1f-9c23-4685-98ae-a77904e93d09)

2024-09-06 06:50 UTC, Shreyav2000 approved these changes
Tested the PR by sending the necessary GET request and verifying the returned data. The volunteer stats, trends, and comparison percentages are working as expected. The aggregation and calculation logic for the volunteerNumberStats and volunteerTrends looks accurate. Everything is functioning as intended. Ready for approval! Nice work! I have attached the screenshots below:
<img width="1726" alt="Screenshot 2024-09-06 at 1 39 47 AM" src="https://github.com/user-attachments/assets/a5017428-8101-46d3-9309-b3096b714378">
<img width="1727" alt="Screenshot 2024-09-06 at 1 47 55 AM" src="https://github.com/user-attachments/assets/10f3ec67-56d9-4f0c-b387-f9314143c283">

2024-09-07 01:30 UTC, sri0606 approved these changes
Hello @Abi-Liu , I have tested the PR as mentioned, and it worked as expected.

![Screenshot 2024-09-06 153718](https://github.com/user-attachments/assets/881e3aeb-caf4-466f-a730-7592ead1428f)
![Screenshot 2024-09-06 153734](https://github.com/user-attachments/assets/878dd89e-fca2-4204-a3c3-7a50c3f64cc0)

2024-09-20 00:46 UTC, chu-ziyu approved these changes
Hi Abi,
I have tested this PR and everything worked as expected!
![Screenshot 2024-09-19 at 5 44 59 PM](https://github.com/user-attachments/assets/697e8645-839d-4905-9fe1-d6ba7ac0601e)

2024-09-20 01:05 UTC, Lexie5212 approved these changes
I have tested the PR. And everything is good.
![Screenshot 2024-09-19 at 18 03 29](https://github.com/user-attachments/assets/f8f4f9dd-647c-4390-8eb2-8e3cbd7923d5)

2024-09-20 20:39 UTC, ashayk9 approved these changes
Changes are working as expected
<img width="1456" alt="Screenshot 2024-09-20 at 1 30 37 PM" src="https://github.com/user-attachments/assets/fede8022-595c-4ef1-bb43-c5af59e3bdb4">
<img width="1434" alt="Screenshot 2024-09-20 at 1 38 26 PM" src="https://github.com/user-attachments/assets/7475d826-8476-459c-adb9-dd3a1ea55057">

2024-09-26 23:23 UTC, nevatiarishabh approved these changes
I have tested the PR. Everything is working as expected. 

<img width="949" alt="Screenshot 2024-09-26 at 4 21 57 PM" src="https://github.com/user-attachments/assets/d808fef7-b8af-465f-a595-28767362ea22">
<img width="949" alt="Screenshot 2024-09-26 at 4 21 16 PM" src="https://github.com/user-attachments/assets/56fc6737-71f3-459f-b121-7cd1887c3a8b">

2024-09-30 22:25 UTC, mrinalini-raghavendran19 approved these changes
This PR does a great job enhancing the reporting capabilities for volunteer statistics, allowing users to analyze trends and compare data effectively over defined time periods.

The new API now retrieves comparison data for various volunteer statistics, including `Total Badges Awarded`, `Total Active Teams` and `Total Hours Worked` in a given time range, with the addition of a start and end date incorporated.

It also provides counts of active, new, and deactivated volunteers, along with their respective comparison percentages relative to a previous week.

I have verified the changes via Postman with owner account credentials. Find below screenshots for the testing:

<img width="859" alt="Screenshot 2024-09-30 at 3 02 44 PM" src="https://github.com/user-attachments/assets/ba7db93c-fa1a-40b4-8753-bf1044f11e0d">

<img width="1077" alt="Screenshot 2024-09-30 at 3 06 25 PM" src="https://github.com/user-attachments/assets/aa821958-3363-4cf5-8744-7de586b7d9d5">

2024-10-04 19:48 UTC, pallavithorat commented
I have reviewed the PR, and everything is working as expected.
<img width="1058" alt="PR #1062" src="https://github.com/user-attachments/assets/451167ca-df90-4e5c-8d12-fb5c5ba8d9b7">
<img width="1026" alt="PR_ #1062" src="https://github.com/user-attachments/assets/40330f17-f678-4954-9e15-fab07ed59dd3">

2024-10-08 08:20 UTC, neeharikakoniki approved these changes
This PR successfully adds a new aggregation pipeline for tracking volunteer trends and fixes existing issues with volunteer hours and work distribution stats. I tested the updated API endpoint in Postman, confirming that the comparison data and formatting were accurate and aligned with the specified requirements.

![image](https://github.com/user-attachments/assets/ea8b2a37-592f-4b33-baa2-94c41781fe98)
![image](https://github.com/user-attachments/assets/dd205fea-35da-4951-9363-8e87578cf69f)

2024-11-03 05:35 UTC, sheetalmangate commented
I could not test this API. it is giving me "400 Bad Request".  Could you please help me how to test this.

![PR1062_testing-error](https://github.com/user-attachments/assets/5a395049-e024-462c-92f0-a8c996869f3a)

2025-01-12 02:36 UTC, merged