Angela mail chimp replacement
OneCommunityGlobal/HGNRest pull request #1080
Opened 2024-08-21 04:24 UTC by angelalalacheng

# Description
- We currently use MailChimp to send out our weekly progress updates. It is not user friendly and the price keeps going up. I’d like a replacement that an Admin can use via the app.
- Take over the work of previous people : [FE](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1315 ) [BE](https://github.com/OneCommunityGlobal/HGNRest/pull/540 ) led to https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1784
- [Video of what’s needed](https://www.loom.com/share/ce0ff3e66f3e40e19703ad9f4206cad1?sid=775e17db-d792-4a1c-a6d6-26379ccfe48c)

## Related PRS (if any):
To test this backend PR you need to checkout [#2595 frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2595).

## Main changes explained:
- Update `src/controllers/emailController.js` for refactoring and use content id to ensure that the image can display correctly in Gmail
- Update `src/utilities/emailSender.js` for refactoring the code

## Before Testing
To send an email using the Gmail API with OAuth2 and nodemailer, follow the video below and set it up.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

Fill in the these variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = true

## How to test:
1. check into current branch
2. do `npm install` and `npm run dev` to run this PR locally
3. Clear site data/cache
4. If you only want to send the testing email to your own testing accounts, you can add a search keyword in src/controllers/emailController.js like the following:
<img width="928" alt="Screenshot 2024-08-20 at 9 23 17 PM" src="https://github.com/user-attachments/assets/e551c916-ff99-40db-937e-27d685bba0ed">

5. See how to test in frontend [#2595 frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2595)

## Screenshots or videos of changes:
See frontend

## Note:
See frontend

2024-09-11 21:49 UTC, vishnupriyaatheti reviewed
@angelalalacheng I am trying to setup  that was described in youtube video. To authorize the Api I am getting below attached error. Can you please suggest what wrong I am doing.
![BE PR 1080](https://github.com/user-attachments/assets/4f85f4fb-9dfa-4559-ac00-ce2a5c635007)

2024-09-22 23:23 UTC, angelalalacheng commented
> @angelalalacheng I am trying to setup that was described in youtube video. To authorize the Api I am getting below attached error. Can you please suggest what wrong I am doing. ![BE PR 1080](https://private-user-images.githubusercontent.com/13943137/366640747-4f85f4fb-9dfa-4559-ac00-ce2a5c635007.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDcyNzMsIm5iZiI6MTcyNzA0Njk3MywicGF0aCI6Ii8xMzk0MzEzNy8zNjY2NDA3NDctNGY4NWY0ZmItOWRmYS00NTU5LWFjMDAtY2UyYTVjNjM1MDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDIzMTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjU4YzE0MDAzZWFmZmFjZTAyNDc1NWRlYjZhYzE5OGFiNTAxMjU2NGY2ODhkNzc1MmU3YjdkZjE1MDllNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7uO8qz-aCSh949TiQP99p3oV9Nn-h_y4u2XyO2VUNxg)

Hi, @vishnupriyaatheti 
Sorry about that I have no idea about that. I google it and also asked GPT andbutnot sure whether it is helpful.

The issue you’re facing is due to the fact that your application hasn’t completed the Google API verification process. When using Google APIs, such as the Gmail API, the app needs to go through a security and verification process by Google to ensure it complies with privacy and security standards.

The error message “Access blocked: Gmail API tutorial has not completed the Google verification process” indicates that the app is still in testing and can only be accessed by developer-approved testers. The app is blocked from wider access because it hasn’t been fully verified.

2024-10-07 18:48 UTC, Ankuriboh requested changes
Code was great, except that we need to reconsider the necessity of the queue system.

Asides from this, it somewhat a hassle to use Gmail as our email provider. I would suggest that we move to a real bulk mail sender other than Mailchimp to solve the issue.

2024-11-01 23:10 UTC, angelalalacheng commented on src/utilities/emailSender.js
> +    const processBatch = async (batch) => {
Thank you for the suggestion! The code extends from previous developer so I just keep use it but I can modify based on your comment!

2024-11-09 23:16 UTC, ajitp4292 reviewed
Awaiting the Google verification to Complete.
<img width="1092" alt="Screenshot 2024-11-09 at 6 15 31 PM" src="https://github.com/user-attachments/assets/3b2beb75-cd37-41b0-b6f6-f8c9fa286c79">

2024-11-10 19:59 UTC, one-community approved these changes

2024-11-10 19:59 UTC, merged