ambika fix core team unique additions in leaderboard
OneCommunityGlobal/HGNRest pull request #1083
Opened 2024-08-22 21:36 UTC by kabraambika

# Description
![image](https://github.com/user-attachments/assets/14fffe22-886a-4e7a-a4d4-26ec42295a77)

Fixes # (bug list priority medium)

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-09-03 19:25 UTC, AJAYINAVOLU requested changes
Reviewed the PR on the frontend repo.

2024-09-04 06:00 UTC, sri0606 commented
Left a [comment on frontend PR.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2600#issuecomment-2327984250)

2024-09-05 17:01 UTC, vishnupriyaatheti approved these changes
Review comments were added on frontend PR 2600

2024-09-06 11:08 UTC, Shreyav2000 approved these changes
I tested the backend logic using Postman, and it worked as expected. I received a 200 response, confirming that the logic for assigning blue squares and calculating additional makeup hours is functioning correctly. The errors I encountered may be due to macOS date manipulation or Babel configuration issues, but they did not affect the backend functionality. As a result, I have approved the backend PR, and the logic is ready for deployment. I'll attach Postman screenshots as evidence.
<img width="1724" alt="post" src="https://github.com/user-attachments/assets/197362fa-fc18-4000-b04c-3ce8af1371ef">
<img width="1728" alt="get" src="https://github.com/user-attachments/assets/a2d1c333-649f-4881-a098-330482d0efa1">

2024-09-30 05:29 UTC, merged