Crystal fix tasks of members are hidden when teams toggle is off
OneCommunityGlobal/HGNRest pull request #1127
Opened 2024-10-08 06:16 UTC by crystallow1168

# Description
<img width="701" alt="image" src="https://github.com/user-attachments/assets/d2b28d61-f18f-4232-9154-61c22a6e67c2">
Bug priority high

## Related PRS (if any):
To test this backend PR you need to checkout the development frontend PR.
…

## Main changes explained:
- Implement condition so that users (besides Owner/Admin/Core Team) cannot view team's tasks when their team toggle visibility is off
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Dashboard → Other Links→ Teams →…
6. Add members to the team to test and verify that user with team visibility toggle off:
  - Owner role -> Can view other members tasks
![User with Owner role visibility toggle off still can view other member’s task](https://github.com/user-attachments/assets/3349c947-ac8c-43fb-bc59-c4c604254c51)

  - Admin role -> Can view other members tasks
![User with Admin role visibility toggle off can still view other member’s task](https://github.com/user-attachments/assets/345c97c2-ffad-4261-9f44-aadd024da1f2)

  - Core Team role -> Can view other members tasks
![User with Core Team role visibility toggle off still can view other member’s task](https://github.com/user-attachments/assets/7b8e6f2b-04ab-4cdf-86e8-869df56f42a9)

  - Manager role -> CANNOT view other members tasks
![User with Manager role visibility toggle off cannot view other member’s task](https://github.com/user-attachments/assets/9ca4311a-374e-4f40-aad4-de5f8aceebac)

  - Volunteer role -> CANNOT view other members tasks
![User with Volunteer role visibility toggle off cannot view other member’s task](https://github.com/user-attachments/assets/c7f9bdd5-3a9a-4bf9-ab07-5f265dede5c5)

  - Volunteer role (user has 2 teams)-> CANNOT view other members tasks 
![User with Volunteer role visibility toggle off cannot view other member’s task, testing with 2 teams](https://github.com/user-attachments/assets/a451d465-604e-471e-b5c5-c62eca4b2440)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-10-08 18:44 UTC, Ankuriboh requested changes
The code doesn't work on my end. It will always show other members' task whenever I've set disable my own visibility.

2024-10-08 18:44 UTC, Ankuriboh commented on src/helpers/taskHelper.js
> +              if (teamMember.userId.equals(userid) && teamMember.visible) hasTeamVisibility = true;
As long as the user that is requesting is the last user and was set as visible in settings, they could see all other users as well as their tasks. You didn't check if the user has necessary permission (i.e. if they're an Owner/Administrator/Manager).

2024-10-08 18:44 UTC, Ankuriboh commented on src/helpers/taskHelper.js
> +            }
Just `teamMembersIds.push(_myTeam.members.filter(m => !m.userId.equals(userid)).map(m => m.userId));`

2024-10-09 23:22 UTC, crystallow1168 commented
> The code doesn't work on my end. It will always show other members' task whenever I've set to disable my own visibility.

Hello, @Ankuriboh did you set the visibility specifically from the Team page? 
Dashboard → Other Links→ Teams → Select the team which has the user you are testing -> turn off the toggle for the user that you are testing. I added a video to show how to set team member's visibility toggle.

https://github.com/user-attachments/assets/f00a616d-f14a-4a63-8569-1b3c57a0a94a

2024-10-14 05:42 UTC, one-community approved these changes

2024-10-14 05:42 UTC, merged

2024-10-14 13:48 UTC, Ankuriboh commented
> > The code doesn't work on my end. It will always show other members' task whenever I've set to disable my own visibility.
> 
> Hello, @Ankuriboh did you set the visibility specifically from the Team page? Dashboard → Other Links→ Teams → Select the team which has the user you are testing -> turn off the toggle for the user that you are testing. I added a video to show how to set team member's visibility toggle.
> 
>  How.to.set.team.member.visibility.s.toggle.mp4

Hi, thanks for the kindly reply. It could probably be some problems on my end. But I tried on [frontend PR #2766 development preview](https://deploy-preview-2766--highestgoodnetwork-dev.netlify.app/dashboard), toggling off the "see all" option as an administrator wouldn't allow me others on the tasks page. Is this working as intended? Because the "see all" tips says that it does "NOT reduce visibility for Owner, Admin or Core Team roles".