huijie - schedule meeting bell notification
OneCommunityGlobal/HGNRest pull request #1154
Opened 2024-11-17 06:53 UTC by metaphor987

# Description
![task](https://github.com/user-attachments/assets/b2324cb4-6c78-455a-bd97-2882cb1555a9)

## Related PRS (if any):
This backend PR is related to the #2878 frontend PR.

## Main changes explained:
1. Implement a new meeting schema in the database.
2. Implement APIs to post a new meeting, to get all meetings within a specific time range

## Known bugs:
The bell does not ring for the first meeting notification displayed but rings for subsequent ones. This happens because browsers block the autoplay of audio or video until the user interacts with the page (e.g., by clicking or tapping). A possible solution could be to display a preview notification for the upcoming meeting, prompting the user to click a button on the page, which would then allow the bell to ring for future notifications.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
4. Clear site data/cache
5. log as admin/owner user
6. go to dashboard→ Other Links→ Schedule Meetings
7. verify that an admin/owner user can fill in the information in the scheduling form. After clicking the "Submit" button, a message should display the details of the meeting the user has just scheduled.
8. Log in as one of the recipients of the scheduled meeting. If the meeting is scheduled within 3 days from the current date, the recipient should see notifications for the meetings they need to attend after logging in. After clicking the "Cancel" button, the current notification should no longer be displayed. Notifications for other meetings, if available, should then be shown.

## Screenshots or videos of changes:
![schedule meeting page](https://github.com/user-attachments/assets/313e8598-512f-457e-8562-22c96b5d070f)
![notification page](https://github.com/user-attachments/assets/58aa6847-fbdc-4be4-8fba-286a6fb3d675)

2024-12-22 02:54 UTC, mashpotato9 commented
everything worked as expected, review left on [#2878](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2878#issuecomment-2558309513)

2025-01-01 02:03 UTC, kobakvantrishvili requested changes
I am having trouble selecting participants to schedule the meeting with. it's not letting me select the participant even if I type in the full name, therefore I am unable to test whether or not the notification is sent out. I'm not sure why this is happening. If I double click it selects the person and then quickly deselects him, when clicking once nothing happens. I tried this out in multiple browsers and in private mode and this front end issue still persists.

<img width="1198" alt="bug1" src="https://github.com/user-attachments/assets/c9cb9b95-9fa5-4244-85e3-231a5f0bef5b" />

2025-01-21 08:04 UTC, jeyanthi-sm commented
The participants selection has few issues. Adding participants is possible only by double-clicking on the name. Single click does not add the participant. The first entry in the list does not get added. From the second entry onwards double clicking on the participant name gets added however the first participant name (if added before) gets replaced by the current selection. 
![PR-1154](https://github.com/user-attachments/assets/1732396a-8196-4447-9bda-6ecea931b8c8)
![pr-1154-save](https://github.com/user-attachments/assets/30ad5881-c4f8-4a08-bbf8-2409c2373a87)

The form gets submitted and shows the confirmation message even without entering any values and clicking the save button
![pr-1154-defaultDetails](https://github.com/user-attachments/assets/6bcf076b-4f7b-4c2b-99c0-f41f878ce8fc)

2025-01-22 23:35 UTC, lycan10 commented
<img width="1512" alt="Screenshot 2025-01-22 at 6 33 14 PM" src="https://github.com/user-attachments/assets/db796c36-56c3-476d-adad-a14890d3f5cf" />

Hi, this feature is either no longer supported or i don not have access to it.

2025-02-07 20:09 UTC, Srichand-Medagani approved these changes
I have reviewed this PR and when the meeting is scheduled with a participant a toggle notification popped with the meeting details. Upon clicking cancel, it disappeared and other meeting notifications popped if any.

<img width="466" alt="image" src="https://github.com/user-attachments/assets/337d9bf9-7d0e-433e-8771-23eb3820c93d" />

<img width="344" alt="image" src="https://github.com/user-attachments/assets/ef4c0bc9-a6d1-4ced-90d0-8c247c3c158f" />

2025-02-08 10:41 UTC, vivshar commented
The backend implementation seems to have some issues, It couldnot find the meetings/new api, and hence no meeting created.
I'm adding the video for reference.

https://github.com/user-attachments/assets/bc9030d9-f836-4fde-b1a1-ac0ccb7f5529

2025-02-08 10:43 UTC, vivshar reviewed
there seems to be issue where meetings/new api call is not found

2025-02-19 19:40 UTC, AurHubertMax approved these changes
Notification works as expected, reviewed with [PR 2878](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2878#pullrequestreview-2627797673).

2025-03-01 22:02 UTC, rohith1667 requested changes
Hi, I am able to schedule a meeting but when I login as a user can not see the notification.,
<img width="1436" alt="Screenshot 2025-03-01 at 4 00 32 PM" src="https://github.com/user-attachments/assets/9651041e-d7d5-40df-bbf0-c62585ae8256" />
![pr#1154](https://github.com/user-attachments/assets/0116be8d-bd1d-42df-a3ad-2081a304b872)

2025-03-01 23:14 UTC, SSP24SCM16G approved these changes
The frontend PR #1154 and backend PR #2878 were tested using a development account. The meeting scheduling feature functions correctly, allowing multiple participants to be added simultaneously. However, an issue was identified where the form submits successfully and displays a scheduled meeting confirmation popup even when no details are entered, indicating missing validation. Additionally, the notes section incorrectly renders messages within <p> tags instead of displaying plain text. These issues need to be addressed to improve validation and formatting. While the core functionality is working, refinements are necessary for better user experience and data accuracy.

<img width="1470" alt="Screenshot 2025-03-01 at 17 02 40" src="https://github.com/user-attachments/assets/1d4f91f0-3472-4e34-a62d-97703333a71c" />
<img width="1470" alt="Screenshot 2025-03-01 at 17 02 57" src="https://github.com/user-attachments/assets/9b71d622-6886-484b-be67-997e11b6a656" />
<img width="1470" alt="Screenshot 2025-03-01 at 17 06 33" src="https://github.com/user-attachments/assets/e417d774-4313-4a04-b0af-15eb6f74f13a" />
<img width="1470" alt="Screenshot 2025-03-01 at 17 07 44" src="https://github.com/user-attachments/assets/eecdc4f2-436d-457c-b4e0-32c584d5d6e1" />

2025-03-06 22:14 UTC, puchakayalasaisaketh reviewed
I tested the PR and found some issues
the form is submitting with no values entered

<img width="468" alt="image" src="https://github.com/user-attachments/assets/2578daf0-cebc-4b35-bd98-65f9af43a0af" />

Once the details are entered, a pop-up confirms that the meeting has been scheduled successfully.

<img width="468" alt="image" src="https://github.com/user-attachments/assets/ca073887-463a-4f1d-b212-35137722f45c" />

<img width="468" alt="image" src="https://github.com/user-attachments/assets/db6ef95b-1ae2-4dce-9cd7-13e11d332944" />

2025-03-09 00:45 UTC, rishwa344 requested changes
I can successfully schedule a meeting from the admin account, but the participants do not receive any notifications on the dashboard or in the bell icon.
<img width="597" alt="Screenshot 2025-03-08 at 4 34 15 PM" src="https://github.com/user-attachments/assets/e41579b2-7157-4074-ad30-0246ac05b549" />
And also i am getting this error while i click on the bell icon on the dashboard.
<img width="1440" alt="Screenshot 2025-03-08 at 4 38 21 PM" src="https://github.com/user-attachments/assets/39b50c91-c0f6-4c76-a4b8-f2d1698ff5d5" />

2025-03-16 05:28 UTC, kkkaiaa requested changes
PR reviewed. I've run into several issues when testing:
I can add a meeting schedule even it's empty.
I can't schedule a meeting for a past date, but I can schedule one for earlier today, even if it's before the current time.
I can't select any participants in the list, and I think it's caused by rendering a list of elements in React without assigning unique keys to them.
<img width="741" alt="截屏2025-03-16 上午1 17 00" src="https://github.com/user-attachments/assets/2af736d3-245f-48b0-8d8f-7d76052400aa" />
<img width="677" alt="截屏2025-03-16 上午1 21 13" src="https://github.com/user-attachments/assets/f2788b05-2e2e-4718-8b57-74174d63df92" />
<img width="790" alt="截屏2025-03-16 上午1 26 23" src="https://github.com/user-attachments/assets/ec2ab865-d8d4-48f7-bf49-c4e40d99bfb4" />

2025-03-29 00:32 UTC, manushajyasta30 requested changes
I have followed all the steps mentioned in the PR. I was able to create a new meeting. but the recipient is unable to see the notofication for the meeting. I have scheduled a meeting for 3/30/2025. Today's date is 3/28/2025. The meeting is in 2 days. According to the changes it should pop a notification but not able to see the notification.
<img width="943" alt="image" src="https://github.com/user-attachments/assets/3eacf8b4-b4d4-4264-b5a7-7b83930c2a1c" />

2025-03-29 03:16 UTC, humemah commented
Tested the meeting scheduling feature but couldn't select a participant, so I couldn't fully verify the scheduling and notifications.
![image](https://github.com/user-attachments/assets/f1085181-cf47-449e-b486-6b108734ec66)

2025-07-01 16:39 UTC, Deekshith010905 commented
Hi, I was able to schedule a meeting, but when I log in as a user, the notification doesn't appear.
![image](https://github.com/user-attachments/assets/23bf5528-1b32-49ea-9760-cf0890579437)
![image](https://github.com/user-attachments/assets/f65a1bd9-eb51-4fec-a542-776d4fd83789)

2026-07-26 04:05 UTC, merged