Added HGN Form Backend Code
OneCommunityGlobal/HGNRest pull request #1164
Opened 2024-12-05 20:14 UTC by slidracoon72

# Description
This PR includes the backend code for the HGN Form application, which allows developers to evaluate their skill sets across various parameters, facilitating collaboration by enabling them to offer or request assistance from others. The backend primarily handles fetching the form questions. In owner mode, the questions can be edited directly from the frontend. This backend implementation includes all the necessary routing and logic to serve and update the questions efficiently.

## Related PR
To test this backend PR you need to checkout the #XXX frontend PR.

## Main changes explained
- models/Question.js: Defines the structure of 'Questions'
- routes/questions.js: Contains the necessary routes for loading and editing questions, facilitating frontend-backend communication.
- seed.js: Populates the MongoDB database with initial question data.
- server.js: Establishes the database connection and starts the backend server.

## How to test
1. check into current branch: `git checkout Rahul-HGN-Form-Backend`
2. change directory using: `cd src/hgn-form/backend`
3. update '.env' file. First, create a sample MongoDB database to test this PR. Then add the URL of your database to MONGO_URI in the '.env' file
4. run `npm install` to install the dependencies
5. run `node seed.js` to populate your MongoDB database
6. run `node server.js` to start your backend server

## Video Explanation - How to test this PR
https://www.loom.com/share/e8a28ca8345a4938b8348a208311adb1?sid=321f16bb-0e22-48b5-9b3e-18d78589bdfb

2024-12-07 23:53 UTC, ppsahu commented
I have this PR and everything works fine, it was able to connect to the MongoDB database and I was able to run the server.js file. I've included the screen recording below for you to refer to.


https://github.com/user-attachments/assets/2d35e0a7-3135-415a-b5af-b93ce5b66142

2024-12-19 03:24 UTC, mashpotato9 commented
I’ve tested with frontend PR#2922 and successfully set up the database. I was also able to retrieve questions, and the modified questions were saved as expected.

2024-12-30 22:50 UTC, kobakvantrishvili requested changes
Everything works as instructed—MongoDB is populated as expected using seed.js, and the Node.js server runs fine. However, I’ve noticed something that might be an issue (though I could be wrong): you've created a project within a project.

The hgn-form\backend directory is a standalone project with its own dependencies, nested inside HGNRest, which is a monolithic application. In my experience, nesting projects like this is not a good practice because it makes maintenance more difficult. For example, deploying hgn-form\backend would have to be done separately and manually.

I would recommend integrating hgn-form\backend into the main project so its logic can be used as one of the backend services. This would make the architecture cleaner and easier to maintain.
<img width="1187" alt="temp2" src="https://github.com/user-attachments/assets/295dbfda-96f2-4ba7-a4e7-e7b7cc896e68" />
<img width="1118" alt="temp" src="https://github.com/user-attachments/assets/bc45b5b9-369e-4603-bbce-334184689bd3" />

2025-01-17 00:32 UTC, honglinchen0524 reviewed
Hi Rahul! Here are some of my suggested improvements.

2025-01-17 00:32 UTC, honglinchen0524 commented on src/hgn-form/backend/routes/questions.js
> +    res.json(questions);
```suggestion
    if (!questions.length) {
      return res.status(404).json({ message: "No questions found" });
    }
    res.json(questions);
```

2025-01-17 00:32 UTC, honglinchen0524 commented on src/hgn-form/backend/routes/questions.js
> +
```suggestion
// Consider adding validation for POST and PUT here
const validateQuestion = (req, res, next) => {
  const { text, page, title } = req.body;
  if (!text?.trim() || !page || !title?.trim()) {
    return res.status(400).json({ error: "Invalid question data" });
  }
  next();
};


// router.post("/", validateQuestion, async (req, res) => {
//.  Existing POST route code here
//});

//router.put("/:id", validateQuestion, async (req, res) => {
//   Existing PUT route here
//});

```

2025-02-13 04:10 UTC, jaissica approved these changes
Tested the backend PR with frontend [PR#2922](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2922) and successfully set up the database. I was able to retrieve questions, and the modified questions were saved as expected. Below are screenshots of the backend implementation along with db data.
![Screenshot 2025-02-12 at 11 05 29 PM](https://github.com/user-attachments/assets/4d1e17ef-e1c5-4a10-8e29-e9f4000b1874)
![Screenshot 2025-02-12 at 11 01 33 PM](https://github.com/user-attachments/assets/56a57a88-f2ff-4282-a2e3-0b67fc13894d)
![Screenshot 2025-02-12 at 11 02 08 PM](https://github.com/user-attachments/assets/79287bd7-eb7d-4980-854c-c4bb737e8c40)

2025-03-01 04:48 UTC, TanviAnantula commented
Everything worked as expected. The database was successfully set up, all questions were retrieved. The connection to the MongoDB database was also established without any issues.

2025-03-02 08:41 UTC, BhagyeshMahale17 reviewed
🤙

2025-03-02 12:26 UTC, AndresJiangCode commented
The system functioned as expected throughout the testing process. The database was set up successfully, and all queries retrieved the expected results.

2025-03-04 23:39 UTC, closed without merging