Alan fix eslint problems
OneCommunityGlobal/HGNRest pull request #239
Opened 2022-12-04 01:14 UTC by LeeSingChanYau

This PR fixes mostly the names of variables to camel case and some other lint problems. This PR was to tested and I did not encounter any problems so far, but I will need someone else to make sure there are no issues.

2022-12-13 22:30 UTC, Aishwaryak01 requested changes
Changes are suggested in the comments. 
Also for src/models/RealTimeTimer.js as the filename is changed, confirm once that it is changed wherever this file is imported.

2022-12-13 22:30 UTC, Aishwaryak01 commented on src/controllers/userProfileController.js
> +const TimeEntry = require('../models/timeEntry');
File name mismatch

2022-12-13 22:30 UTC, Aishwaryak01 commented on src/helpers/dashboardhelper.js
> +const timeEntry = require('../models/timeEntry');
Filename mismatch

2022-12-13 22:30 UTC, Aishwaryak01 commented on src/helpers/timeEntryHelper.js
> +const timeEntry = require('../models/timeEntry');
File name mismatch

2022-12-13 22:30 UTC, Aishwaryak01 commented on src/routes/dashboardRouter.js
> +  Dashboardrouter.route('/dashboard/leaderDoard/:userId')
Typo. D is typed instead of B

2022-12-13 22:30 UTC, Aishwaryak01 commented on src/startup/routes.js
> +const timeEntry = require('../models/timeEntry');
Filename mismatch

2022-12-13 22:30 UTC, Aishwaryak01 commented on src/startup/routes.js
> +const timeEntryRouter = require('../routes/timeEntryRouter')(timeEntry);
Filename mismatch

2022-12-20 23:43 UTC, EvianTan commented
Hey @LeeSingChanYau and @Aishwaryak01 @one-community ,

I would suggest also closed this PR for now. Like I said, this PR contains lots of code changes, it's really hard for people to review. I would expect this kind of huge PR to be split into small ones, to reduce the possibility to break our app. Plus, the key points of re-enabling ESLint is not applying changes, instead, which rules should be keep and which rules should be banned. Since Prettier and ESLint have some rules in conflicts with each other.

2022-12-20 23:46 UTC, one-community commented
Yes, that makes sense. Aishwarya, is there any way to apply your suggestions here in a different PR so that work isn't wasted?

2022-12-22 00:15 UTC, Aishwaryak01 commented
The changes are minor but I doubt separating them in different PR as the changes are scattered in multiple files.

2022-12-22 00:40 UTC, one-community commented
So do you agree with us just closing this and losing those suggestions?

2022-12-22 00:46 UTC, Aishwaryak01 commented
If that benefits all, I am happy to close this. Maye the comments can be covered when the PR is split.

2022-12-22 00:47 UTC, closed without merging