Lucile T - add work confirmation improvements to people report
OneCommunityGlobal/HGNRest pull request #362
Opened 2023-05-23 17:45 UTC by LucileTech

###Description
9. (PRIORITY MEDIUM) Jae: Add work confirmation improvements to People Report (WIP Lucile)
Admin or Owner login → Reports → Reports → People → Choose
Remove “hours logged this week” section: If a user is INACTIVE (has an end date), then the “Hours Logged This Week” square should not show. Center the remaining ones.
Please also add the User’s Title under their name.

THIS PART IS THE ONE NOT FINISHED YET:
Please also add a “Rehireable” section under their name that can be clicked as Yes or No

###Related PR
To test this backend PR you need to checkout the #836 frontend PR.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/836)

###Mainly changes explained:
1 - isRehireable was added to UserProfile Model
2 - isRehireable management and new Date(req.body.endDate) was added in userProfileController

###Before (sorry for my slow connexion)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111132148/e92b0a4c-9f38-4129-963b-645cdada4b9d

###After (sorry for my slow connexion)

https://github.com/OneCommunityGlobal/HGNRest/assets/111132148/1587e394-e643-4f06-9c1c-9b6ade8e35f3

###How to test:
Git checkout Lucile_add_work_confirmation_improvements_to_people_report in the backend
do npm install and npm run build to run this PR locally

Git checkout Lucile_add_work_confirmation_improvements_to_people_report in the frontend
do npm install and npm run start:local 

Admin or Owner login → Reports → Reports → People → Choose someone with an end date 
You should be able to checkout and checkout the rehireable check box on the right.
The chosen check should remain even if the page is refreshed.

Admin or Owner login → Reports → Reports → People → Choose someone without an end date 
You should not see the rehireable checkbox

2023-05-23 21:39 UTC, stevenpaalz requested changes
I am not able to replicate the expected functionality. Upon checking the rehireable box from an admin account of any inactive user and then refreshing the page, the user is reassigned as an active user with an end date of today. The rehireable check box no longer appears. Also relevant to [PR #836](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/836)

https://github.com/OneCommunityGlobal/HGNRest/assets/121642083/ffd666a9-45d7-4cda-800a-d163e5b0bfce

2023-05-24 02:30 UTC, LucileTech commented
> I am not able to replicate the expected functionality. Upon checking the rehireable box from an admin account of any inactive user and then refreshing the page, the user is reassigned as an active user with an end date of today. The rehireable check box no longer appears. Also relevant to [PR #836](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/836)
> 
>  Screen.Recording.2023-05-23.at.5.34.43.PM.mov

Hi @stevenpaalz thank you for your review, can you please git pull on the backend branch and try again? I think you did not have the last comit

2023-05-24 13:04 UTC, stevenpaalz approved these changes
@LucileTech yes, my apologies. With latest commit this appears to be working as intended.
 
![Screenshot 2023-05-24 at 9 01 40 AM](https://github.com/OneCommunityGlobal/HGNRest/assets/121642083/a752bc9e-d080-4671-8a33-c336b4c2685a)

2023-05-25 02:54 UTC, AnishPandita commented
Hi @LucileTech I tested your with the specified backend branch and its working as intended. Great work.
<img width="1435" alt="Screenshot 2023-05-24 at 7 51 51 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/111321945/2f98b2bd-bfa6-443a-9ae8-5221058fa781">
<img width="1439" alt="Screenshot 2023-05-24 at 7 52 17 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/111321945/cf8312e3-3f53-4f09-b9ba-664179ae956f">

2023-05-25 13:46 UTC, LucileTech commented
> Hi @LucileTech I tested your with the specified backend branch and its working as intended. Great work. <img alt="Screenshot 2023-05-24 at 7 51 51 PM" width="1435" src="https://user-images.githubusercontent.com/111321945/240788475-2f98b2bd-bfa6-443a-9ae8-5221058fa781.png"> <img alt="Screenshot 2023-05-24 at 7 52 17 PM" width="1439" src="https://user-images.githubusercontent.com/111321945/240788491-cf8312e3-3f53-4f09-b9ba-664179ae956f.png">

Thank you @AnishPandita can you please approve this PR ?
Thanks

2023-05-25 18:43 UTC, yoyoweiii approved these changes
Hi @LucileTech I've tested your PR and it works as described. Good work!

https://github.com/OneCommunityGlobal/HGNRest/assets/60588210/a46d6b3b-53c3-4cf5-8b78-4c514aa5c528

2023-05-25 19:23 UTC, lchua2314 requested changes
Hi @LucileTech I requested small formatting changes for both the frontend and backend. Please make the changes and I'll approve both my reviews. Functionality works as intended. Amazing work.

Before:
![Before 1](https://github.com/OneCommunityGlobal/HGNRest/assets/46981223/d7d01679-3b64-4c19-addf-38167b64a848)
![Before 2](https://github.com/OneCommunityGlobal/HGNRest/assets/46981223/1b8995d3-43e1-41d9-980d-e65461523ffe)

After:
![After 1](https://github.com/OneCommunityGlobal/HGNRest/assets/46981223/9ab3e887-702e-4280-aff0-3d5f5cb27fb1)
![After 2](https://github.com/OneCommunityGlobal/HGNRest/assets/46981223/2c010e88-3543-42a8-b4c4-279a8af8516d)

2023-05-26 02:20 UTC, papiasharmin commented
Everything is working as  intended after changes. the" Rehireable" checks , unchecks and remaining same after refreshing page and the end date also did not change. Great work.

https://github.com/OneCommunityGlobal/HGNRest/assets/86232710/4ac3f4cb-182e-4a20-849d-363739083c79

2023-05-26 02:26 UTC, papiasharmin reviewed
@LucileTech code is working as intended, only some code formatting error showing from prettier on both userProfileController.js and userProfile.js. great work.

2023-05-26 09:16 UTC, LucileTech commented on src/models/userProfile.js
> +  isRehireable: { type: Boolean, default: false},
Thank you @Ichua2314 I added the space

2023-05-26 19:44 UTC, nathanah approved these changes

2023-05-26 19:44 UTC, nathanah approved these changes

2023-05-27 02:24 UTC, lchua2314 approved these changes

2023-06-10 00:35 UTC, merged