Sav fix lead team of x badge
OneCommunityGlobal/HGNRest pull request #364
Opened 2023-05-27 23:31 UTC by Lunaliar

# Description
This bug resulted from improper backend calls and a typo in the aggregation pipeline of the database for the myTeam collection and null values in backend permissions of several roles. I have removed permissions from the function so it will run faster and refactored the function. This badge should be awarded to users with either the mentor or the manager role and will only count users without the roles of Admin, Owner, Coreteam, manager, or mentor as team members being led. For example, if your user was on a team with 10 users with leadership roles and 5 volunteers they would be awarded a badge for leading a team of 5 users. To test this function make a user a mentor or manager and then add them to a team of at least 5 volunteers to make sure this badge is being awarded properly. Best of luck please watch the video for more clarification.

## Main changes explained:
Fix getTeamMembers function to call database properly
Remove hasPermission calls.
Refactor code to run faster.
…

## How to test:
check into current branch
log as admin user
Make a mentor/manager user
Add user to team with 5 or more volunteers 
isolate tested mentor/manager user in awardBadges
## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HGNRest/assets/98275089/9bb0693a-948b-47af-9815-c1dae67d2087

2023-05-31 17:25 UTC, 20chen-7 approved these changes
The function is intended. Everything looks good. This is some error in the terminal after the test. I am not sure that is another error that may be required to solve in the future.
<img width="405" alt="Screenshot 2023-05-31 at 11 23 53 AM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/f3351155-8607-4625-aa93-fe806177bfd1">
<img width="805" alt="Screenshot 2023-05-31 at 11 20 47 AM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/4228303f-4bbb-4a75-8580-edb9b48f888b">

2023-05-31 19:15 UTC, Lunaliar commented
Awesome! If I had to take a guess based on the error message "onsole is not defined" there may be a typo on a console log somewhere. Dont worry Ill do a sweep of all console logs before we merge.

2023-06-01 19:42 UTC, lchua2314 requested changes
Hi, @Lunaliar I want to say again, I really like your video. I have requested some changes that you are familiar with from PR #366: 
1. Reverting double quotes back to single quotes to match the rest of the codebase.
2. hasPermission should be removed because it's an unused constant.
3. As chen has stated, console logs should be removed.

When I tested the feature, I refreshed the profile page and found two duplicate badges. 
![Dup badges](https://github.com/OneCommunityGlobal/HGNRest/assets/46981223/518750e2-0413-492c-9e17-272ad753fda5)

When I refresh the page, it shows one badge. 
![Refresh](https://github.com/OneCommunityGlobal/HGNRest/assets/46981223/e103be43-78cc-43eb-a97c-f1476d8abeba)

Maybe this is just a frontend-issue or I missed something, but I thought I should bring it up.

Other than that, everything works as intended. Good job!

2023-06-01 19:42 UTC, lchua2314 commented on src/cronjobs/userProfileJobs.js
> +const { CronJob } = require("cron");
Please revert the double quotes back to single quotes. I'm assuming it's the linter that's doing this.

2023-06-01 19:42 UTC, lchua2314 commented on src/helpers/userHelper.js
> +const hasPermission = require("../utilities/permissions");
Please remove hasPermission because it's an unused constant.

2023-06-01 19:42 UTC, lchua2314 commented on src/helpers/userHelper.js
> +    console.log("Increase Badge Count", personId, badgeId);
As chen as stated, please remove console.logs used for testing because they hinder performance.

2023-07-05 01:14 UTC, closed without merging