XiaoW fix getOrgData logic
OneCommunityGlobal/HGNRest pull request #398
Opened 2023-06-09 06:48 UTC by wang9hu

# Description
Dashboard will send a get request to '.../dashboard/leaderboard/org/data' and it will takes several seconds to get response for React main, and for React dev it will even take minutes to resolve (more test users). The response for this request is only for the first item on leaderboard (the 'HGN Totals' one).
![Screenshot 2023-06-08 191222](https://github.com/OneCommunityGlobal/HGNRest/assets/77769556/b205f9eb-3ec4-463d-b950-7a55b6ff680c)

Also The backend logic for this type of request is incorrect, and fixing this will resolve this whole issue.

(Priority low) Fixes LEADERBOARD COMPONENT 4 

## Main changes explained:
- Fix the aggregate pipeline logic (details see comments in file) 
- remove the second time consuming DB query and integrate it in the above pipeline
…

## How to test:
1. check into dev, run app in a new incognito browser, and on dashboard, check the first item on leaderboard to see how long it takes to update(usually minutes). Or you can open chrome developer tools and search network tab for the request sending to '.../dashboard/leaderboard/org/data' and see how long it takes for its status to change from pending to 200
2. check into this branch, and do the same thing.
3. compare the times.

## Note:
I am still learning Mongdb, and if you notice anything I could improve please let me know as well.

2023-06-09 14:00 UTC, stevenpaalz requested changes
Hi Xiao, I have tested this a few times but I am not seeing significant improvements in response time. On dev it took me 7.4 minutes. I tested it 4 times on this branch and had response times of 7 mins, 6.9 mins, and 6.9 mins. 

Could you explain a bit further on what you are trying to change here?

2023-06-09 17:34 UTC, wang9hu commented
> Hi Xiao, I have tested this a few times but I am not seeing significant improvements in response time. On dev it took me 7.4 minutes. I tested it 4 times on this branch and had response times of 7 mins, 6.9 mins, and 6.9 mins. 
> 
> Could you explain a bit further on what you are trying to change here?

@stevenpaalz Hi, Steven, did you checkout to this branch and test it again for comparison?

2023-06-09 19:27 UTC, 20chen-7 approved these changes
I finally know how to test this one. Thank you! And this is intended.
![Screenshot 2023-06-10 at 2 57 01 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/f94a4a93-c376-4372-9fdd-5545da3d49c7)
![Screenshot 2023-06-10 at 2 52 14 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/e4fee924-32cf-4ec2-a8ab-5bc2c243f468)

2023-06-09 19:39 UTC, wang9hu commented
> 



> Looks like the new version is faster than before. For the previous version, it takes roughly 2.21 seconds, and now it is 1.85 seconds. ![IMG_5063](https://user-images.githubusercontent.com/102696148/244784766-1d1440e8-c1ba-4aa0-9661-69481da31e90.PNG) ![IMG_5064](https://user-images.githubusercontent.com/102696148/244784771-d8ce87d9-7bfa-4bf6-bdf8-7f080b93d0f6.PNG)

2023-06-09 19:43 UTC, wang9hu commented
> Looks like the new version is faster than before. For the previous version, it takes roughly 2.21 seconds, and now it is 1.85 seconds. ![IMG_5063](https://user-images.githubusercontent.com/102696148/244784766-1d1440e8-c1ba-4aa0-9661-69481da31e90.PNG) ![IMG_5064](https://user-images.githubusercontent.com/102696148/244784771-d8ce87d9-7bfa-4bf6-bdf8-7f080b93d0f6.PNG)

Hmm, during my testing it took minutes on development branch, did you use a new incognito browser? If there was cached data, app will just use that.

2023-06-09 20:37 UTC, KurtisIvey approved these changes
Approved! Quite the performance gain you've made with nearly a 6000% improvement in speed. Phenomenal job 


Like you've mentioned, If reviewers aren't seeing time differences, they'll want to make sure they run npm build after checking out the branch for pr#398. Took me a bit until I realized this myself.

Old backend
![works](https://github.com/OneCommunityGlobal/HGNRest/assets/19482363/ece660cf-9454-4f72-8726-0ff92f115dda)

With PR implemented
![works](https://github.com/OneCommunityGlobal/HGNRest/assets/19482363/439c27a8-843d-490a-9b65-9202da7a6ebb)

2023-06-10 01:27 UTC, 20chen-7 commented
> > Looks like the new version is faster than before. For the previous version, it takes roughly 2.21 seconds, and now it is 1.85 seconds. ![IMG_5063](https://user-images.githubusercontent.com/102696148/244784766-1d1440e8-c1ba-4aa0-9661-69481da31e90.PNG) ![IMG_5064](https://user-images.githubusercontent.com/102696148/244784771-d8ce87d9-7bfa-4bf6-bdf8-7f080b93d0f6.PNG)
> 
> Hmm, during my testing it took minutes on development branch, did you use a new incognito browser? If there was cached data, app will just use that.

I did use incognito browser on chrome, safari, firefox. But it is still 1.81s. I am not sure what I should do for the next step.
![Screenshot 2023-06-09 at 7 24 17 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/6ab3ce72-7c86-4201-a7a6-ac023b8de1ef)

2023-06-10 03:14 UTC, bienzguoa approved these changes
Good job! It improved quite a lot! From 6.9 min to 2.04 s. And the comment in the code really helps for understanding this logic.
On dev:
<img width="1454" alt="Screenshot 2023-06-09 at 10 02 59 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/92126559/896c5888-ab4b-4bc8-9436-0eb923801633">
On this branch:
<img width="1456" alt="Screenshot 2023-06-09 at 10 08 02 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/92126559/aff845d3-3c69-4d89-8c7c-d22fdffcb1e9">

2023-06-10 03:50 UTC, wang9hu commented
Hi, @20chen-7, thanks for keep trying! Did you run `npm run build` for both development branch and my PR branch?

2023-06-13 15:21 UTC, Chuehleo approved these changes
Good work! The improvement was amazing, it went from 7.7 mins -> 1.98 s.
![Screenshot 2023-06-13 074800](https://github.com/OneCommunityGlobal/HGNRest/assets/122568562/340052e1-d8cd-424c-a0b7-6bfbcf280afe)
![Screenshot 2023-06-13 081457](https://github.com/OneCommunityGlobal/HGNRest/assets/122568562/026d0c2c-e224-460a-83e4-bcf45205149e)

2023-06-14 13:24 UTC, stevenpaalz approved these changes
My apologies, I must not have had the latest version of this build. Code seems to be working correctly. I ran multiple tests and request always resolved between 1 and 7 seconds. Nice job.

2023-06-14 19:58 UTC, one-community commented
Thank you all, moving this to final review!

2023-06-14 23:16 UTC, AuroraLovesWhales approved these changes
Hi @wang9hu. I have reviewed your PR and I can verify that there is a huge improvement (from 7.3min to 1.8s). Amazing work!
Before:
![Pasted Graphic 2](https://github.com/OneCommunityGlobal/HGNRest/assets/44281916/f69020c9-397a-48ab-b644-b62b7134dcf2)

After:
![Pasted Graphic 3](https://github.com/OneCommunityGlobal/HGNRest/assets/44281916/161490af-9b58-46e4-9867-8043fef92773)

2023-06-14 23:27 UTC, merged

2023-06-17 03:56 UTC, EdwinLauM commented
Works as intended! Great job! 

Before: 

<img width="705" alt="Screen Shot 2023-06-16 at 8 53 57 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/74cb2c2a-fd66-4a52-a996-7abca0398aa0">

After: 

<img width="781" alt="Screen Shot 2023-06-16 at 8 26 39 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/02d71c94-6911-4f3f-b290-452b1f1ad2c0">