Xiaoyu add editable container for info
OneCommunityGlobal/HGNRest pull request #452
Opened 2023-07-20 00:34 UTC by 20chen-7

# Description
![Screenshot 2023-07-19 at 6 30 58 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/ac23c688-6414-4a5c-aeae-b747c12cf6e7)

## Related PRS (if any):
To test this backend PR you need to checkout the #996 frontend PR.
…

## Main changes explained:
- Add information controller
- modifies routes
- add informationrouter
- modify server
- add information models
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
Login as Owner:
https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/b64a595e-2d8e-4e11-b645-30eec40ac6e8
Login as Admin:
https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/60d049a5-5014-421a-aeb9-cd3add6a16b0

Login as Volunteer:
![Screenshot 2023-07-19 at 6 21 02 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/f310d23c-31a2-4d68-9f1f-3eca10960404)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-07-20 03:06 UTC, ramyaram2092 reviewed
Left a detailed review in the frontend PR . I will approve the PR based on the feedback for my comments in the front end PR

2023-07-20 03:47 UTC, luisarevalo21 commented
Hello @20chen-7,

I reviewed your PR on the frontend and suggested some feedback. 
Overall your work on the PR was great. I'll approve this one once you review my suggestions and take them into consideration. 

Thanks

2023-07-20 06:03 UTC, iTvX commented on src/controllers/informationController.js
> +  const addInformation = function (req, res) {
You first create a new Information and then create another new Information after checking for name uniqueness.  I suggest you may first check for name uniqueness, and then create the Information.

2023-07-22 05:23 UTC, iTvX commented on src/controllers/userProfileController.js
> +  const putInfoCollections = function (req, res) {
I noticed that you're using `UserProfile.updateMany({}, { $set: { infoCollections } })` to update the `infoCollections` field for all users. I would suggest considering including the user's ID and their corresponding `infoCollections` in the request body, and then iterating over these users and `infoCollections` in the method to update the `infoCollections` for each user. 

```javascript
const { userInfos } = req.body; // userInfos should be an array of { userId, infoCollections }
for (let userInfo of userInfos) {
  await UserProfile.updateOne({ _id: userInfo.userId }, { $set: { infoCollections: userInfo.infoCollections } });
}

2023-07-25 06:26 UTC, DavidC0126 requested changes
I have tested the PR with FE [PR#1025](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1025) and everything works as intended. I leave the comment on FE PR. 

However, when I pull down the branch and want to npm run start, it said that badgeController.js is missing so I manually add the file back to the BE (I did not see the file in this branch).

2023-07-25 18:42 UTC, DavidC0126 approved these changes
It looks good to me.

2023-07-28 15:35 UTC, 20chen-7 commented
> Hello @20chen-7,
> 
> I reviewed your PR on the frontend and suggested some feedback. Overall your work on the PR was great. I'll approve this one once you review my suggestions and take them into consideration.
> 
> Thanks

Fixed

2023-08-04 16:36 UTC, ThapeloMasasa reviewed
The functionality works as intended... added more information on the frontedn PR

2023-08-06 04:28 UTC, veronicacheng2 approved these changes
Hi @20chen-7, I have tested the PR together with #1052 and left comments there. Everything works as intended.

2023-08-06 06:35 UTC, winghojackyli approved these changes
I've tested this PR and it works great with frontend. Comment left on frontend.

2023-08-13 01:54 UTC, TheDescendant39 reviewed
Hi @20chen-7, I reviewed you PR and commented on [#1025](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1025#pullrequestreview-1575581126)

2023-08-16 23:29 UTC, winghojackyli approved these changes
Hi @20chen-7 , updated review is availble on the corresponding frontend PR. Comments left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1025#pullrequestreview-1581552404

2023-08-19 03:57 UTC, merged