Masasa_create_badge_permission
OneCommunityGlobal/HGNRest pull request #534
Opened 2023-09-12 19:04 UTC by ThapeloMasasa

# Description
This PR enables the user to have access to badges and have access to creating padges in the backend,  to enable the user to have the ability to create badges.
<img width="748" alt="Screenshot 2023-09-09 at 9 25 22 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/73863365/390dbed4-6e5a-456c-bbb8-3014b0b8f33a">
<img width="1384" alt="Screenshot 2023-09-09 at 9 29 45 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/73863365/f43edf6c-7db5-44e7-8081-830f985d62ac">

## Related PRS (if any):
To test this backend PR you need to checkout the [#1287](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1287) frontend PR.
…

## Main changes explained:
-added  individualpermission check to postbadges and view badges in badgesController
…

## How to test:
1. Follow the test instructions mentioned on the frontend

2023-09-12 21:41 UTC, navneeeth approved these changes
Hello, @ThapeloMasasa! I have reviewed your changes and they work as intended. Good implementation! I have commented a full review on the [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1287#pullrequestreview-1623199960).

2023-09-13 05:20 UTC, DavidC0126 reviewed
Tested the PR with FE PR#1287, left the comment on FE PR.

2023-09-13 18:56 UTC, Shiwani99 commented
Hi,
I tested the PR and I have left my comments at PR#1287

2023-09-13 21:24 UTC, vikrambadhan approved these changes
Hi, I tested your PR with FR #1287 and works as intended!

2023-09-14 02:43 UTC, wantingxu7 commented
Tested with FE #1287 and comment there

2023-09-14 20:01 UTC, TuanDinh140194 commented
Hi! I have tested your PR#1287 function and review there

2023-09-14 22:13 UTC, robertoooc approved these changes
Tested along with FE 1287, left comments on other PR.

2023-09-19 11:35 UTC, Chris33871 commented
Hi @ThapeloMasasa , 

I left a comment on the Front End post

2023-10-14 03:39 UTC, StrawberryCalpico approved these changes
I reviewed your PR, the details of test: [FE #1287](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1287#pullrequestreview-1677724666)

2023-10-14 07:34 UTC, malikjahanzaib approved these changes
Hi @ThapeloMasasa, I have reviewed this PR and everything seems to work as described. Detailed comments on FE #1287.

2023-10-15 00:23 UTC, RheaWu1212 commented
Hi! I have tested your PR#1287 function and review there

2023-10-27 22:31 UTC, nathanah requested changes
I don't think `seeBadgeManagementTab` should exist as a permission as it's just a combination of `seeBadges` and `createBadges`. However, if you are to make it, then you will also need to add it to `createInitialPermissions.js` under every role that should have it.

2023-10-27 22:31 UTC, nathanah commented on src/controllers/badgeController.js
> +    if (!await hasPermission(req.body.requestor.role, 'seeBadges') && !await hasIndividualPermission(req.body.requestor.requestorId, 'seeBadgeManagementTab')) {
```suggestion
    if (!await hasPermission(req.body.requestor, 'seeBadges') && !await hasPermission(req.body.requestor, 'seeBadgeManagementTab')) {
```
Probably need to pull the latest changes. The arguments have changed.

2023-10-27 22:31 UTC, nathanah commented on src/controllers/badgeController.js
> +    if (!await hasPermission(req.body.requestor.role, 'createBadges') && !await hasIndividualPermission(req.body.requestor.requestorId, 'seeBadgeManagementTab')) {
```suggestion
    if (!await hasPermission(req.body.requestor, 'createBadges') && !await hasPermission(req.body.requestor, 'seeBadgeManagementTab')) {
```
Probably need to pull the latest changes. The arguments have changed.

2023-11-05 00:13 UTC, shubhankarval approved these changes
Hey @ThapeloMasasa, left a comment on FE PR [#1287](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1287).

2024-02-08 02:23 UTC, Pandani07 approved these changes
This PR works as intended along with the frontend PR, left a review there.

2024-02-29 04:07 UTC, skaush21 reviewed
comment on frontend [PR 1287](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1287)

2024-06-05 01:55 UTC, closed without merging