allow user post role
OneCommunityGlobal/HGNRest pull request #546
Opened 2023-09-24 05:38 UTC by Lin1404

# Description
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/78375725/ea4cd8a9-4613-4329-aff5-e091b550adf2)

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ Tasks→ task→…
5. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-09-24 20:59 UTC, wantingxu7 approved these changes
Hi Haohui, good work, the function works well. Left detailed comment in FE

2023-09-26 01:22 UTC, JYXiao-2021 approved these changes
Hi, I left my comment at FE.

2023-09-27 20:38 UTC, navneeeth approved these changes
Hello! The PR works as intended. Good job! Commented a detailed review on the frontend PR.

2023-09-28 07:07 UTC, vikrambadhan approved these changes
Hi, the PR works well. Left my comment on FE

2023-09-29 21:43 UTC, Shiwani99 approved these changes
Hi,
Great work. Added comments at frontend PR#1307.

2023-10-02 23:11 UTC, Bhagyashree444 approved these changes
Well done! Works as expected. I've dropped a comment on the frontend PR#1307.

2023-10-09 19:06 UTC, StrawberryCalpico requested changes
Hi! I just reviewed your PR, it seems like there's a conflict with the current branch, so that I can't find the add new user permission role. the video was in  [#1307](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1307#pullrequestreview-1665122487)

2023-10-11 02:48 UTC, malikjahanzaib requested changes
Hi @Lin1404, it seems this branch has some conflicts. I have checked out both FE and BE branches. When I try to go to "dashboard→ Other Links→ Permissions Management→ Manage User Permissions" from an owner account, I search for the user to assign the permission but there appears no “Add New User Permissions Role”. Below is the test recording.

Left detailed review on FE.

2023-10-22 01:52 UTC, Cloid commented
Left comments in FE #1307.

2023-10-27 02:45 UTC, ChirayuRai commented
Hey! I added my comments in FE #1307

2023-10-27 21:31 UTC, nathanah commented on src/controllers/rolesController.js
> +      res.status(403).send("You are not authorized to create new roles.");
This change isn't needed as of PR547.
https://github.com/OneCommunityGlobal/HGNRest/pull/547

2023-10-29 01:52 UTC, palakgosalia commented
Hey, I left comments in PR 1307. Thank you

2023-12-23 07:01 UTC, Alforoan reviewed
I left my comment on the fe pr #1307

2024-01-27 01:32 UTC, closed without merging