added statement to clear user cache if needed so profile page is upda…
OneCommunityGlobal/HGNRest pull request #550
Opened 2023-09-29 01:01 UTC by robertoooc

# Description
When you visit a Team member's list and remove a member, then visit that user's profile you'll notice that their teams section is not updated immediately. The update can take up to a few minutes to finally show.
<img width="820" alt="Screenshot 2023-09-28 at 5 14 05 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/117053202/7276e0d4-de35-409a-801b-f9a9b0b14ded">

## Related PRS (if any):
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Added an if statement to teamController.js, clears the user cache if any to get the most up to date user profile
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build`, and`npm start` to run this PR locally
3. check frontend instructions

2023-09-29 21:28 UTC, Shiwani99 requested changes
Hi,
Left comments at frontend PR#1350.

2023-09-30 05:27 UTC, JeffLi117 requested changes, later dismissed
Left commends on FE PR #1350.

2023-10-01 00:23 UTC, RheaWu1212 commented
Left comments on FE PR #1350.

2023-10-01 05:20 UTC, astrjc0326 commented
Left commends on FE PR #1350.

2023-10-01 17:15 UTC, beblicarl commented
I left a [comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1350#issuecomment-1742142709) on the frontend of this PR

2023-10-02 21:41 UTC, Bhagyashree444 reviewed
I've left a comment on the frontend PR#1350.

2023-10-04 23:21 UTC, Vishala09 commented
I have left the comment on front-end PR 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1350#pullrequestreview-1658633448

2023-10-05 20:25 UTC, Shreyj14 commented
Hi @robertoooc left a comment for this on the FE PR 1350.
There needs to be a fix for the team member not being updated instantly.

2023-10-06 15:57 UTC, Shiwani99 approved these changes

2023-10-06 23:33 UTC, Shubhu0 reviewed
I've left a comment on the frontend PR#1350.

2023-10-07 08:47 UTC, Vishala09 approved these changes

2023-10-07 20:26 UTC, malikjahanzaib approved these changes
Hi @robertoooc, this PR functions as intended. Left detailed review on BE thread PR #1350. Great job!

2023-10-10 02:34 UTC, StrawberryCalpico approved these changes
Hi! I just test your PR, it worked perfectly, Good Job! Details at [#1350](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1350#pullrequestreview-1665858825)

2023-10-14 01:17 UTC, KurtisIvey approved these changes
Functions perfectly with the front end.

2023-10-14 01:55 UTC, merged