Create a Weekly Summaries Reports recipient button for Owners
OneCommunityGlobal/HGNRest pull request #566
Opened 2023-10-11 06:53 UTC by mounica-dingari-by

# Description
Show and editable list of who is currently receiving the Weekly summary report and
it's password protected with the test account 
[mounica_test20@gmail.com]
Password@1234

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/49270410/e287dd82-e5a0-4920-99e7-5f7e145ad4f6)

## Related PRS (if any):
To test this backend PR you need to checkout the #1400 frontend PR.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to Reports→ Weekly Summaries Reports →  Weekly Summaries Reports button
5. Enter the password and if the user is Authorized, a popup shows up, with list of Weekly Summary recipients
6. Test if you're able to add/delete the Weekly Summary recipients.
7. The weekly summaries will be sent to the recipients through email. In order to test this, add yourself to the recipients and to send/receive email using Gmail API, using OAuth2 and nodemailer, kindly follow the below video and setup up a test mail id.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

Fill below variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/49270410/19ef1602-fa6c-4ea2-b923-b78b2527735c

![Screenshot from 2023-10-10 13-57-37](https://github.com/OneCommunityGlobal/HGNRest/assets/49270410/3ea7cc36-ca8f-415d-87ee-4a83a888be03)

## Note:
Include the information the reviewers need to know.

2023-10-14 00:04 UTC, StrawberryCalpico requested changes
Details in [#1400](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1400#pullrequestreview-1677568773)

2023-10-19 00:56 UTC, malikjahanzaib requested changes
Left comment on FE [PR #1400](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1400#pullrequestreview-1686468517).

2023-10-28 10:49 UTC, Bali2Mohit commented on src/helpers/userHelper.js
> +const sendMail = require("../utilities/nodemailer")
Hi @mounica-dingari-by 
I am getting Error: Cannot find module '../utilities/nodemailer'. I checked the utilities folder, but there is no nodemailer file in that.
<img width="573" alt="Screenshot 2023-10-28 at 11 43 27" src="https://github.com/OneCommunityGlobal/HGNRest/assets/94716419/c44050d3-f547-4b5b-b318-a58bd53c7cd1">

2023-11-16 22:49 UTC, ptrpengdev commented
Hi @mounica-dingari-by, it appears that there are code conflicts with the latest code in the development branch. Could you please take a moment to resolve these conflicts? Thank you!

2023-11-17 18:00 UTC, Changhao3220K commented
Hi @mounica-dingari-by
I am trying to run backend on the local server but get this error.
<img width="803" alt="Screenshot 2023-11-17 at 12 58 54 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/104778270/512ee766-2753-4099-8629-f36c561324c9">
do you have any idea about how could I fix this?

2023-11-17 18:19 UTC, Changhao3220K reviewed
Hi @mounica-dingari-by
I am trying to run backend on the local server but get this error.
<img width="803" alt="Screenshot 2023-11-17 at 12 58 54 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/104778270/e2d20427-44be-45de-9542-6a68b1a96814">
please help me check if i got anywhere wrong.

2023-11-17 21:01 UTC, Shuhua-L requested changes
Hey @mounica-dingari-by, I checked out the branch and ensured it's up to date using `git pull` and `npm install`. However, I can't get the backend up and running due to the missing module `nodemailer`. See the screenshot for more details.

<img width="903" alt="PR1400+566" src="https://github.com/OneCommunityGlobal/HGNRest/assets/83729360/668d2a76-4129-4e37-b1d8-75615fd13aee">

2023-11-18 05:59 UTC, wanglu1207 commented
Hi @mounica-dingari-by, there is an error shows that "Error: Cannot find module '../utilities/nodemailer'". More details can be found from the screenshot.

<img width="584" alt="mounica_weekly_summary_reports_button_backend" src="https://github.com/OneCommunityGlobal/HGNRest/assets/67501735/c71d22fc-1b9d-42d5-8a38-0016c497eba4">

2023-11-18 06:20 UTC, ptrpengdev commented
Hi @mounica-dingari-by, same here with the missing file. Failed to start the server. Line 16 "const sendMail = require("../utilities/nodemailer")" in the userHelper.js file.

2023-11-18 22:04 UTC, palakgosalia commented
Hey, I had an issue starting up the backend server. Attached is the screenshot. Thank you

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/104417272/ed47929a-935b-48f5-b5c3-2848c1e3f1d8)

2023-12-07 16:58 UTC, DragonSlayer2401 commented
I tested this PR and the related frontend PR. The frontend PR started up fine but this PR gave a bunch of errors like mentioned by others above. Please see image below and check the frontend PR for a video:

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/102876103/023cf6c9-f455-4076-a1ce-c80b171cf52f)

2023-12-09 01:25 UTC, sucheta90 reviewed
Please refer to the comment on Front End [PR1400](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1400#pullrequestreview-1773404720)

2024-02-18 02:06 UTC, brandta-1 requested changes
# Review
After checking out the branch and running 
```
npm install
npm run build
npm start
```
My node terminal displays the following error: ```Error: Cannot find module '../utilities/nodemailer'```

I will link this review to my [front end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1400#pullrequestreview-1887065842)

2025-04-28 04:11 UTC, closed without merging