Roberto - Adds email notification for Owner create/reset password
OneCommunityGlobal/HGNRest pull request #569
Opened 2023-10-13 06:56 UTC by robertoooc

# Description
<img width="819" alt="Screenshot 2023-10-10 at 1 34 00 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/117053202/27f16c0b-06c2-457c-ab8a-f330c38e1ae4">
This PR will send an email when a new Owner account is either created or their password is reset.

## Related PRS (if any):
Isn't related to any PR but test with latest frontend

## Main changes explained:
- Imports and uses emailSender function in userProfileController.js. Email is sent when a new owner account is created or when a owner's password is reset. 
- Adds more security checks to the reset password function because it didn't originally check permissions.

# IMPORTANT SET UP
1. check into current branch
2. You need to create your own OAuth credentials - Watch this video up to 6:56 ([Where to get new env variables](https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s)) 
3. If the video above gives you issues at 6:00 when the app isn't verified and doesn't let you proceed, Watch this video to fix that ([How to fix the OAuth Error](https://www.youtube.com/watch?v=x_NPvk0pk8g))
4. Add these variables to your environment file with your own credentials
`REACT_APP_EMAIL=The email you use for the OAuth`
`REACT_APP_EMAIL_CLIENT_ID=Watch the video to get this`
`REACT_APP_EMAIL_CLIENT_SECRET=Watch the video to get this`
`REACT_APP_EMAIL_REDIRECT_URI=https://developers.google.com/oauthplayground`
`REACT_APP_EMAIL_REFRESH_TOKEN=Watch the video to get this`
`sendEmail=true`
5. In `src/controllers/userProfileController.js`, change the emails to whatever recipient email you wish to use on lines `249` and `923` (ex: onecommunityglobal@gmail.com -> yourEmail@gmail.com) -It should be different from the email in the .env file
6. Do `npm install`, `npm run build`, and `npm start`  (Make sure to run build after making any changes)
7. In the frontend check into development and log into an Owner account
8. Verify that creating an Owner account results in an email sent to your recipient
9. Verify that resetting an Owner account's password results in an email sent to your recipient

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/117053202/75d5eeb7-386c-4749-a681-34929eefbcd8

## Note:
- If you have any issues in the how to test section check out these docs or feel free to ping me for help: 
[Implement a feature related to Email sending and testing](https://docs.google.com/document/d/1HJJTDtWykjGb4IfiIFlHXDfp_IABvmwKxsMPqqF6rG8/edit)
[Update Oauth 2.0 Gmail Email Token Refresh Instructions](https://docs.google.com/document/d/1By_Ls6RGbesMgZvRzU2zIPIJtLBKMgQjabTUH2ZM8kE/edit)

- To prevent unintended email notifications, it is crucial to stop the local server running on your machine before midnight Pacific Time on Saturday. This precaution ensures that the cron job does not execute on your local server and random emails are not sent to everyone.

2023-10-17 21:40 UTC, StrawberryCalpico reviewed
<img width="572" alt="Screenshot 2023-10-17 at 5 35 56 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/114443664/ab4db6aa-e28c-4725-bff2-cbdf443ac851">
<img width="765" alt="Screenshot 2023-10-17 at 5 36 24 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/114443664/0eb96d0b-9d3b-4b66-9be2-01d83f47381a">



Hi, I tried to tested your PR. I followed the instructions and set up the google API, but I didn't received the email after creating new "owner".  I kept receiving error messages(400). I added a console.log in the try catch [emailSender.js](https://github.com/OneCommunityGlobal/HGNRest/blob/728b83d1dcf53b48e248b5864e10449afa20b5ec/src/utilities/emailSender.js#L64C34-L64C34) to print the error message.

2023-10-21 10:35 UTC, malikjahanzaib approved these changes
Hi @robertoooc, I tested this PR and everything works great. When an owner account is created or there is a password reset for an owner account, an email is sent out. Great job!!!

Screenshots:

<img width="960" alt="Screenshot 2023-10-21 033151" src="https://github.com/OneCommunityGlobal/HGNRest/assets/46221334/8897fdd9-7774-45bc-a369-8706f8150986">

<img width="960" alt="Screenshot 2023-10-21 033201" src="https://github.com/OneCommunityGlobal/HGNRest/assets/46221334/10da5945-7f0c-4254-bf00-15351890f651">

<img width="960" alt="Screenshot 2023-10-21 033034" src="https://github.com/OneCommunityGlobal/HGNRest/assets/46221334/503fdf8e-6309-4cb6-8d93-b6d6fe2e8552">

2023-10-22 00:18 UTC, shubhankarval approved these changes
Hey @robertoooc, I tested this PR and it works exactly as expected, good job! 
\
Creating Owner account:
![pr](https://github.com/OneCommunityGlobal/HGNRest/assets/59073366/91041212-dcdb-4f2b-8100-36ec042bbe27)
![pr2](https://github.com/OneCommunityGlobal/HGNRest/assets/59073366/2b0089b3-f19f-4f28-a9f1-99cf8870073f)
\
Resetting password for Owner account:
![pr3](https://github.com/OneCommunityGlobal/HGNRest/assets/59073366/1f2678df-bdd7-4f17-9c40-ecaab8b90741)
![pr4](https://github.com/OneCommunityGlobal/HGNRest/assets/59073366/3318025e-eacb-45f8-8c2b-f99688ac81d9)

2023-10-22 05:59 UTC, John-Flavian commented on src/controllers/userProfileController.js
> +      const requestor = await UserProfile.findById(req.body.requestor.requestorId).select('firstName lastName email role').exec();
Nicely done.

Although good practice of "seperation of concerns" would be nice.

2023-11-03 03:03 UTC, Shuhua-L approved these changes
Hi @robertoooc, I successfully tested the PR, and everything is working as intended. Nicely done!

To be more specific:
- I logged in as an Owner (Shuhua Owner), created a new owner account (Shuhua Owner1), and received an email
  <img width="1398" alt="PR569-1" src="https://github.com/OneCommunityGlobal/HGNRest/assets/83729360/26e9ff26-8096-4544-95ce-037b2e8f5da1">
  <img width="909" alt="PR569-2" src="https://github.com/OneCommunityGlobal/HGNRest/assets/83729360/c3497cd2-5893-4067-a55c-974190cb67ba">

- I then reset the password of the new account and received another notification
  <img width="910" alt="PR569-3" src="https://github.com/OneCommunityGlobal/HGNRest/assets/83729360/9aeb578a-6772-4b9f-b380-51db26aab3b8">

2023-12-12 23:27 UTC, ilyaflaks commented
@robertoooc I tested this PR. The "reset password" functionality works just as intended! Good job!
<img width="1137" alt="969-password-reset-email" src="https://github.com/OneCommunityGlobal/HGNRest/assets/105448137/9b1bdf46-dc62-4a0b-b7a4-d6f5421aed72">

However, when I try to create a new user, I get a 502 Server error: 
<img width="1728" alt="969branch-front-end-error" src="https://github.com/OneCommunityGlobal/HGNRest/assets/105448137/76052cbc-82cf-4958-8d88-1939463218fa">


When I console log the error on the backend, the message is: **userProfile validation failed: location: Cast to string failed for value "{...}" (type Object) at path "location"**
<img width="1728" alt="969branch-save-error" src="https://github.com/OneCommunityGlobal/HGNRest/assets/105448137/d1182c76-312e-44c8-ba11-092acff8b052">

When I console log **req.body.location**, it looks like this: 
<img width="348" alt="969branch-create-error" src="https://github.com/OneCommunityGlobal/HGNRest/assets/105448137/d6f349b4-ad66-46ec-b61d-d1af6bd61015">


I can't immediately see how the changes you made to your code can lead to this error. When I create a user in the "development" branch with the same information I don't get any errors. The object for req.body.location looks the same: 
<img width="274" alt="dev-branch-create-success" src="https://github.com/OneCommunityGlobal/HGNRest/assets/105448137/d5da5058-ea75-4feb-bc47-27415831db00">

This is also the case for me for the branch **Roberto_Create_Notification_For_Main_Branch**

2024-02-15 07:13 UTC, XiaohanMeng approved these changes
I have tested this Pull Request with my owner account, and it worked as intended. 
First, I logged into my owner account and created a test account with the owner role. Here is the email I received. 
![PR569_result1](https://github.com/OneCommunityGlobal/HGNRest/assets/113215317/f6b9f85b-08b9-43d5-ad2a-9dec91c13a4f)


Then, I reset the password for the test owner account and received a new email.
![PR569_result2](https://github.com/OneCommunityGlobal/HGNRest/assets/113215317/12772315-d4d5-48b8-93f9-30c639c65774)

2024-02-18 04:35 UTC, huangweihou approved these changes
Hi @robertoooc, I tested an owner account was created and a password reset for an owner account. Both worked correctly with emails received. Great job!!!
Please take below screenshots as reference:
<img width="805" alt="Screen Shot 2024-02-17 at 11 28 59 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/53529971/4ae11d4b-e0f5-4b7f-87d8-021ae126fa51">
<img width="805" alt="Screen Shot 2024-02-17 at 11 28 59 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/53529971/518d44b2-90e4-4a9b-8e66-9ce8204ae08c">

2024-02-20 01:57 UTC, psharma1984 commented
Hi @robertoooc, tested with an owner account. As a new user is created and a password is reset for an owner account, it sends an email to the recipient.
Please take below screenshots as reference:
![Screenshot from 2024-02-19 17-53-55](https://github.com/OneCommunityGlobal/HGNRest/assets/123996264/dcdadbc2-1a84-4020-9c78-76347562962c)
![Screenshot from 2024-02-19 17-49-08](https://github.com/OneCommunityGlobal/HGNRest/assets/123996264/2eeec60d-e0f8-4ca2-ad10-f9b67ee0f68b)

2024-02-20 02:03 UTC, psharma1984 commented
Hi @robertoooc, I tested an owner account was created and a password reset for an owner account. Both worked correctly with emails received. Great job!!!
Please take below screenshots as reference:
![Screenshot from 2024-02-19 17-53-55](https://github.com/OneCommunityGlobal/HGNRest/assets/123996264/5182377d-7dd2-4769-9146-79e39bf6439d)
![Screenshot from 2024-02-19 17-49-08](https://github.com/OneCommunityGlobal/HGNRest/assets/123996264/18a3adde-d00c-460a-b4c7-bbcc470a57e8)

2024-02-20 02:15 UTC, psharma1984 approved these changes

2024-02-27 06:31 UTC, skaush21 approved these changes
features work well!
* followed instructions on video -> followed instructions on second video as well
* added specified code to .env
* navigated to src/controllers/userProfileController.js added new email to lines 274 and 946.
* npm install, npm run build, npm run start, did the same for frontend
* logged in using owner account
* created owner account, received email verification
* reset owner account password, received email verification
All mentioned features worked well, great job!
I do want to point out that there is a console warning, although I dont think its anything to worry about. 
<img width="714" alt="account appears on user list" src="https://github.com/OneCommunityGlobal/HGNRest/assets/141872402/a7bf1837-4220-4a37-83db-34099e63cdf5">
<img width="714" alt="create account" src="https://github.com/OneCommunityGlobal/HGNRest/assets/141872402/d0d80100-e2ce-457f-b986-1fc20208f413">
<img width="714" alt="reset password" src="https://github.com/OneCommunityGlobal/HGNRest/assets/141872402/06a9c890-e90a-4ce2-bca9-0e26f5492791">
<img width="714" height="100" alt="Screen Shot 2024-02-26 at 10 27 40 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/141872402/80ff940d-89f9-41c4-95cf-3708c095fec6">

2024-03-17 03:15 UTC, ramyaram2092 requested changes
Hello @robertoooc  Good job on the functionality! .I did get an email for account creation. However I didnt recieve any for password update 
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/89441435/3a6c35de-d41a-47a8-baee-c7c86ba61986)

2024-03-19 06:02 UTC, robertoooc commented
@ramyaram2092, It looks like the problem was at some point the allusers cache was not defined or didn't return anything so the previous code that would try to add a user or remove one from that array would cause that error, added an if statement as error handling to prevent that case now.

Also before sending email checking the dbName if its the hgn dev then it only alerts for Owner creation and password reset, but if the dbName is anything else such as the main site's db then it would also alert of Admin and Owner actions.

2024-04-06 17:41 UTC, ramyaram2092 reviewed
Check the following review

2024-04-06 17:44 UTC, ramyaram2092 approved these changes
Works @robertoooc . Good job !. I got email for both scenarios

2024-04-06 23:18 UTC, one-community commented
Thank you all, merging!

2024-04-06 23:18 UTC, merged