Ramya teams limit see all
OneCommunityGlobal/HGNRest pull request #576
Opened 2023-10-18 06:44 UTC by ramyaram2092

# Description
- A “Limit See-All” option for teams 

-  Other Links ->Teams

- When this option is turned on for a team member,  the team member  shouldn't  be able to see  other members of the team in their dashboard 

- The member however should be able to see team members of other teams  they are part of 

## Related PRS (if any):
This backend PR is related to the [1425](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1425) frontend PR.
To test this backend PR you need to checkout the [1425](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1425) frontend PR.

## Main changes explained:

- Added  a "visible" attribute to Member Object in Teams document and set it to true by default.
- Added a new route to updating the team member visibility. 
- Add  a  function  called  "updateTeamVisibility "in teams Controller   to process the newly selected visiblity of the team member

## How to test:
1. check into current branch
2. run node src/utilities/addMembersToTeams.js so that "visible" attribute gets added to all existing team members
3. run `npm install ` followed by `npm run build start`  and  `npm start ` to run this PR locally

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-10-19 06:31 UTC, DavidC0126 approved these changes
LGTM, commented on FE PR.

2023-10-19 16:19 UTC, shubhankarval requested changes
Left a comment on FE [1425](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1425#pullrequestreview-1688160585).

2023-10-21 00:34 UTC, StrawberryCalpico requested changes
Hi! I reviewed your PR, left comment on the [FR#1425](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1425#pullrequestreview-1691026115)

2023-10-21 02:26 UTC, ChirayuRai reviewed
Hello! I added my comments in FE#1425!

2023-10-21 02:48 UTC, ramyaram2092 commented
I am investigating the bug/ feedbacks received so far. Marking the PR to "do not review " for now on the same account

2023-12-15 06:43 UTC, Alforoan approved these changes
I left a comment on the FE pr.

2023-12-24 01:19 UTC, ljrirene reviewed
Please see my review of #1425 here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1425#pullrequestreview-1795511374

Thank you!

2024-01-16 23:22 UTC, yuhuimin1996 commented
Please see my comments at the FE pr #1425

2024-01-20 08:17 UTC, Renanluizssx reviewed
hi @ramyaram2092, please see my review at the PR #1425: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1425

2024-01-20 08:17 UTC, Renanluizssx commented on src/controllers/teamController.js
> +// const teamDetails=require('../models/team');
you could delete this comment

2024-01-20 08:29 UTC, ramyaram2092 commented
Hi all thanks for your detailed feedback . I am looking into your feedback and addressing them, marking the PR do not review on the same note

2024-02-01 23:58 UTC, ramyaram2092 commented
Addressed the feedbacks at [731](https://github.com/OneCommunityGlobal/HGNRest/pull/731)

2024-02-01 23:58 UTC, closed without merging