Fix hasPermission() arguments and add catches.
OneCommunityGlobal/HGNRest pull request #585
Opened 2023-10-25 04:19 UTC by nathanah

# Description

## Main changes explained:
- Change hasPermission() arguments from requestor.role to requestor in rolePresetsController.js
- Add catch statements to hasPermission() calls.

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. log in as owner user
4. go to the permissions management page
5. verify you can create and load presets

## Screenshots or videos of changes:
Before:
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/23086054/14cf7060-9cc2-4b4c-aa34-e8d254baa47e)
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/23086054/497d0496-9085-491a-8f30-691d9e761aba)

After:
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/23086054/dc4a589b-3aee-4142-94f5-7a4bc0e7c3a7)
And no error

2023-10-25 05:15 UTC, ChirayuRai commented
Hey Nathan. I cannot seem to find anything indicating role presets anywhere. If I click on add new role, it just shows a list of all possible roles. Is there a frontend PR attached to this as well? For reference, I checked out the branch, did npm install, npm run build, and then npm start. After that I loaded up the development branch for the frontend and am using that to test.

![Screenshot 2023-10-24 at 10 12 27 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/15188751/3e8a9919-9d7f-445a-9a15-e90e08bdda1e)

2023-10-25 05:45 UTC, AaronPersaud requested changes, later dismissed
Hi @nathanah, the permissions error in the backend has been fixed, but I am unable to fully use the "Create New Preset" and "Load Presets" buttons.

https://github.com/OneCommunityGlobal/HGNRest/assets/10265513/3e05761d-6484-48db-a353-7ed39b8b2913

When I click "Create New Preset" the POST request returns a 403 forbidden error.

When I click "Load Presets", I am able to preview all the available presets, as well as rename and delete them. However, when I click "Apply", the PATCH request is also return a 403 forbidden error.

@ChirayuRai, you have to click on a specific role to see the presets for that role

2023-10-25 15:34 UTC, KurtisIvey approved these changes
Functions as intended. Able to create, delete, rename, and load presets without issue. I did test this with pr1420 since the current dev didn't have the preset implementation in it. Not sure if pr1420 got rolled back

https://github.com/OneCommunityGlobal/HGNRest/assets/19482363/2c0e0fb2-f2a5-42d0-9f95-61a0c7401c97

2023-10-27 21:47 UTC, nathanah commented
> Hey Nathan. I cannot seem to find anything indicating role presets anywhere. If I click on add new role, it just shows a list of all possible roles. Is there a frontend PR attached to this as well? For reference, I checked out the branch, did npm install, npm run build, and then npm start. After that I loaded up the development branch for the frontend and am using that to test.
> 
> ![Screenshot 2023-10-24 at 10 12 27 PM](https://user-images.githubusercontent.com/15188751/277880579-3e8a9919-9d7f-445a-9a15-e90e08bdda1e.png)

You have to choose a role. I updated the instructions.

2023-10-27 21:49 UTC, nathanah commented
> Hi @nathanah, the permissions error in the backend has been fixed, but I am unable to fully use the "Create New Preset" and "Load Presets" buttons.
> 
>  HGN.APP.-.Google.Chrome.2023-10-25.01-38-21.mp4 
> When I click "Create New Preset" the POST request returns a 403 forbidden error.
> 
> When I click "Load Presets", I am able to preview all the available presets, as well as rename and delete them. However, when I click "Apply", the PATCH request is also return a 403 forbidden error.
> 
> @ChirayuRai, you have to click on a specific role to see the presets for that role

Those 403s mean you don't have permission to edit role permissions.

2023-10-28 03:21 UTC, malikjahanzaib approved these changes
Hi @nathanah, I have tested this PR locally and I was able to create and load preset(s) for a test role. Check my recording below. Nice job!

P.S. Some UI changes can be made such as when a new preset is created there could be some acknowledgement that a new preset has been added. I understand it is beyond the scope of this PR as this is BE focused. Just a suggestion :)

Test rec:

https://github.com/OneCommunityGlobal/HGNRest/assets/46221334/49f7d781-c0a1-4893-96ea-caf416e24b41

2023-10-28 07:12 UTC, AaronPersaud commented
> 
> Those 403s mean you don't have permission to edit role permissions.

Thank you for the clarification Nathan, that makes sense. Do you think it would make sense to have an error popup if the user doesn't have the permissions, or is that a fringe case we don't need to worry about?

2023-11-01 01:49 UTC, nathanah commented
> > Those 403s mean you don't have permission to edit role permissions.
> 
> Thank you for the clarification Nathan, that makes sense. Do you think it would make sense to have an error popup if the user doesn't have the permissions, or is that a fringe case we don't need to worry about?

I think a popup is warranted, but outside the scope of this PR. Had planned to come back to it after I finish another project I'm working on.

2023-11-26 01:04 UTC, GKD890 approved these changes
It works as intend, will leave the result to the related FE PR

2023-12-02 18:57 UTC, DragonSlayer2401 commented
I tested on an Owner account. Everything appears to be working correctly. I was able to create and load presets.

https://github.com/OneCommunityGlobal/HGNRest/assets/102876103/419f771b-f51b-4a9c-899d-f49b9f5c5793

2023-12-03 00:08 UTC, ptrpengdev commented
Tested with FE PR [1548](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1548#issuecomment-1837286384). The code works as expected.

2023-12-04 04:33 UTC, one-community commented
> I think a popup is warranted, but outside the scope of this PR. I had planned to come back to it after I finish another project I'm working on.

Yes, please add this. If it's easy, just include it in the PR too.

2023-12-04 07:55 UTC, nathanah commented
> > I think a popup is warranted, but outside the scope of this PR. I had planned to come back to it after I finish another project I'm working on.
> 
> Yes, please add this. If it's easy, just include it in the PR too.

That would be a front-end change and this is a back-end PR, so it cannot be added to this PR.

2023-12-04 21:25 UTC, navneeeth approved these changes
Hello, @nathanah! Tested the changes while testing a FE PR of yours that involves this BE and the create and load presets work as expected. LGTM!


https://github.com/OneCommunityGlobal/HGNRest/assets/44264834/a5479b1d-9f22-4a94-87b2-615e5c3714a2

2023-12-07 20:06 UTC, one-community commented
Thank you all, merging!

2023-12-07 20:06 UTC, merged