added unassignUserInProject, assignUserInProject permission to creteI…
OneCommunityGlobal/HGNRest pull request #610
Opened 2023-11-14 04:18 UTC by luisarevalo21

# Description
<img width="762" alt="Screenshot 2023-11-13 at 8 14 31 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/22454953/5d73285b-d151-430e-b94d-f3a6550dbbd7">
This PR resolves part C. 

## Main changes explained:
Added both   'unassignUserInProject' and  'assignUserInProject' to admins permission on initial setup. 

## How to test:
1. check into current branch
2. do `npm run build`, `npm run install` `npm run start` to run this PR locally
3. Checkout the front end development branch 
4. log as admin user
5. go to dashboard→ other links → projects
6. select a project and select the projects team member icons
7. make sure a red delete button appears next to all users
8. remove a user and refresh to make sure the user is removed.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/22454953/754772fe-3787-4fcc-ae54-64e2b4a68bdf

2023-11-18 22:50 UTC, palakgosalia commented
Hey, I reviewed and tested your PR. I was able to delete the member from the project. Thank you

https://github.com/OneCommunityGlobal/HGNRest/assets/104417272/bf165a80-09c8-4e54-9608-645f1a799abd

2023-12-09 07:46 UTC, ljrirene approved these changes
Good job Luis! This feature works as expected on my side.

https://github.com/OneCommunityGlobal/HGNRest/assets/34266880/0f8e54d0-72f2-49ce-a136-65f1f3a83eec

2023-12-23 07:01 UTC, Alforoan requested changes
I am for some reason unable to click on anything.



https://github.com/OneCommunityGlobal/HGNRest/assets/118868270/ea22fdcc-a016-4397-864d-0fcce660a5c4

2024-02-07 01:01 UTC, Pandani07 requested changes
Hi, I am not able to click on anything. I also got this in the backend log

![Screenshot 2024-02-06 at 8 01 03 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/44672833/240e23ac-af92-4da8-b991-63eeb11a9573)

2024-06-14 17:58 UTC, akshit0211 requested changes
I am not able to click on anything on the page. Please check this.

<img src="https://github.com/OneCommunityGlobal/HGNRest/assets/112666943/17d5b6a9-1d3f-4643-8c32-a7d04931a3b5" alt="error">

2024-09-05 22:33 UTC, AJAYINAVOLU requested changes
The web page is freezing completely. 

<img width="946" alt="image" src="https://github.com/user-attachments/assets/4daec328-bb88-448b-aebb-b69b9f3dfae3">

2025-04-28 04:11 UTC, closed without merging