Xiaow TimeEntryForm refactor (backend)
OneCommunityGlobal/HGNRest pull request #668
Opened 2023-12-23 11:17 UTC by wang9hu

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2023-12-24 06:03 UTC, Alforoan reviewed
I could not do npm run build because there is a syntax error. It's missing a try block.

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/118868270/85e1f641-940a-4ea8-8a29-f159b916f906)

2023-12-27 06:37 UTC, wang9hu commented
> I could not do npm run build because there is a syntax error. It's missing a try block.
> 
Hi @Alforoan, thank you for your review, I checked the code and the try block is intact, please be sure to pull the latest branch and test it again. Let me know if there is anything other issue.

2023-12-29 01:56 UTC, Alforoan reviewed
I got an error. Also check the comment left on fe pr #1744

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/118868270/6fe81331-515c-4e81-91ef-406e53586c33)

2023-12-29 18:57 UTC, ChengyanOo commented on src/controllers/timeEntryController.js
Hi @wang9hu,

I noticed that the frontend is returning a 400 error code. It might be helpful to start investigating this issue on the server side. A good starting point could be around line 200.

2023-12-29 19:08 UTC, ChengyanOo requested changes, later dismissed
Hi @wang9hu,

Great work on the PR! I gained new insights by the conciseness of your syntax and the neat refactoring you've done. However, I've encountered an issue where the frontend linked with this PR is generating a 400 server error when attempting to change the timeEntry, please take a look at the comment I made on the timeEntryController.js

2023-12-31 05:40 UTC, wang9hu commented on src/controllers/timeEntryController.js
Thank you for your feedback! Changes has been made in the latest commit, please pull it and check if the bug is still there.

2023-12-31 05:43 UTC, wang9hu commented
> I got an error. Also check the comment left on fe pr #1744
Thank you for your comment! 

As for the issue in the screenshot, it is from Mongodb Atlas, which is not in the scope of this PR. 

I have made some changes to address the issue you mentioned in your comment, please pull the latest commit and check if the bug is still there.

2024-01-03 04:33 UTC, one-community approved these changes

2024-01-03 04:33 UTC, merged