Jay - Add Controller Logic for Edit Link Permission
OneCommunityGlobal/HGNRest pull request #688
Opened 2024-01-06 20:21 UTC by Alforoan

# Description
A user with a 'manageAdminLinks' permission is now able to access and edit other users' links.

## Related PRS (if any):
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Add permission logic for users to be able to access and edit other users' links.
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm run start` to run this PR locally
3. Clear site data/cache

2024-01-14 03:39 UTC, ramyaram2092 reviewed
The functionality works as expected .However, seeing some exception in the backend console in addition to console statements 
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/6681910f-d82c-4308-911d-a85a66b8470d)

![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/b28fb3a0-52aa-448b-9073-e43f8bef668b)

2024-01-23 04:17 UTC, pshereen requested changes
Tested the PR.
Controller Logic for Edit Link Permission is working as per the requirement. 

But some error messages are shown at the backend console.

<img width="948" alt="Screenshot 2024-01-22 201333" src="https://github.com/OneCommunityGlobal/HGNRest/assets/7041610/de380d8a-09cb-4ca4-b235-c0890112117f">

2024-01-24 02:48 UTC, Renanluizssx reviewed
see my review @Alforoan: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1787

2024-01-27 17:17 UTC, Sophie-lei reviewed
Tested and left commrnt in PR1787. Please view for details.

2024-01-27 23:03 UTC, KevHnh approved these changes
Tested with Frontend PR and everything works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1787

2024-01-28 03:09 UTC, galgalinidhi commented
The functionality works as expected. However, the backend console displays the following error-

<img width="1437" alt="Screenshot 2024-01-27 at 7 08 42 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/44816413/aa34d668-64fc-4878-92e9-b5d8307eb9bf">

2024-01-31 19:09 UTC, Pandani07 approved these changes
The frontend PR works as intended but I get these messages in the backend log

![Screenshot 2024-01-31 at 2 06 58 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/44672833/b47943e2-101e-473a-a3ab-342a04949b75)
![Screenshot 2024-01-31 at 2 07 09 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/44672833/cf535aaa-da4b-418c-bab1-d35ed2e546d9)
![Screenshot 2024-01-31 at 2 07 06 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/44672833/b1768865-2205-43c9-9303-42eb9567d953)

2024-02-03 17:09 UTC, Pandani07 approved these changes

2024-02-04 05:35 UTC, SaiDeepak-NEU approved these changes
Tested the changes for the edit link permission and everything worked as expected. I was able to see the edit link and was able to add google doc links.

Please refer to the frontend PR1787 for screenshots and additional comments.

2024-02-07 03:24 UTC, X1aoZhang99 requested changes
Hi Jay,

Please see my review in FE [#1787](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1787#pullrequestreview-1866835268)

2024-02-09 03:21 UTC, mohabbasd approved these changes
I tested this PR and it works flawlessly, good job. The screenshots are in the frontend PR review.

2024-02-14 21:53 UTC, XiaohanMeng reviewed
Hi, I have tested this PR. The detailed comment is on the FE project. Here are some errors appeared in the backend terminal while testing.
![PR1787_error](https://github.com/OneCommunityGlobal/HGNRest/assets/113215317/b6106c79-7bbf-4777-aa64-a7b0513c9095)

2024-03-02 21:47 UTC, nathanah requested changes

2024-03-02 21:47 UTC, nathanah commented on src/controllers/userProfileController.js
> +
```suggestion
        await hasPermission(req.body.requestor, "manageAdminLinks")
      ) {
        record.adminLinks = req.body.adminLinks;

       if (await hasPermission(req.body.requestor, "putUserProfileImportantInfo")
```
something more like this. The brackets from the if statement are causing syntax errors.

2024-05-08 03:18 UTC, closed without merging