add controller logic
OneCommunityGlobal/HGNRest pull request #712
Opened 2024-01-20 20:19 UTC by Alforoan

# Description
A user with a 'editTimeEntryDescription' permission is now able to see the edit button on another user's dashboard and edit it properly.

## Related PRS (if any):
To test this backend PR you need to checkout the [#1859](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1859) frontend PR.
…

## Main changes explained:
- Add controller logic so that the user with the permission has authorization to save the changes.
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm run start` to run this PR locally
3. Clear site data/cache

2024-01-23 15:58 UTC, X1aoZhang99 approved these changes
Hi Jay,

I've tested your PR, and all functionalities worked as intended. 

https://github.com/OneCommunityGlobal/HGNRest/assets/113070229/363fac5e-cde9-48c7-a044-35fe2bca6724

2024-01-27 01:23 UTC, nathanah requested changes
Need to separate  `canEditTimeEntryDescription` from `canEdit`.

2024-01-28 01:00 UTC, abdel-lall approved these changes
LGTM.

2024-01-31 01:53 UTC, Renanluizssx reviewed
see my review @Alforoan: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1859

2024-02-03 17:58 UTC, Pandani07 approved these changes
Tested this PR along with the related frontend PR and everything works as intended. Please check my review on the  frontend PR for the video.

2024-02-10 00:35 UTC, nathanah requested changes
Need to make sure `editTimeEntryDescription` can only edit descriptions and nothing else. Also, add new permissions to owners/admins or relevant roles in `createInitailPermissions.js`.

2024-02-16 06:24 UTC, mohabbasd reviewed
Hello, left a review on the frontend PR.

2024-02-21 03:02 UTC, XiaohanMeng approved these changes
Hi, I left my comment on FE project: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1859#pullrequestreview-1891974890

2024-02-21 22:10 UTC, Coops023 approved these changes
hi Jay, 

i have left my comments on the frontend PR.

2024-02-23 22:04 UTC, Weiyao-Li commented
Tested with the frontend, please see frontend review

2024-03-08 03:54 UTC, SRamen1999 approved these changes
I left my comment on FE project: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1859#pullrequestreview-1891974890

2024-03-25 21:12 UTC, hetvi11110 requested changes
I encountered a console error. Please check it on the frontend PR for reference.

2024-03-29 18:14 UTC, iven-yao requested changes
just tested this pr with the front end, please check the frontend [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1859#pullrequestreview-1969250477)

2024-04-01 20:09 UTC, kylepham approved these changes
Changes here look good to me. I left a [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1859#pullrequestreview-1972031155) in the frontend PR.

2024-05-02 22:24 UTC, closed without merging