Jay - Toggle Tangible Permission
OneCommunityGlobal/HGNRest pull request #713
Opened 2024-01-22 02:27 UTC by Alforoan

# Description
A user with a 'editTimeEntryToggleTangible' permission is now able to check and uncheck the box.

## Related PRS (if any):
To test this backend PR you need to checkout the [#1859](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1859) frontend PR.
…

## Main changes explained:
- Add controller logic so that the user with the permission has authorization to save the changes.
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm run start` to run this PR locally
3. Clear site data/cache

2024-01-24 23:12 UTC, Renanluizssx reviewed
Hi @Alforoan, look my review at:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862#pullrequestreview-1842568615

2024-02-03 19:50 UTC, galgalinidhi commented
Hi @Alforoan, I left a comment here- https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862.

2024-02-05 22:14 UTC, Pandani07 requested changes
My admin account was given the permission to change while I just gave the permission to my volunteer account. It works as expected for my volunteer account.

2024-02-09 23:22 UTC, nathanah requested changes
Add new permissions to owners/admins or relevant roles in `createInitailPermissions.js`

2024-02-20 22:16 UTC, XiaohanMeng requested changes
Hi, I've left my comment on the frontend project. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862
And here is the error on my backend terminal.
![PR1862+713-error](https://github.com/OneCommunityGlobal/HGNRest/assets/113215317/8843bc48-1c83-4f61-84ef-31d160af31e0)

2024-02-21 05:11 UTC, Jingyii800 requested changes
Hi @Alforoan, I have tested with the backend PR, and there is one issue with the feature. Please check it in this comment. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862#pullrequestreview-1892119438

2024-03-03 05:34 UTC, brandta-1 requested changes
# Review
please see [front-end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862#pullrequestreview-1912859576).

2024-03-08 20:01 UTC, Weiyao-Li commented
please check my frontend pr:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862#pullrequestreview-1925749440

2024-03-19 23:28 UTC, rajnada commented
I have mentioned my feedback on [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862#issuecomment-2008333763](url)

2024-03-20 05:03 UTC, iven-yao commented
I reviewed this pr with [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862#pullrequestreview-1947948596)

2024-03-21 01:26 UTC, hetvi11110 reviewed
I tested both frontend and backend PR. Both are working as mentioned. For reference, please check the comment on frontend PR.

2024-03-31 21:24 UTC, kylepham approved these changes
Changes look good. Feature worked as expected. I left a [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1862#pullrequestreview-1970409150) in frontend PR.

2024-04-03 21:08 UTC, closed without merging