Jay - Change Date on Intangible Time Entry
OneCommunityGlobal/HGNRest pull request #726
Opened 2024-01-28 20:46 UTC by Alforoan

# Description
Added date verification logic such that if the date is in the future, it gives an error.

## Related PRS (if any):
To test this backend PR you need to checkout the [#1865](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865) frontend PR.
…

## Main changes explained:
- Add controller logic so that the user cannot change the date to an invalid date (date in the future).
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm run start` to run this PR locally
3. Clear site data/cache

2024-02-03 17:11 UTC, Pandani07 approved these changes
Tested this PR and left comments on the frontend PR. Works as intended

2024-02-05 15:52 UTC, Renanluizssx reviewed
see my review @Alforoan please:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865

2024-02-17 19:56 UTC, swathyjayaseelan approved these changes

2024-02-19 20:21 UTC, Coops023 commented
I have left my comments in the frontend PR.

2024-02-20 22:14 UTC, XiaohanMeng reviewed
Hi, I've left my comment in the frontend project. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865

2024-02-22 05:11 UTC, Jingyii800 approved these changes
Congratulations! This backend PR works well. Please check more details on this comment. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865#pullrequestreview-1894916238

2024-02-22 05:15 UTC, skaush21 approved these changes
left a comment on PR 1865: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865]

2024-03-01 17:18 UTC, MALAV1308 approved these changes
Hello , I have tested your PR and backend is working as per requirement. Good Job!

2024-03-03 02:35 UTC, brandta-1 approved these changes
# Review

See [front-end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865#pullrequestreview-1912817153).

2024-03-08 03:50 UTC, SRamen1999 reviewed
left a comment on PR 1865: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865%5D

2024-03-08 19:33 UTC, Weiyao-Li commented
Left comment at Frontend

2024-03-08 23:08 UTC, nathanah requested changes
The frontend PR is for `editTimelogDate`, but here, you're using `editTimeEntryToggleTangible`.

2024-03-08 23:08 UTC, nathanah commented on src/controllers/timeEntryController.js
> +      || !req.body.timeSpent || !isValidDate;
Should verify permission of valid, past date here.

2024-03-08 23:08 UTC, nathanah commented on src/controllers/timeEntryController.js
> +    if (!(canEdit || canEditTimeEntryToggleTangible) ) {
Needs to be separated to only affect the relevant data.

2024-03-08 23:08 UTC, nathanah commented on src/controllers/timeEntryController.js
> +    const currentDate = getCurrentDate();
```suggestion
    const currentDate = moment().tz('America/Los_Angeles').format('YYYY-MM-DD');
```
Use `moment()` as used elsewhere (e.g. line 190)

2024-03-08 23:08 UTC, nathanah commented on src/controllers/timeEntryController.js
> +  }
```suggestion
```
Add this in a utils file if it's needed, but you can just use moment() as used elsewhere in this file.

2024-03-08 23:08 UTC, nathanah commented on src/controllers/userProfileController.js
> +        || await hasPermission(req.body.requestor, 'editTimeEntryToggleTangible') || req.body.requestor.requestorId === userid
```suggestion
        || req.body.requestor.requestorId === userid
```
Is this needed?

2024-03-09 21:07 UTC, hetvi11110 reviewed
I have tested this PR with PR# 1865 on the front end. Please take a look at my comment there.

2024-03-20 04:13 UTC, iven-yao reviewed
I reviewed this pr with corresponding [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865#pullrequestreview-1947914171)

2024-03-24 23:43 UTC, Tiantian-C approved these changes

2024-03-24 23:46 UTC, Tiantian-C reviewed
Hi, I have tested the PR and left the comment at the frontend. It works, thank you!

2024-03-31 20:14 UTC, kylepham requested changes
PR worked as intended, but there is a bug that caused by entering a future date submission followed by a past/current date submission. It created 2 entries in the database: one for the future date, and one for the past/current date. Please see my frontend PR's [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865#pullrequestreview-1970399835) for reference.

2024-04-03 21:08 UTC, closed without merging

2024-04-05 17:37 UTC, MQChen211 commented
I tested this PR with the frontend [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1865#issuecomment-2040315272](url)