Jay - Add Time Entry (Others)
OneCommunityGlobal/HGNRest pull request #727
Opened 2024-01-29 07:16 UTC by Alforoan

# Description
A user with the 'postTimeEntry' is able to submit a time entry for others successfully.

## Related PRS (if any):
To test this backend PR you need to checkout the [#1871](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871) frontend PR.
…

## Main changes explained:
- Add controller logic so that the user with the permission is able to submit the time entry successfully.
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm run start` to run this PR locally
3. Clear site data/cache

2024-02-02 07:51 UTC, yvonnep165 approved these changes
Hi @Alforoan ,

I have tested this PR with PR# 1871 at the frontend. Please refer to PR 1871 for more details.

2024-02-05 15:57 UTC, Renanluizssx reviewed
see my review @Alforoan please in front-end: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871

2024-02-05 23:09 UTC, Pandani07 approved these changes
Tested this PR and the frontend PR as well, everything works get. Please refer the video in my review of the frontend PR.

2024-02-19 14:33 UTC, Coops023 approved these changes
Hi Jay, 
I have left my comments regarding this review in the front-end PR

2024-02-21 03:07 UTC, XiaohanMeng approved these changes
Hi, I left my comment on FE project: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871

2024-02-21 03:13 UTC, Jingyii800 approved these changes
Hi, I have tested this feature with frontend branch. It works well! Please check more details in this comment. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871#pullrequestreview-1891983416

2024-03-01 16:24 UTC, MALAV1308 approved these changes
Hello , I have tested your PR and everything is working Good from backend. Good Job!

2024-03-03 00:59 UTC, brandta-1 approved these changes
# Review
please see [front-end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871#pullrequestreview-1912795181).

2024-03-04 16:06 UTC, rajnada commented
Hi. I have tested the functionality it's working fine ! Here is my frontend review 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871#issuecomment-1976920787

Good Job :)

2024-03-07 19:06 UTC, Weiyao-Li approved these changes
please check my frontend comment:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871

2024-03-08 02:19 UTC, hetvi11110 approved these changes
I have tested this PR with PR# 1871 on the front end. Please take a look at my comment there.

2024-03-08 03:56 UTC, SRamen1999 approved these changes
I left my comment on FE project: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871

2024-03-08 03:57 UTC, nathanah requested changes

2024-03-08 03:57 UTC, nathanah commented on src/controllers/userProfileController.js
> +      )
`postTimeEntry` should not allow editing entire user profiles.  Separate this. It would be best if time entries had their own API.

2024-03-20 01:20 UTC, iven-yao approved these changes
I reviewed this pr with the [frontend pr](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871#pullrequestreview-1947798074), everything works correctly

2024-04-03 21:07 UTC, closed without merging

2024-04-05 16:46 UTC, MQChen211 commented
I reviewed this PR with the frontend, here's my comment: [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1871#issuecomment-2040243771](url)