Chengyan phase2 update reusable type backend
OneCommunityGlobal/HGNRest pull request #773
Opened 2024-02-28 19:54 UTC by ChengyanOo

# Description
This update introduces a backend endpoint addition for the new reusable type. It ensures seamless integration with the frontend's item type management functionalities.

## Related PRs (if any):
While the frontend integration for this feature is still under development, you can utilize the in-progress frontend work for testing purposes. Check out [Chengyan phase2 reusables list UI #1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956/) for the frontend changes. This will allow you to test the backend functionality in a more interactive manner, keeping in mind that the frontend is not yet finalized and subject to change.

## Main changes explained:
- Implemented the two new REST endpoints: `http://localhost:4500/api/bm/invtypes/reusables`, and `http://localhost:4500/api/bm/invtypes/reusable`

## How to test:
1. Switch to the current branch.
2. Execute `npm install`, `npm run build`, and `npm run start` to run this PR locally.
3. Test in conjunction with the frontend PR [Chengyan phase2 reusables list UI #1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956/)
4. Watch the detailed walkthrough video for recommended way to test.
5. Review the code for potential code smells.

## Screenshots or videos of changes:
![Screenshot of Feature](https://github.com/OneCommunityGlobal/HGNRest/assets/69735000/56766a6e-1f44-4cf2-bbec-5f17986c4d43)
Detailed walkthrough: [https://www.loom.com/share/cedd7377335845738e0eac02169fb696?sid=286fb8d4-24a2-4d21-a1dd-8584d4a3614b](https://www.loom.com/share/cedd7377335845738e0eac02169fb696?sid=286fb8d4-24a2-4d21-a1dd-8584d4a3614b)

2024-03-28 23:59 UTC, ImzIssa requested changes
Hey I am getting this error when I try to build.
  
![PR 773](https://github.com/OneCommunityGlobal/HGNRest/assets/87269725/c27c6ef9-8b7d-4fa7-b4eb-c87569fa2af6)

2024-03-28 23:59 UTC, ImzIssa commented on src/controllers/bmdashboard/bmReusableController.js
> -    const purchaseReusable = async (req, res) => {
Hey, I am not able to build the app. looks like you deleted purchaseReusable but its still being return from the controller which is causing an error.

![PR 773](https://github.com/OneCommunityGlobal/HGNRest/assets/87269725/61d8c2c3-7d57-4925-84b1-be2afa43e057)

2024-05-23 05:50 UTC, Sandhya1236 requested changes
The application crashes with a ReferenceError: purchaseReusable is not defined in bmReusableController.js. This occurs because the purchaseReusable variable or function is referenced without being declared or imported. Please fix this.

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/79351059/15204cdf-3f42-4faa-bca6-214068c462f9)

2024-05-24 08:46 UTC, Infinite-Turkey requested changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/122322808/6eed1d7f-4623-4a89-a555-341ff60c7094)
The purchaseReusable variable or function is being used in the bmReusableController.js file, but it hasn't been declared or imported.

2024-05-31 21:58 UTC, Wenboooooo requested changes
Hello, it seems like the backend pulled from the branch cannot be run.
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/114895283/909b33d5-4d12-44b8-93f0-01cf4ca254f2)

2024-06-05 01:32 UTC, Kavil-Jain-514 requested changes
Hey there, I am unable to start the back-end. Error:
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/112303944/eddd3845-94da-4d13-b9e5-a4c5e79b83b3)

2024-06-05 04:04 UTC, closed without merging