Alex Brandt Integrate ChatGPT
OneCommunityGlobal/HGNRest pull request #809
Opened 2024-03-22 20:41 UTC by brandta-1

# Description
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/3a257f51-2c23-4767-a5a4-dab418f1fe2f)

## Related PRS (if any):
This PR was built off of [646](https://github.com/OneCommunityGlobal/HGNRest/pull/646)
To test this backend PR you need to checkout the #XXX frontend PR.

## Main changes explained:

### ```src/controllers/chatGPTController.js```
This controller takes in a front-end request containing the user's id and name. This data is used to retrieve their weekly summaries, then the controller retrieves the latest AI prompt, and sends this data to ChatGPT, and sends the AI response to the front end.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Create a ChatGPT API key (or use an existing one) and set it as the ```OPENAI_API_KEY``` environment variable in your ```.env``` file
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/b38077a8-6d4c-4a37-8833-141116ab0a13)

## How to get a ChatGPT API key

1. Go to [OpenAI's API portal](https://auth0.openai.com/u/signup/identifier?state=hKFo2SBmV2YzamhMVkZ0NmtoTGFUdE14YWZMazNWNl85V1RQUKFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIF9vVWdUdlI0TFd1bWRDWTJfMlJNREMxR0lsZW5QWWZJo2NpZNkgRFJpdnNubTJNdTQyVDNLT3BxZHR3QjNOWXZpSFl6d0Q)
2. Create an account (or login to an existing one) and navigate to API keys on the left side of the page:
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/5971cd00-d3b7-48eb-911e-d60b41199070)
3. Create a new secret key:
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/ca892d5d-9ce6-45c9-a58f-0ea6d8c04093)
4. Name the key (optional) the click create secret key:
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/7ada2d59-6f1e-4003-a65c-753843b42c0c)
5. copy the key string and save it somewhere, then paste it into your ```.env``` file:
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/dc9939ea-78bd-4f75-a45e-27f47d08a30b)

## Screenshots or videos of changes:
See files changed

2024-03-22 20:59 UTC, Abi-Liu reviewed
I'm getting an error when trying to run `npm install` on the backend. Do you know what may be causing this error?


![Screenshot 2024-03-22 at 1 58 28 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/59585815/c23790be-a0dd-42fe-8015-8f081d2a7b59)

2024-03-23 02:15 UTC, DiegoSalas27 requested changes

2024-03-23 02:15 UTC, DiegoSalas27 commented on src/.DS_Store
Please delete this file and add it to the .gitignore file.

2024-03-23 02:53 UTC, brandta-1 commented on src/.DS_Store
[added](https://github.com/OneCommunityGlobal/HGNRest/pull/809/commits/8dea04f1c1f05eafd1ed6f3083e95d4b8efbc32f)

2024-03-23 02:55 UTC, brandta-1 commented
> I'm getting an error when trying to run `npm install` on the backend. Do you know what may be causing this error?
> 
> ![Screenshot 2024-03-22 at 1 58 28 PM](https://private-user-images.githubusercontent.com/59585815/316166579-c23790be-a0dd-42fe-8015-8f081d2a7b59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNjI3MDIsIm5iZiI6MTcxMTE2MjQwMiwicGF0aCI6Ii81OTU4NTgxNS8zMTYxNjY1NzktYzIzNzkwYmUtYTBkZC00MmZlLTgwMTUtOGYwODFkMmE3YjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDAyNTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYTVjYTk4ODZhOTczZWEyZmU4YTNmMDMwM2MwM2MyYjZkMjM4YjEyYjY1NTE5MjU1MGE4YTI4NjkzYjY0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jrBoyIRoXvjvREqdSLJ-yjVrbUfY1mMyik138eePLaA)

It looks like this was an error with json format in package-lock, the error should be fixed now. If it persists, then try deleting ```package-lock.json```, thank you.

2024-04-10 02:54 UTC, jennZhang93 reviewed
Please see the [frontend review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2083#pullrequestreview-1990697661)

2024-05-09 03:15 UTC, KaushikMreddy commented
Requested Changes and  reviewed this PR at the front end. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2083#pullrequestreview-2047073862

Running the application was simple and generating the API key was easy, Thank you for adding the steps to create one.

2024-07-20 22:05 UTC, closed without merging