Unit tests for the postactionItem method in actionItemController
OneCommunityGlobal/HGNRest pull request #816
Opened 2024-03-26 04:10 UTC by Abi-Liu

# Description
Added unit tests for the postactionItem method inside of the actionItemController.

## Related PRS (if any):
N/A
…

## Main changes explained:
- Added unit tests for the postactionItem method inside of the actionItemController.
…

## How to test:
1. check into the current branch
2. do `npm install` 
3. run `npm run test actionItemController` and confirm that both tests are passing.

## Screenshots or videos of changes:
![Screenshot 2024-03-25 at 9 10 07 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/59585815/c118b60e-1399-4231-afe0-6809a1c93748)

## Note:
N/A

2024-03-26 05:29 UTC, linkhanthtel approved these changes
I reviewed this PR and all tests have passed!

<img width="951" alt="#816" src="https://github.com/OneCommunityGlobal/HGNRest/assets/95618937/c1b3f68e-7a3b-444c-8248-7215f570d82e">

2024-03-26 08:31 UTC, 20chen-7 approved these changes
Excellent unit test.
<img width="708" alt="Screenshot 2024-03-26 at 4 31 14 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/59b01d8f-5dee-452f-868e-def956eb4a24">

2024-03-26 16:51 UTC, DiegoSalas27 requested changes
Hi Abi,

Great work. Please have a look at my comments and address them. I am adding a video where I explain how to test closures (something we will face a lot unit testing different files in this project). Please update also the actionItemController.js to update the way we import the notificationhelper closure.

As a brief explanation when we mock a closure we need to mock it before the source code executes the closure: e.g. `require('../helpers/notificationhelper')()`. If the source code executes the closure before its is mocked, our mocks will not work.

Remember, we always need to mock dependencies, because they may contain async functionalities that can make our tests unpredictable.

https://github.com/OneCommunityGlobal/HGNRest/assets/26840798/c1cb69d2-7eab-469a-a47d-7ad819367db4

Feel free to reach out to me if you have any questions.

2024-03-26 18:20 UTC, Abi-Liu commented
@DiegoSalas27 Thank you for your detailed review! That cleared up a lot of confusion regarding why the `spyOn` method was failing for the `notificationcreated` method. I have added the suggestions as well as the third test case.

Please review it again whenever you have time.

2024-03-26 19:32 UTC, DiegoSalas27 requested changes
Hi Abi,

Thank you for updating your code. It's almost perfect. Please just delete the unused imports for mongodb memory database since we are not using it right now. Once that's done, I will approve your PR and have it merged.

2024-03-26 19:32 UTC, DiegoSalas27 commented on src/controllers/actionItemController.spec.js
> +  mongoHelper: { dbConnect, dbDisconnect },
We can delete this import, since we are not using the memory database in any unit test.

2024-03-26 19:32 UTC, DiegoSalas27 commented on src/controllers/actionItemController.spec.js
> +    await dbConnect();
We can also delete line 26, and make the `beforeAll` non async.

2024-03-26 19:32 UTC, DiegoSalas27 commented on src/controllers/actionItemController.spec.js
> +  afterAll(async () => {
We can delete the entire `afterAll` function.

2024-03-26 19:54 UTC, Abi-Liu commented
@DiegoSalas27 Cleaned up the unused imports

2024-03-26 19:58 UTC, DiegoSalas27 approved these changes
Perfect. Thank you, Abi.

2024-03-27 20:19 UTC, Abi-Liu commented
Updated pull request in PR [817](https://github.com/OneCommunityGlobal/HGNRest/pull/817)

2024-03-27 20:19 UTC, closed without merging