Nahiyan_Fix White Screen Dashboard Error
OneCommunityGlobal/HGNRest pull request #820
Opened 2024-03-27 17:26 UTC by Nahiyan-16

# Description
For the backend, I just made sure that we check is our cached data is up to date before returning it.
Before we didn't do this step and it resulted in added Project not being displayed in User Profile page.

## Related PRS (if any):
To test this backend PR you need to checkout the #XXX frontend PR.

## Main changes explained:
- Created an if statement to check is cached data is up to date.

## How to test:
1. check into current branch
2. do `npm install` ,`npm run build`, and `npm start` to run this PR locally
3. Clear site data/cache
4. log as Owner user
5. go to dashboard→ Other Links → Projects → Create a new project
6. Add your own account
7.  Add a WBS
8.  Add a task and assign to self
9.  Go to your User Profile -> Projects
10. Observe that your added project is being displayed

2024-03-29 19:54 UTC, iven-yao approved these changes
I just reviewed this pull request with its corresponding frontend, please check [here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2091#pullrequestreview-1969530933) for more detail.

2024-03-30 03:50 UTC, mohabbasd approved these changes
Hello, I tested your PR and left a review on the frontend.

2024-03-30 05:35 UTC, abdel-lall requested changes

2024-03-30 05:35 UTC, abdel-lall commented on src/controllers/userProfileController.js
> +      if (cachedData.isUpToDate) {
Hi, The property 'isUpToDate' does not exist in the user cached data. Consequently, this 'if' statement will always evaluate to false, which means 'getUserById' is no longer utilizing caching.

2024-03-30 10:03 UTC, Sarthak32 approved these changes
I have left the review on frontend PR : https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2091#pullrequestreview-1969880460

2024-03-30 16:48 UTC, closed without merging