Christy team controller tests
OneCommunityGlobal/HGNRest pull request #826
Opened 2024-03-30 03:21 UTC by mianmiantea2019

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-04-03 17:00 UTC, DiegoSalas27 requested changes
Hi Christy,

Great work. I really appreciate your effort and commitment to unit testing. Please address the comments I submitted and let me know once that's cleared to review it again.

Reach out to me at any time if needed, and I will help you with anything you need.

2024-04-20 18:37 UTC, aaryaneil approved these changes
Tested this PR and all the test cases passed.
<img width="1534" alt="Screenshot 2024-04-20 at 1 36 59 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/39597927/d0cfbac3-4993-4a1e-9ac7-09e333b00f39">

2024-04-24 03:40 UTC, linkhanthtel approved these changes
All test cases passed as expected! Nice work! 

<img width="1182" alt="#826" src="https://github.com/OneCommunityGlobal/HGNRest/assets/95618937/1f37c3db-1337-47a4-a523-653caa213a05">

2024-04-26 22:18 UTC, Abi-Liu approved these changes
Great work with your tests! 

![Screenshot 2024-04-26 at 3 17 29 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/59585815/ab5bd3f2-2d80-4da2-a4ad-7d68834c47a9)

2024-05-03 15:43 UTC, Ramaruva approved these changes
All test cases are passed in my local env
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/64008831/78b653ca-2e8a-4cae-96b1-17d97b9076d7)

2024-05-05 13:24 UTC, DiegoSalas27 requested changes
Hey Christy. Great work. Your unit tests are perfect and they cover positive and negative cases. In addition, you went further to assert that functions like `sort` and `find` where called with correct parameters. There is only one comment to address in my review. Once this is solved, I will merge your PR.

2024-05-05 13:24 UTC, DiegoSalas27 commented on src/controllers/teamController.spec.js
> +jest.mock('../utilities/permissions', () => ({
This line of code is unnecessary. `mockHasPermission` already mocks the `hasPermission` function.

2024-05-16 06:09 UTC, KaushikMreddy commented
Hi, 
Your test cases have passed 
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/144624017/90f9e524-0404-415a-9857-7cf5284fe52a)

For getTeamById, try to add a test case where the id is not provided, I believe a 400 is to be returned for that.

2024-05-29 19:40 UTC, peter6866 approved these changes
All tests passed as expected.
<img width="666" alt="image" src="https://github.com/OneCommunityGlobal/HGNRest/assets/58479595/f12d7a9c-70b2-40e4-9264-c55c0a2f367e">

2024-06-01 22:24 UTC, Sandhya1236 approved these changes
I have successfully tested the unit tests for the getAllTeams, getTeamById, and postTeam functions in the teamController. The main changes included creating unit tests for these functions. After checking into the current branch, running npm install, and executing npm run test teamController, I verified that all tests passed successfully, confirming that the functions in the teamController operate correctly under various scenarios.

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/79351059/acdc55d4-bb92-4bdc-bd81-47a9e7b09381)

2024-06-14 17:43 UTC, akshit0211 commented
All test cases passed. Good work!

<img width="796" alt="All test cases passed" src="https://github.com/OneCommunityGlobal/HGNRest/assets/112666943/b2f587d7-9896-4eca-8981-594e92300a88">

2024-06-14 17:44 UTC, akshit0211 approved these changes

2024-06-16 02:44 UTC, deepthikannan approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/83337914/057874ff-33b2-4d10-a547-df6bdc107a9e)
Testes your unit tests for the functions in Team Controller and all the test cases passed.

2024-07-21 01:52 UTC, jinxyou approved these changes
All test cases have passed. Great work!
![PR 826](https://github.com/user-attachments/assets/92511791-c219-4403-80a8-9f70eca6e11e)

2024-07-30 22:47 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (160)](https://github.com/user-attachments/assets/14f3fdfc-8363-4271-b32b-0c3b239591c5)

2024-09-05 21:41 UTC, AJAYINAVOLU approved these changes
Tests are passing successfully.

<img width="710" alt="image" src="https://github.com/user-attachments/assets/06a6b0d0-03fd-4373-a35e-91272c8b95e1">

Thank You

2024-09-07 01:56 UTC, Saniya98 approved these changes
All test cases are passing as expected 
![image](https://github.com/user-attachments/assets/b8cc51fd-f0e1-427b-b4f6-7ab3f1907758)

2024-09-15 02:45 UTC, panchalvatneu approved these changes
all 4 tests passed, good work!
![image](https://github.com/user-attachments/assets/c98447ce-34b2-4dc9-a212-be3b32bebd22)

2024-09-18 05:28 UTC, ishangoel17 reviewed
All test cases are passing. Below is the screenshot for reference:
![Capture826](https://github.com/user-attachments/assets/42c7fac6-8404-43ac-bc22-74bff9674fea)

2024-09-27 19:12 UTC, geetamatkar commented
Hi @mianmiantea2019 ,
Tested this pR and all test cases have passed.

<img width="994" alt="PR826" src="https://github.com/user-attachments/assets/842da617-c74c-46cb-95bc-4e74020873b4">

2024-09-29 14:44 UTC, j-corp-25 approved these changes
Everything is working on my end.
Awesome Stuff!!
![Teams_Controller_Review](https://github.com/user-attachments/assets/63d2b3b7-d74d-45cf-b1ba-384b5aa09c32)

2024-11-01 23:24 UTC, SatyashanthiT commented
Reviewed and approved for the Team Controller's unit tests. Confirmed that all tests for the getAllTeams and getTeamById functions passed, verifying the expected functionality and coverage.
<img width="851" alt="image" src="https://github.com/user-attachments/assets/a14a8cb8-59ad-4ce6-8d1e-27f6bd87097f">

2025-01-05 18:41 UTC, one-community commented
Thank you all, merging!

2025-01-05 18:41 UTC, merged