Ivy blue email be
OneCommunityGlobal/HGNRest pull request #829
Opened 2024-03-31 07:17 UTC by 20chen-7

# Description
<img width="652" alt="Screenshot 2024-03-31 at 1 25 20 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/df608a7a-dcfd-460e-8420-47dc9e7d23a7">

## Main changes explained:
- Add administrative content and previous blue square historyInfringements
…

## How to test:
1. check into current branch
2. Gmail API
Before testing, you need to set up your own test email id to send the mail notification.
This is only for test purposes. Once tested you can revert these changes..

To send an email using the Gmail API with OAuth2 and nodemailer, follow the video below and set it up.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

Fill in the these variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = true
3. comment this to run every minute
<img width="697" alt="Screenshot 2024-03-31 at 1 49 23 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/f16a7de4-f12a-41ab-8536-1e3f69fb916e">
add test user email here:
<img width="668" alt="Screenshot 2024-03-31 at 1 29 58 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/ba80a03e-357e-4932-a92f-3715ffd1bfaa">
change the email address you wanna receive the blue square email
<img width="858" alt="Screenshot 2024-03-31 at 1 39 06 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/876b9856-b6d9-4182-857c-7c6e6eafe710">
for the frontend, based on @Abdel Lallouache's recommendation(https://highest-good.slack.com/files/U051KB9CPNW/F06S268Q2H0/expl.mp4), we should comment `if (!validateDateIsNotBeforeStartOfCurrentWeek(requestData)) return;`
<img width="697" alt="Screenshot 2024-03-31 at 1 44 18 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/4866ebf0-ceda-4689-8896-e53ad755e69f">

5. do `npm install` and `...` to run this PR locally
6. Clear site data/cache
7. log as admin user 
8. go to dashboard→ user management→ assign the test user day off(→…
<img width="522" alt="Screenshot 2024-03-31 at 1 49 35 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/102696148/8f623daf-fb4a-418a-baf5-820298725ab2">
The date is one week before the current week(explanation in the video provided by Abdel Lallouache) 
Thank @Abdel Lallouache's instructions and @DiegoSalas27 's help in modifying eslint file to get rid of some formatting issues brought by the previous version(which I do not want to change a lot).

2024-04-05 12:57 UTC, ImzIssa reviewed
Hey, I've been trying to review your PR but I'm not successful. I've managed to get and set up the API Keys but I can't get the email.

If you could provide more detailed steps on how to test this PR that would be great.

2024-04-09 20:47 UTC, ptrpengdev commented on .eslintrc
> +    "no-console": "off",
I noticed that you have made modifications to the ESLint rules. Perhaps we should make these changes in a separate PR and leave this PR to the add-admin-detail feature only.

2024-04-19 20:25 UTC, ptrpengdev commented on src/helpers/userHelper.js
> +    administrativeContent,
Reviewed on 4/19. The issue persists. getInfringementEmailBody is invoked in the timeEntryController with four parameters.

<img width="1507" alt="image" src="https://github.com/OneCommunityGlobal/HGNRest/assets/69882989/f2726302-7998-46bb-a803-ae57d7915717">

2024-04-21 00:51 UTC, metaphor987 reviewed
Hi Ivy,

I have set up the gmail api following the instructions, and can successfully receive the blue square emails every minute. These emails are sent from and to the test user and are BCC'd to the email I set up in the "emailSender" field, and I am unsure if this behavior is correct. The email content includes the expected administrative details.
<img width="1175" alt="Screenshot 2024-04-20 at 8 49 01 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/91745551/6a33ded9-3ea1-4fb7-9ccb-b0cce4bfb3e1">

During further testing, I encountered issues when attempting to open the video link for the "Add new time off request" feature(https://highest-good.slack.com/files/U051KB9CPNW/F06S268Q2H0/expl.mp4). 
<img width="706" alt="Screenshot 2024-04-20 at 8 47 11 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/91745551/0fa3dae9-9d8a-4dcd-b63e-3b851f994da7">

Could you please provide the link again or provide additional clarification on how to set the "Date of leave" and what behavior should be expected afterward? In my testing, I set the date of leave to be today and also a week before today, but I have not observed any changes and continue to receive emails every minute.

Thank you!

2024-04-21 02:28 UTC, 20chen-7 commented
> Hi Ivy,
> 
> I have set up the gmail api following the instructions, and can successfully receive the blue square emails every minute. These emails are sent from and to the test user and are BCC'd to the email I set up in the "emailSender" field, and I am unsure if this behavior is correct. The email content includes the expected administrative details. <img alt="Screenshot 2024-04-20 at 8 49 01 PM" width="1175" src="https://private-user-images.githubusercontent.com/91745551/324215410-6a33ded9-3ea1-4fb7-9ccb-b0cce4bfb3e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NjY1MDAsIm5iZiI6MTcxMzY2NjIwMCwicGF0aCI6Ii85MTc0NTU1MS8zMjQyMTU0MTAtNmEzM2RlZDktM2VhMS00ZmI3LTljY2ItYjBjY2U0YmZiM2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAyMjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NDdmNzc5MGNjOWRiY2MyNWIyMmI3MmI3NWRjNWI5ODIwMDE4ODNjMjJlYjE0YjA3YzA4ZjAwYWVlMzZjN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wj7J9aqEWVL8lZa4bQOdzogzbmDkAfgil_fWNItkNlU">
> 
> During further testing, I encountered issues when attempting to open the video link for the "Add new time off request" feature(https://highest-good.slack.com/files/U051KB9CPNW/F06S268Q2H0/expl.mp4). <img alt="Screenshot 2024-04-20 at 8 47 11 PM" width="706" src="https://private-user-images.githubusercontent.com/91745551/324214799-0fa3dae9-9d8a-4dcd-b63e-3b851f994da7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NjY1MDAsIm5iZiI6MTcxMzY2NjIwMCwicGF0aCI6Ii85MTc0NTU1MS8zMjQyMTQ3OTktMGZhM2RhZTktOWQ4YS00ZGNkLWI2M2UtM2I4NTFmOTk0ZGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAyMjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTVmOGJjOTljNGMxZTUzNGZmOWE2ZmM2NDRmZjM4MjA2YmQ3ZTFlYjhkYmFjNzRmZDNmZDczODIzOTBlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eqOAUsPqdk8IJWTZ3zkjZNQgmFgc8ol7IPU-KthgPdI">
> 
> Could you please provide the link again or provide additional clarification on how to set the "Date of leave" and what behavior should be expected afterward? In my testing, I set the date of leave to be today and also a week before today, but I have not observed any changes and continue to receive emails every minute.
> 
> Thank you!

Thank you for your review! and I found the latest frontend has already fixed this bug, So we do not need to modify the frontend anymore. As for the bcc issue, this is defined as the initial dev version, for this part, we only change the onecommunityglobal email to our email, just for test.

2024-04-21 04:47 UTC, abdel-lall requested changes
Hi @20chen-7, According to the description, users should not receive administrative details. However, during testing, both the admin email and user email received administrative details.
Owner Email:
![Screenshot 2024-04-20 234158](https://github.com/OneCommunityGlobal/HGNRest/assets/49083865/7e44e76d-231d-42cd-a874-e40036bb1fd6)

User Email:
![Screenshot 2024-04-20 234150](https://github.com/OneCommunityGlobal/HGNRest/assets/49083865/4a533e1f-665a-478a-b557-d926450d0947)

2024-04-21 05:38 UTC, 20chen-7 commented
> Hi @20chen-7, According to the description, users should not receive administrative details. However, during testing, both the admin email and user email received administrative details. Owner Email: ![Screenshot 2024-04-20 234158](https://private-user-images.githubusercontent.com/49083865/324223929-7e44e76d-231d-42cd-a874-e40036bb1fd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzUxMzUsIm5iZiI6MTcxMzY3NDgzNSwicGF0aCI6Ii80OTA4Mzg2NS8zMjQyMjM5MjktN2U0NGU3NmQtMjMxZC00MmNkLWE4NzQtZTQwMDM2YmIxZmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA0NDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzOTBiNzgyMmU4NGM1ZjAxNjIzNmRkZjI5Nzg5MjAzODQ3M2U5YjJmYTBmODZjZWQ5NDhlY2EwMzkyYjI4OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HEmhnMTIeIn0ve6zesqnOPDPS6QxkftNNtbZ-Stcd6g)
> 
> User Email: ![Screenshot 2024-04-20 234150](https://private-user-images.githubusercontent.com/49083865/324223947-4a533e1f-665a-478a-b557-d926450d0947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzUxMzUsIm5iZiI6MTcxMzY3NDgzNSwicGF0aCI6Ii80OTA4Mzg2NS8zMjQyMjM5NDctNGE1MzNlMWYtNjY1YS00NzhhLWI1NTctZDkyNjQ1MGQwOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA0NDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NWFlZWE3N2RhYmY4YTg0M2ZlOWU3MjYzYzYzMDIxMGRmOTY0OTIzODQ0Y2NhNTkyMzkxYmYwMzU1NTMwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4oOBbjV5remytJW63Pa-NeXHAcZL5i2D7Sspkwmm4tU)

This is out of the scope of this PR.

2024-04-24 16:34 UTC, ptrpengdev reviewed
Hi @20chen-7 

I noticed that you updated the getInfringementEmailBody function within the userHelper. Please make sure that the getInfringementEmailBody invoked in the timeEntryController (line 308) is not affected by the updated params.

2024-04-25 08:16 UTC, 20chen-7 commented
> Hi @20chen-7
> 
> I noticed that you updated the getInfringementEmailBody function within the userHelper. Please make sure that the getInfringementEmailBody invoked in the timeEntryController (line 308) is not affected by the updated params.

So based on PR673((https://github.com/OneCommunityGlobal/HGNRest/pull/673/files)), adding new input parameter(requestForTimeOffEmailBody) will not change the blue square mail, the same logic for adding the administrative content.

2024-05-01 04:59 UTC, one-community commented
Thank you all, merging!

2024-05-01 04:59 UTC, one-community approved these changes

2024-05-01 04:59 UTC, merged