XiaoW_Refactor of timeentry controllers and fix the edit history issue
OneCommunityGlobal/HGNRest pull request #881
Opened 2024-04-10 04:03 UTC by wang9hu

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:
Include the information the reviewers need to know.

2024-04-10 14:01 UTC, alla0810 commented
lots of network errors when loaded.
![network error](https://github.com/OneCommunityGlobal/HGNRest/assets/131193110/caf181c9-5625-423e-86ab-1d6e3d36ec3a)

2024-04-10 14:02 UTC, alla0810 commented
lots of network errors when loaded

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/131193110/d3c104d1-2f0b-4d98-b13b-379cf8f9e28b)

2024-04-10 15:21 UTC, alla0810 commented
logged in as a volunteer. Works good.

![logged in as a volunteer](https://github.com/OneCommunityGlobal/HGNRest/assets/131193110/c1468acb-b687-44b9-9b67-08b3cd98ce54)

2024-04-11 13:31 UTC, j-corp-25 submitted a review, later dismissed
Hi @wang9hu ,

I followed instructions for  **Volunteer** and **Admin** roles. I have ran into errors for both.

When im editing on the **Admin** role. I can edit and update the time-entry but `toastify` error still shows up when I delete the entry. The entry deletes but error still pops up

Below is the error in a recorded test for Admin


https://github.com/OneCommunityGlobal/HGNRest/assets/95154804/fbd98528-26c9-4e00-b595-180d06dfeced

I tested it with Volunteer role, and I could not make the entry. I get error on the date field.
`Invalid date. Please refresh the page.`






https://github.com/OneCommunityGlobal/HGNRest/assets/95154804/029b764b-c576-4108-97ef-bef552fd740b

2024-04-11 22:12 UTC, SRamen1999 submitted a review, later dismissed
I left my review on the frontend PR. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2131#pullrequestreview-1995565936

2024-04-13 14:29 UTC, aaryaneil requested changes
Left a review on the [frontend.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2131#pullrequestreview-1999273129)

2024-04-13 22:51 UTC, Tiantian-C reviewed
Hi,
I have tested it and leave the review at the frontend!

2024-04-13 22:58 UTC, ljrirene commented
Please see the PR review for the front-end:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2131#pullrequestreview-1998776357

2024-04-17 03:03 UTC, jennZhang93 submitted a review, later dismissed
Left a review at the fronend PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2131#pullrequestreview-2004901087

2024-04-19 17:51 UTC, ptrpengdev reviewed
Comment for reference. Frontend also tested.  [Frontend PR comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2131#issuecomment-2067036415).

2024-04-19 23:00 UTC, wang9hu commented on src/controllers/timeEntryController.js
> +  if (fromProjectId) {
The code blocks you are referring to are not just for posting tangible or intangible time entries, but also for changing the tangibility of a time entry from tangible to intangible or vice versa. If I create a function for post new time entry, I need to create both postNewTangbleTimeEntry and postNewIntangibleTimeEntry for that, and they will also be used in the editTimeEntry controller, which kind of conflict their names, and I don't want to create another 2 same functions with different names just for editTimeEntry.

2024-04-19 23:07 UTC, wang9hu commented on src/controllers/timeEntryController.js
> +          const { projectId, taskId } = timeEntry;
Those are not within the scope of this PR, this PR focuses only on the create, edit, and delete single time entry.

2024-04-20 02:16 UTC, ptrpengdev commented on src/controllers/timeEntryController.js
> +          const { projectId, taskId } = timeEntry;
Got it.

2024-04-20 05:55 UTC, one-community commented
Thank you all, merging!

2024-04-20 05:56 UTC, one-community approved these changes
Comments addressed

2024-04-20 05:56 UTC, merged