badge count APIs
OneCommunityGlobal/HGNRest pull request #895
Opened 2024-04-11 22:23 UTC by yunshan111

# Description
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/65985986/e21490a4-b263-4917-83cc-c356539c81f3)
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/65985986/34179b15-59b9-4a95-9013-be41623b73fe)

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
…

## Main changes explained:
Add badge count APIs
…

## How to test:
check into current branch and frontend #
see frontend instruction

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/65985986/e0e974ab-ca4b-4fcd-b868-69f177cacc2d

2024-04-12 09:53 UTC, hbodgal approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/145157488/9511ce49-3f61-4ec0-8f2a-b4f393f97f13)

Yes counter resets to 0. Works Fine.

2024-04-12 13:42 UTC, alla0810 commented
0. 'badge' tab not shown on development branch
1. checked out to Jiadong_Zhang_Replace_badge_Section branch.
2. errors while login as admin.
3. many errors resolved after waiting for around 10secs, but some of them still remain.
4. badge count updated successfully, and 'badge' tab appears after 'Weekly Summaries' tab.
5. But unlike above mentioned, red number indicator not shown
6. badge count reset after another badge assigned by admin

![before](https://github.com/OneCommunityGlobal/HGNRest/assets/131193110/a08bfe51-a876-408b-aec7-edc8027881c2)

![branch name](https://github.com/OneCommunityGlobal/HGNRest/assets/131193110/5d07a316-79ec-4040-a050-508a28e9ce83)

![errors while login as admin](https://github.com/OneCommunityGlobal/HGNRest/assets/131193110/6ad4904d-addd-44e7-a27e-e4f7139cbc4e)

![resolved after around 10sec](https://github.com/OneCommunityGlobal/HGNRest/assets/131193110/03a457c1-1b4c-44f8-b30d-f7ff03de6639)

![badge count not shown](https://github.com/OneCommunityGlobal/HGNRest/assets/131193110/ab70b956-b32f-4681-a6da-5b536dab02cf)

2024-04-12 23:42 UTC, aaryaneil reviewed
The badge numbers didn't show up in the badge tab in red.

https://github.com/OneCommunityGlobal/HGNRest/assets/39597927/8cc7e8a0-ed9a-4166-aa32-749a587e77ce

2024-04-14 00:04 UTC, aaryaneil requested changes
The badge numbers didn't show up in the badge tab in red.

https://github.com/OneCommunityGlobal/HGNRest/assets/39597927/166901d9-0998-479f-a16a-c5608dcf5395

2024-04-14 00:25 UTC, alla0810 requested changes
errors while login as admin.
many errors resolved after waiting for around 10secs, but some of them still remain.
badge count updated successfully, and 'badge' tab appears after 'Weekly Summaries' tab.
But unlike above mentioned, red number indicator not shown

2024-04-19 00:55 UTC, jennZhang93 approved these changes
Left a review at the frontend PR with some UI suggestions: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2146#pullrequestreview-2010296515

2024-04-19 02:42 UTC, SRamen1999 reviewed
Left a review at the frontend PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2146#pullrequestreview-2010423723

2024-04-19 21:52 UTC, metaphor987 requested changes
Hi Jiadong,

I've tested the changes using an admin account. The main functionalities are working well. I just encountered an issue here. If the admin assigns multiple badges to the user in one form(instead of clicking the "Confirm" to submit the "Assign Badge" form multiple times), the increased badge count in the user's dashboard will only increment by one. I've attached some screenshots below:

User account before receiving the badges:
![Screenshot 2024-04-19 at 4 56 04 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/91745551/b959b13d-958b-4d4b-92ac-ede6b8103bdf)

Assigning badges process in the admin pages:
![Screenshot 2024-04-19 at 4 57 43 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/91745551/e2059be2-2bba-4282-a486-cf96c5c82acf)

User account after badges are assigned:
![Screenshot 2024-04-19 at 5 00 09 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/91745551/3f1d535d-2f44-47c4-8609-b50f56e05d9e)
![Screenshot 2024-04-19 at 5 00 33 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/91745551/5100ab4d-a904-482f-8512-84b0ac39a344)

Despite this issue, all other functionalities work very well. Thank you!

2024-04-20 22:51 UTC, Tiantian-C reviewed
I have tested this function, it works well!

https://github.com/OneCommunityGlobal/HGNRest/assets/122494725/1d55c3ab-af05-4b1e-8b3d-720b54115326

2024-04-27 01:10 UTC, yunshan111 commented
> adge count in the user's dashboard will o

Thank you, I am modifying it.

2024-04-27 01:16 UTC, yunshan111 commented
> 0. 'badge' tab not shown on development branch
> 1. checked out to Jiadong_Zhang_Replace_badge_Section branch.
> 2. errors while login as admin.
> 3. many errors resolved after waiting for around 10secs, but some of them still remain.
> 4. badge count updated successfully, and 'badge' tab appears after 'Weekly Summaries' tab.
> 5. But unlike above mentioned, red number indicator not shown
> 6. badge count reset after another badge assigned by admin
> 
> ![before](https://private-user-images.githubusercontent.com/131193110/322002017-a08bfe51-a876-408b-aec7-edc8027881c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODA0NzcsIm5iZiI6MTcxNDE4MDE3NywicGF0aCI6Ii8xMzExOTMxMTAvMzIyMDAyMDE3LWEwOGJmZTUxLWE4NzYtNDA4Yi1hZWM3LWVkYzgwMjc4ODFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMTA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzBhZmIzNjVkZmMyZGZjNTIxN2EyYmE3YzVmODZhOGYxNmFhY2EzY2Y1MDc3ZjcxZTY3OTNmNjQxNWZkMzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d3Tpk-zPRFwEU7Y3-yaFdvDjmw2sjgGV0EFkod3LsPU)
> 
> ![branch name](https://private-user-images.githubusercontent.com/131193110/322001534-5d07a316-79ec-4040-a050-508a28e9ce83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODA0NzcsIm5iZiI6MTcxNDE4MDE3NywicGF0aCI6Ii8xMzExOTMxMTAvMzIyMDAxNTM0LTVkMDdhMzE2LTc5ZWMtNDA0MC1hMDUwLTUwOGEyOGU5Y2U4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMTA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjdjNGYzMTdiNDYzMGFmODIyOGVhOWFhZTMyMDVmM2FiZTEyYTk4NWU2ODUwNmRlMDI5ODRlNTc2YTUyMjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FGMTltIi-Jfqp0hu9JejP1Gg-K905KhKLmma1pAXevk)
> 
> ![errors while login as admin](https://private-user-images.githubusercontent.com/131193110/322001610-6ad4904d-addd-44e7-a27e-e4f7139cbc4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODA0NzcsIm5iZiI6MTcxNDE4MDE3NywicGF0aCI6Ii8xMzExOTMxMTAvMzIyMDAxNjEwLTZhZDQ5MDRkLWFkZGQtNDRlNy1hMjdlLWU0ZjcxMzljYmM0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMTA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzRjNWM3MWYwYzI3YWRlM2UyOTE4NDdkOTExMzFiOTg3NzkyMTBiYmRhNzhjMGJkNGJjYzczMjI2NWZjMjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JzubnkKwJWkzPnVT3g5h_NTFGgeYIUYl1m7DZyO0O0I)
> 
> ![resolved after around 10sec](https://private-user-images.githubusercontent.com/131193110/322001651-03a457c1-1b4c-44f8-b30d-f7ff03de6639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODA0NzcsIm5iZiI6MTcxNDE4MDE3NywicGF0aCI6Ii8xMzExOTMxMTAvMzIyMDAxNjUxLTAzYTQ1N2MxLTFiNGMtNDRmOC1iMzBkLWY3ZmYwM2RlNjYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMTA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTJlNjFiY2QyZWQzN2UwNzg1NGVmYzAwMWI3YTY1MzJhMmE0NDE0NDUxZjBjN2M4OTZhY2FlZWM4NmJlZDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IKhGZg82gzUUcb_yDnkdBkRPamm3_UOkhChVJFuNuJY)
> 
> ![badge count not shown](https://private-user-images.githubusercontent.com/131193110/322001755-ab70b956-b32f-4681-a6da-5b536dab02cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODA0NzcsIm5iZiI6MTcxNDE4MDE3NywicGF0aCI6Ii8xMzExOTMxMTAvMzIyMDAxNzU1LWFiNzBiOTU2LWIzMmYtNDY4MS1hNmRhLTViNTM2ZGFiMDJjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMTA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2MxMGM5ZmJlYmI3YjhkZjhiMGJhNzFhN2YyNzA1NjEyZGRiYWIwMTU0ODg0ODg2M2NhYzU0YTA1OWU1Y2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uR8RB8ycK82YNvC7FFo1WiyZMXvAdZO3X5PGsCsq8bE)



> Hi Jiadong,
> 
> I've tested the changes using an admin account. The main functionalities are working well. I just encountered an issue here. If the admin assigns multiple badges to the user in one form(instead of clicking the "Confirm" to submit the "Assign Badge" form multiple times), the increased badge count in the user's dashboard will only increment by one. I've attached some screenshots below:
> 
> User account before receiving the badges: ![Screenshot 2024-04-19 at 4 56 04 PM](https://private-user-images.githubusercontent.com/91745551/324124671-b959b13d-958b-4d4b-92ac-ede6b8103bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODA2ODIsIm5iZiI6MTcxNDE4MDM4MiwicGF0aCI6Ii85MTc0NTU1MS8zMjQxMjQ2NzEtYjk1OWIxM2QtOTU4Yi00ZDRiLTkyYWMtZWRlNmI4MTAzYmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAxMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0N2E3YThmZDc0YTQwNjBkOTQwMTY3Y2Y2YThhNWU5NzMxNTFiN2NjMTdmZGFhOGUxY2U0MDAzMjc4NTJmZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jWPvJ35Z2ZXkq3Wb0vzacLxYSzmb2h_4eouLSUcdAxA)
> 
> Assigning badges process in the admin pages: ![Screenshot 2024-04-19 at 4 57 43 PM](https://private-user-images.githubusercontent.com/91745551/324124696-e2059be2-2bba-4282-a486-cf96c5c82acf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODA2ODIsIm5iZiI6MTcxNDE4MDM4MiwicGF0aCI6Ii85MTc0NTU1MS8zMjQxMjQ2OTYtZTIwNTliZTItMmJiYS00MjgyLWE0ODYtY2Y5NmM1YzgyYWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAxMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZjExOTY0NTAwMzlmYjU0MTRmOWIzZTdlYThmMWZjYTE5ZWRmOGIyYzQxZjE0YTcwM2UwMmY4OTBjZTVkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BXKC-k5H2BOFKCUgXsNWr4A_ibdV2HSl9jWLg3hm2Eg)
> 
> User account after badges are assigned: ![Screenshot 2024-04-19 at 5 00 09 PM](https://private-user-images.githubusercontent.com/91745551/324124715-3f1d535d-2f44-47c4-8609-b50f56e05d9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODA2ODIsIm5iZiI6MTcxNDE4MDM4MiwicGF0aCI6Ii85MTc0NTU1MS8zMjQxMjQ3MTUtM2YxZDUzNWQtMmY0NC00N2M0LTg2MDktYjUwZjU2ZTA1ZDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAxMTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMTUzZjE5YWUxN2Q0ODhhOTU4OTI3ZWIwMzg3MGJmZmJhZDJlOGZjMTVhZGQ2N2MyNjJjN2ExYmUxMTJhOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jLmf_A6UbrP-HkBnp0p7ZX_BpkFP_rFVmO5WLbOYCJs) ![Screenshot 2024-04-19 at 5 00 33 PM](https://private-user-images.githubusercontent.com/91745551/324124751-5100ab4d-a904-482f-8512-84b0ac39a344.png?jwt=eyJhbGciOiJIUzI1N [...]

2024-04-27 01:19 UTC, yunshan111 commented
> errors while login as admin. many errors resolved after waiting for around 10secs, but some of them still remain. badge count updated successfully, and 'badge' tab appears after 'Weekly Summaries' tab. But unlike above mentioned, red number indicator not shown

Can you try it one more time? I cannot regenerate those bugs. backend: https://github.com/OneCommunityGlobal/HGNRest/tree/Jiadong_Zhang_Replace_badge_Section
frontend:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/tree/Jiadong_Replace_Badges_Sectiong

2024-04-27 01:22 UTC, yunshan111 commented
> The badge numbers didn't show up in the badge tab in red.
> 
>  322160087-8cc7e8a0-ed9a-4166-aa32-749a587e77ce.mov

Can you show me the inspect so I can know what's happening, I cannot regenerate the bug
backend: https://github.com/OneCommunityGlobal/HGNRest/tree/Jiadong_Zhang_Replace_badge_Section
frontend:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/tree/Jiadong_Replace_Badges_Sectiong

2024-05-03 18:10 UTC, mSharifHub commented
Even when the put request fails due to a internal server error as shown in the browser console, the UI shows as updated successfully. 


<img width="1064" alt="Screenshot 2024-05-03 at 11 08 39 AM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/135287156/4b02094b-8312-4ebc-a01c-ea1d28afe79e">

2024-05-03 18:18 UTC, mSharifHub requested changes
There is an error which i took a screenshot in the comments section where we have an internal error and yet the user UI still displays that a badge was uploaded successfully.

2024-05-03 18:18 UTC, mSharifHub commented on src/controllers/badgeController.js
> +    });
```suggestion
   const getBadgeCount = async function (req, res) {
    I recommend encapsulating in a try and catch
    
    try {
        const userId = mongoose.Types.ObjectId(req.params.userId);
     
        const userProfile = await UserProfile.findById(userId);

        if (!userProfile) {
            res.status(404).send('Cannot find the user to be assigned.');
            return;
        }
        res.status(200).send({ count: userProfile.badgeCount });
    } catch (error) {
        console.error("Error fetching user profile:", error);
        res.status(500).send('Server error occurred while fetching badge count.');
    }
};

```

2024-05-05 06:40 UTC, Parth-tech reviewed
Hi,
I have left a comment on the front end repo [link](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2146#pullrequestreview-2039591500).

2024-05-15 18:44 UTC, KaushikMreddy commented
Hi, 
I've left a review for this PR in the Frontend: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2146#pullrequestreview-2058763543

2024-05-21 20:34 UTC, peter6866 commented
Hi, I have left a review in the frontend PR #2146

2024-05-26 03:11 UTC, Sandhya1236 approved these changes
I checked out the current branch, ran npm install and the necessary commands to set up the PR locally. I logged in as an admin user and navigated to the dashboard -> Other Links -> Badge Management to assign a new badge to another user. However, the Badge Management page failed to load due to an error in the FilterBadges function within the BadgeDevelopmentTable.jsx
![image](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/ef0bbabb-dc3f-4156-99e3-fbe955f2c74d)

2024-05-28 22:40 UTC, dikshitakejriwal commented
left a review in the frontend - https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2146#pullrequestreview-2083956062

2024-05-30 08:12 UTC, Infinite-Turkey reviewed
Left a comment at Backend side [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2146#pullrequestreview-2087561039)

2024-07-06 21:28 UTC, Vigneshwar-Muriki approved these changes
Tested this PR and it works as expected.
![Screenshot 2024-07-06 172717](https://github.com/OneCommunityGlobal/HGNRest/assets/131609223/523fea1f-c18b-4f1d-ba5d-400977ff8c8a)
![Screenshot 2024-07-06 172631](https://github.com/OneCommunityGlobal/HGNRest/assets/131609223/5643de0f-5cf3-4aae-b1fd-53044e152d38)

2024-08-03 01:23 UTC, closed without merging