Sanket - Create way to see 6 months & yearly anniversaries
OneCommunityGlobal/HGNRest pull request #903
Opened 2024-04-19 16:10 UTC by SanketKaware

# Description
This PR is about adding a trophy icon for 6M, 1Y, 2Y, 3Y, etc. work anniversaries to the Leaderboard and Weekly Summaries Report.
![Screenshot 2024-04-19 at 9 35 52 AM](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/9ebb55fb-c9c2-473c-996c-718c09e85a98)

The PRs FE[#1603](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603) BE[#627](https://github.com/OneCommunityGlobal/HGNRest/pull/627) created earlier may cause issues if merged due to significant advancements in both backend and frontend. Moreover, there were some other issues with these PRs which were pointed out in the comments section. In this new PR, I have resolved those.

## Related PRs (if any):

## Main changes explained:
Created Trophy icon for 6M, 1Y, 2Y, 3Y, etc. work anniversaries to the Leaderboard and Weekly Summaries Report

## How to test:

1. Check into the current branch
2. Do `npm run build` -> `npm run start` 
3. Follow the test steps of [FE#2171](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2171)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/576a9b58-8f89-42c1-b3f7-df50e0b18819

2024-04-23 13:56 UTC, alla0810 commented
I commented on [PR2171](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2171).

2024-04-24 14:03 UTC, alla0810 approved these changes
Works expected.  Nice work!

2024-04-26 01:26 UTC, jennZhang93 approved these changes
left a frontend review: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2171#pullrequestreview-2023905615

2024-04-30 23:06 UTC, cgomezhub commented
left a frontend review:   https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2171#pullrequestreview-2032763374

2024-05-01 14:38 UTC, cgomezhub requested changes
Good job! I see that most of the requested changes are complete, however there are some details to consider:

1. Add ID copy functionality in WBS and Members table:
       - well done

2. Fix style to show ellipsis at end of ID string when text overflows:

on screens less than 533 pixels (see images)
- ellipsis in WBS table not working
- task table needs general adjustments
-  borders of all tables are not showed

3. Wrap the text in the Name column when the text overflows:
It works very well!

Additionally, I would like the description to appear centered and left-aligned as shown below:
                 7672 hours committed
                 131 active members
                 145 total contributors

4. Fix pagination component overlapping table content.
made!

5. Correct the texts of the tables so that they are aligned to the left.
made!

![Screenshot 2024-05-01 081627](https://github.com/OneCommunityGlobal/HGNRest/assets/55204862/ed26ca4c-9485-4091-8add-f8c035f0bee6)
![Screenshot 2024-05-01 081813](https://github.com/OneCommunityGlobal/HGNRest/assets/55204862/1a1017d5-2e2b-4373-be11-45fa21cd0871)
![Screenshot 2024-05-01 100933](https://github.com/OneCommunityGlobal/HGNRest/assets/55204862/5bd7c58f-a50c-4ff6-8038-f93301f24e8d)

2024-05-04 00:26 UTC, Parth-tech approved these changes
The functionality works as intended, good job. 
Review posted on front end repo: [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2171#pullrequestreview-2039160768)

2024-05-14 14:29 UTC, kaushikMreddy293 commented
Hi, I've reviewed this PR in the Frontend: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2171#issuecomment-2110399750

2024-05-14 18:05 UTC, nathcarnevalli reviewed
I reviewed on [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2171#pullrequestreview-2056062396).

2024-05-15 14:40 UTC, KaushikMreddy commented
Hi, I've reviewed this PR in the Frontend: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2171#issuecomment-2110399750

2024-05-29 19:58 UTC, peter6866 approved these changes
Great work on the backend implementation for seeing the anniversaries badges. I have left a detailed review for the frontend PR.

2025-04-28 04:12 UTC, closed without merging