Jordy add getUserNotifications unit tests
OneCommunityGlobal/HGNRest pull request #907
Opened 2024-04-22 21:38 UTC by j-corp-25

# Description

Unit tests for getUserNotifications in notificationController

## Related PRS (if any):
N/A

## Main changes explained:
- Unit tests for the getUserNotifications endpoint

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm run test notification`

## Screenshots or videos of changes:

![getUserNotificationsTestCases](https://github.com/OneCommunityGlobal/HGNRest/assets/95154804/d69ce619-4a48-42f8-8538-c6797a14e7b9)

## Note:
N/A

2024-04-23 12:37 UTC, linkhanthtel approved these changes
All tests passed as expected! Nice work! 

<img width="1182" alt="#907" src="https://github.com/OneCommunityGlobal/HGNRest/assets/95618937/45860bc9-884b-4c55-9be7-5ae9f0577f0d">

2024-04-23 17:35 UTC, Alakabtaha0 approved these changes
Passed all 3 tests. good job.
<img width="726" alt="Screenshot 2024-04-23 at 18 33 59" src="https://github.com/OneCommunityGlobal/HGNRest/assets/106825659/e4c05167-1aec-488b-9e0d-7f509bcf2572">

2024-04-24 00:03 UTC, mianmiantea2019 requested changes
Hi Jordy, Good work!  Just few recommendations in the .md file

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/59427068/89c17bfb-6b3b-4fbb-81f8-144b77babbce)

2024-04-24 00:03 UTC, mianmiantea2019 commented on requirements/notificationController/getUserNotification.md
It's recommended to test first negative cases first. So please reorganize your .md file to include the negative cases first and positive cases at last.

2024-04-24 01:23 UTC, j-corp-25 reviewed
updated order of tests base on Christy's suggestion

2024-04-24 01:23 UTC, j-corp-25 commented on requirements/notificationController/getUserNotification.md
Thank you for pointing this out! I have updated the order of the test cases : )

2024-04-24 03:31 UTC, mianmiantea2019 approved these changes
Good work!

2024-04-26 22:15 UTC, Abi-Liu approved these changes
The tests are looking good and are all passing. Good work!

![Screenshot 2024-04-26 at 3 14 51 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/59585815/a78e0a94-5663-48c4-b42b-7072ec442641)

2024-04-27 03:42 UTC, gowthamdongari approved these changes
test cases sucessfully 
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/27274513/3c788c92-4917-444a-81cf-6764a854d303)

2024-10-24 16:22 UTC, closed without merging