Ilya - Tools table
OneCommunityGlobal/HGNRest pull request #913
Opened 2024-04-25 22:10 UTC by ilyaflaks

<img width="771" alt="tool-list-task" src="https://github.com/OneCommunityGlobal/HGNRest/assets/105448137/1c6dc9fc-7081-419c-aeb6-558fcc11ad42">

# Description
Adds functionality for the user to navigate to [/bmdashboard/tools](http://localhost:3000/bmdashboard/tools), and view a list of all tool items currently in the system. The table can be sorted by tool name or by project and the results can be filtered by tool name. Update History and Purchase History can be viewed for each item in a modal.

## Related PRS (if any):
This backend PR is related to the [#2193](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2193) frontend PR.
To test this backend PR you need to checkout the #2193 frontend PR, branch **ilya_tools_table_fe**

## Main changes explained:
- largeItemBaseSchema changed to have a "condition" field
- buildingTool schema changed to have specific values for the purchaseStatus field
- fetchAllTools function added to bmToolController to query the database and return a full list of tool items and populate certain fields
- A new route added to call fetchAllTools when a GET request is made to /api/tools

## How to test:
1. Check out the current branch. Make sure you are using Node version 14.17.6. Run **npm install** and **npm run build && npm start** to run the backend locally
2. Check out **ilya_tools_table_fe** branch on the front end. Run commands **npm install** and **npm run start:local** to launch the front end application
3. On the front end log in as any user
4. Go to [/bmdashboard](http://localhost:3000/bmdashboard) and log in again
5. Navigate to [/bmdashboard/tools](http://localhost:3000/bmdashboard/tools). A list of all tools currently in the system should display.
6. Test the filtering by Project and Tool function (the dropdowns above the table)
7. Test sorting by project and by name (the arrows next to "Project" and "Name" in the table header
8. Pressing the View button under Updates should open an Updates Record modal (not all items have information to display)
9. Pressing the View button under Purchases should open an Purchase Record modal (not all items have information to display)
10. Pressing the pencil should open an Update Tool Form modal. The content of this modal is outside of the scope of this task

## Screenshots or vide

https://github.com/OneCommunityGlobal/HGNRest/assets/105448137/512b9aa1-98c0-4a51-96f2-c42e3b54683d

2024-05-01 18:00 UTC, mSharifHub requested changes
The controllers needs to be refractor for clarity and mostly dont use try and catch along with promise chain. You can use try and catch for better clarity and  provide more information on the error handling.

2024-05-02 13:25 UTC, alla0810 approved these changes
Left PR review [on the frontend side](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2193#pullrequestreview-2035737972).
Great work!
Everything works great!

2024-05-02 17:39 UTC, ilyaflaks commented on src/controllers/bmdashboard/bmToolController.js
> +        .then(results => res.status(200).send(results))
@mSharifHub  Good observation about try/catch. I have removed it in the latest commit and added a more explicit error message. The format for the populate function is a matter of preference, but I moved it outside of the query anyway.
Thank you for your review

2024-05-02 20:34 UTC, Ramaruva approved these changes
Reviewed changes in frontend related to this branch and changes are working as expected

2024-05-03 00:06 UTC, Parth-tech approved these changes
Hey Llya,
Everything works correctly, good job. Here's my review [FrontEnd Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2193#pullrequestreview-2037139321)

2024-05-04 03:49 UTC, aaryaneil approved these changes
Tested the PR and left a review on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2193#pullrequestreview-2039221428)

2024-05-11 15:32 UTC, KaushikMreddy commented
Hi, 

I ran the backend step by step as mentioned, everything ran but no data is being populated in the tools table.
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/144624017/1a351269-91e3-470c-b351-e698932d05c6)

Data fetched from the API call seems to be empty
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/144624017/ea1b754d-4ec9-45cc-bbb6-5e80f122505c)

2024-05-14 14:09 UTC, nathcarnevalli reviewed
No data is being shown to me. I logged in with different accounts.

![Screenshot 2024-05-14 105941](https://github.com/OneCommunityGlobal/HGNRest/assets/69649453/5f2e9342-9174-4b72-ab5b-1ffc708e7d44)

2024-05-17 15:43 UTC, ZhangPeizhou commented
Reviewed in the frontend.

2024-05-18 03:22 UTC, DaveB4r approved these changes
Everything is perfect!
Great Job!
Building Management Dashboard OK!
![bmdashboardlogin](https://github.com/OneCommunityGlobal/HGNRest/assets/117042123/ae3fa083-f3ba-4c15-9616-291df1ba77a8)
Building and Inventory Management Dashboard OK!
![bmdashboard](https://github.com/OneCommunityGlobal/HGNRest/assets/117042123/8afa7870-0b7d-4e3f-9f6e-5c0c23a05460)
Tools OK!
![bmdashboardtoolsfilter](https://github.com/OneCommunityGlobal/HGNRest/assets/117042123/4e6a37a5-1f28-48c0-8bc1-22b472c11c9d)
Sort Tools OK!
![bmdashboard-sort-runs](https://github.com/OneCommunityGlobal/HGNRest/assets/117042123/db0a9f7f-aa81-4516-ad93-254503c43eb7)
Purchase Record OK!
![purchase](https://github.com/OneCommunityGlobal/HGNRest/assets/117042123/5b6a5079-c695-4fc9-9503-7425cd0690b7)

2024-05-21 02:29 UTC, one-community commented
Thank you all, merging!

2024-05-21 02:29 UTC, merged