test: completed testing for getAllInvInProjectWBS
OneCommunityGlobal/HGNRest pull request #945
Opened 2024-05-13 02:52 UTC by luisarevalo21

# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

## Note:

<img width="1228" alt="Screenshot 2024-05-12 at 7 51 44 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/22454953/d2d2de6e-cb47-4f6d-b606-dba4b891e08c">

2024-05-13 03:13 UTC, j-corp-25 approved these changes
Hi @luisarevalo21 ,

All tests are passing!


![PR#945](https://github.com/OneCommunityGlobal/HGNRest/assets/95154804/1b0dce98-5d00-40f0-87b1-491be908764e)

2024-05-13 20:22 UTC, Ramaruva approved these changes
Hi I have run all test cases in my local env and are working as expected 
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/64008831/cc89c0aa-9f90-4aae-8a4d-77d002908d92)

2024-05-16 06:02 UTC, KaushikMreddy commented
Hi, 
All the test cases have passed
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/144624017/effc839b-5c85-4546-b786-9e7d6934782d)

Please remove the commented code in the file, if your changes are final. Good work!

2024-05-16 19:18 UTC, gowthamdongari approved these changes
works as exxpected 
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/27274513/47c95428-d479-48a4-89e1-84bf27ae4147)

2024-05-17 23:31 UTC, MinSun0814 approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/145076494/d724a45a-62d7-450f-8e19-2d950867d1b3)
Hello, I ran your tests and everything passed.

2024-05-18 02:40 UTC, Abi-Liu requested changes
Looks good! All test cases are passing as expected. I left a few comments regarding how to enhance the overall tests.
![Screenshot 2024-05-17 at 7 37 42 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/59585815/050b7165-4f8b-469d-96d2-6fa4bbffc69d)

2024-05-18 02:40 UTC, Abi-Liu commented on src/controllers/inventoryController.spec.js
> +      expect(findSpy).toHaveBeenCalledWith({
You do a good job of checking to make sure these methods are called with the correct arguments here.

2024-05-18 02:40 UTC, Abi-Liu commented on src/controllers/inventoryController.spec.js
> +      const findSpyProjects = jest.spyOn(projects, 'findOne').mockImplementationOnce(() => {
Make sure you assert that these spy methods are called with the correct arguments as well.

2024-05-18 09:21 UTC, Wenboooooo approved these changes
![1716024053269](https://github.com/OneCommunityGlobal/HGNRest/assets/114895283/4e06b12d-708a-453f-938e-6960e81dbab4)
Looks good to me. All cases have been passed

2024-05-18 19:33 UTC, aaryaneil approved these changes
All the test cases passed.
<img width="726" alt="Screenshot 2024-05-18 at 2 32 54 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/39597927/ce77de5e-1fa5-4021-b707-fd572f127667">

2024-05-31 19:54 UTC, dikshitakejriwal approved these changes
All the test cases passed!
<img width="799" alt="Screenshot 2024-05-31 at 12 54 28 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/62951992/a5889ea2-e4f9-4083-a5b3-86b185cc4771">

2024-06-01 22:14 UTC, Sandhya1236 approved these changes
I have successfully tested the first set of unit tests for the Inventory Controller. The main changes include creating unit tests for the getAllInvInProjectWBS function and documenting all positive and negative cases in a markdown file. After checking into the current branch, running npm install, and executing npm run test inventoryController, I verified that all tests passed successfully, confirming the functionality of the getAllInvInProjectWBS function is working as expected.

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/79351059/25ecbfd8-d696-4ed1-807b-008accb6816b)

2024-06-02 04:28 UTC, deepthikannan approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/83337914/22151dd8-54cb-4450-aba8-435829364cb7)
Great code, all test cases passed !

2024-06-12 23:41 UTC, akshit0211 commented
All test cases passed. Good job!

<img width="657" alt="All test cases passed" src="https://github.com/OneCommunityGlobal/HGNRest/assets/112666943/b9afd124-548b-4000-868e-d14072d8c9ff">

2024-06-12 23:41 UTC, akshit0211 approved these changes

2024-06-15 23:23 UTC, shradac approved these changes
All tests passed. The tests cover all specified scenarios. Good Work!

<img width="1030" alt="10" src="https://github.com/OneCommunityGlobal/HGNRest/assets/56028645/93b6af2b-a91c-40f7-9f2f-7f60c2c5eb54">

2024-06-16 03:06 UTC, mianmiantea2019 commented
All tests passed. The tests cover all specified scenarios. Good Work!

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/59427068/aaa62630-f4a6-4895-9040-cc9d2d36b732)

2024-07-11 00:04 UTC, nyelmela approved these changes
All test cases have passed.
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/123037122/342b7bc7-b105-430c-9316-c18bfd414f6c)

2024-07-21 07:16 UTC, cecilia-uu commented
<img width="759" alt="截屏2024-07-21 下午3 16 04" src="https://github.com/user-attachments/assets/5338b196-fd32-40c8-addc-fb9dfa1dbb68">
Tests have passed.

2024-07-30 22:43 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (159)](https://github.com/user-attachments/assets/8fa0d759-d420-44ce-9548-d8a3e171a1f9)

2024-08-04 05:04 UTC, jinxyou approved these changes
All test cases have passed.
![PR 945](https://github.com/user-attachments/assets/ce422e78-edc0-4748-9d08-a8569178c0a9)

2024-08-17 01:42 UTC, Gmon-k commented
All the test cases has passed and Below is the screenshot for it.

<img width="1024" alt="11" src="https://github.com/user-attachments/assets/0235b2a8-48b9-4700-bc88-f47e22d425ab">

2024-09-05 20:34 UTC, AJAYINAVOLU approved these changes
Tests are passing successfully without any errors.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/4609666a-e631-4715-9379-e0ece284565c">

Thank You

2024-09-06 02:18 UTC, manikittu810 approved these changes
Hello @luisarevalo21 
Everything is working good as mentioned.

Thank you.
<img width="1383" alt="Screenshot 2024-09-05 at 7 16 40 PM" src="https://github.com/user-attachments/assets/051b8293-070b-4f0d-b779-869c37460550">

2024-09-06 21:47 UTC, Saniya98 approved these changes
All tests are passing 
![image](https://github.com/user-attachments/assets/86dd8741-c189-4822-8c99-7dc8d27c3682)

2024-09-14 00:48 UTC, neeharikakoniki approved these changes
All tc passed.
![image](https://github.com/user-attachments/assets/1fb5b8bb-5dad-41b0-9b05-2c52ffb9b1f4)

2024-09-15 02:36 UTC, panchalvatneu approved these changes
All tests on inventoryController passed, good work!
![image](https://github.com/user-attachments/assets/39a65165-e73f-433f-b5fc-2c696236b886)

2024-09-18 05:16 UTC, ishangoel17 reviewed
All test cases are passing. Below is the screenshot for reference:
![Capture945](https://github.com/user-attachments/assets/ac22f150-ea2a-4c1b-bb12-7169510030c7)

2024-09-24 18:45 UTC, anirudhsk2107 approved these changes
The tests are working properly 

![Screen Shot 2024-09-24 at 2 44 36 PM](https://github.com/user-attachments/assets/2604d797-5b16-4495-865e-e39e90818f75)

2024-10-05 16:55 UTC, geetamatkar commented
I tested this PR and all test cases are passing.

<img width="1047" alt="PR945" src="https://github.com/user-attachments/assets/bc38eca3-0018-4fb8-9225-1c104ce268a9">

2024-10-06 06:48 UTC, ziyanw52 approved these changes
I have tested that all the test cases have passed.
![1191728197303_ pic_hd](https://github.com/user-attachments/assets/a235c949-35e7-4bec-b4d1-f11f13881385)

2024-10-13 05:26 UTC, mianmiantea2019 commented
I have tested that all the test cases have passed.

![image](https://github.com/user-attachments/assets/22aef184-471d-4f72-a653-54a3b3996b8f)

2024-10-14 22:06 UTC, pallavithorat commented
All test cases have passed.
<img width="922" alt="PR#945" src="https://github.com/user-attachments/assets/b867a280-3e76-4cfc-a16e-036d73e9f9c3">

2024-10-27 04:23 UTC, RachanaZha approved these changes
Have tested the changes. All test cases passed successfully. Changes are working fine.

![zha_rachana_PR#945](https://github.com/user-attachments/assets/858e71b3-c0f9-4e34-8e3e-59e424a64166)

2024-10-31 03:14 UTC, SatyashanthiT commented
I reviewed this pr for the Inventory Controller, specifically focusing on the unit tests for getAllInvInProjectWBS. After running the tests and verifying all cases pass, I approved this PR
<img width="851" alt="image" src="https://github.com/user-attachments/assets/48607210-d11c-4fa0-9336-553269d2ffb9">

2025-05-02 04:41 UTC, one-community commented
Thank you all, merging!

2025-05-10 05:54 UTC, one-community commented
Thank you all, merging!

2025-05-10 05:55 UTC, merged