test: project controller unnit test
OneCommunityGlobal/HGNRest pull request #973
Opened 2024-06-01 15:02 UTC by SushmithaPrathap

# Description
PR adds unit test for projectController.js,

## Related PRS (if any):
none
…

## Main changes explained:
- Added unit test file named: projectController.spec.js
- Markdown files explaining all the tests …
…

## How to test:
1. check into the current branch
2. do npm install
3. do npm run test projectController
4. All test cases should pass

## Screenshots or videos of changes:
![Screenshot 2024-06-01 at 11 00 58 AM](https://github.com/OneCommunityGlobal/HGNRest/assets/113482457/87c6fa54-f378-496c-a616-8a518562872c)

2024-06-01 15:47 UTC, peter6866 approved these changes
All tests passed as expected. 
<img width="671" alt="image" src="https://github.com/OneCommunityGlobal/HGNRest/assets/58479595/8cd2fa38-a05d-49b8-bb7d-88b8c535aa27">

2024-06-01 15:53 UTC, dikshitakejriwal approved these changes
All the test cases passed as expected. 
<img width="828" alt="Screenshot 2024-06-01 at 8 51 23 AM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/62951992/be3c63ce-5afe-4293-b489-e777050a9275">

2024-06-01 17:41 UTC, Kavil-Jain-514 approved these changes
All the 39 test cases have passed. Great work !!
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/112303944/2bedc8b8-60db-4a80-905c-3d66f6be74e9)

2024-06-01 19:25 UTC, DiegoSalas27 reviewed
Added some comments. Overall great work. Please solve these issues and add the integration tests.

2024-06-01 19:25 UTC, DiegoSalas27 commented on src/controllers/projectController.js
> +      .catch((error) => res.status(404).send(error.message));
I don't think this is safe. Why would you return the `message` string rather than the Error itself? This will break the frontend app right?

2024-06-01 19:25 UTC, DiegoSalas27 commented on src/controllers/projectController.js
> +          res.status(500).send(errors);
Better keep the error status as 400 as we discussed in our meeting.

2024-06-01 19:25 UTC, DiegoSalas27 commented on src/controllers/projectController.js
> +  // const deleteProject = async function (req, res) {
Why have you added commentted code? This is cannot be merged.

2024-06-01 19:25 UTC, DiegoSalas27 commented on src/controllers/projectController.js
> +    Project.findById(projectId, async (error, record) => {
Why did you add `async` here?

2024-06-01 20:28 UTC, Sandhya1236 approved these changes
I have successfully tested the addition of unit tests for projectController.js. The changes involved adding a new unit test file named projectController.spec.js, along with markdown files explaining all the tests. After checking into the current branch and running npm install, I executed the tests using npm run test projectController. All test cases passed successfully, confirming that the unit tests for the project controller are working as expected.

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/79351059/781e06be-eae9-4c08-a40d-2c2731dc069e)

2024-06-01 23:36 UTC, aaryaneil approved these changes
Tested the PR and all the test cases passed.
<img width="838" alt="Screenshot 2024-06-01 at 6 33 25 PM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/39597927/32a97fca-c853-4af0-8a8e-5d35400d0ca8">

2024-06-02 00:58 UTC, tianyangL11 approved these changes
All test cases passed successfully!
![9e119184b56302d381eb184831109a3](https://github.com/OneCommunityGlobal/HGNRest/assets/144981416/793fba7a-85de-4004-9c5d-4406627321cf)

2024-06-02 02:01 UTC, deepthikannan approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/83337914/3fda16e3-5973-4013-98f6-e2420ec602d1)
All tests are passing, and the code looks clean.

2024-06-02 04:08 UTC, MinSun0814 approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/145076494/9a721248-f6ea-4fe0-944d-d12486ee190a)
All tests passed. Nice work.

2024-06-04 00:02 UTC, cecilia-uu approved these changes
All tests have passed!
<img width="798" alt="截屏2024-06-04 上午8 01 44" src="https://github.com/OneCommunityGlobal/HGNRest/assets/117628326/74a4dc04-ce13-48bd-a331-8daa6d14e5bd">

2024-06-07 22:05 UTC, Logeshwari-Renu approved these changes
All the test cases have been passed.!

![PR973](https://github.com/OneCommunityGlobal/HGNRest/assets/166590596/b5e6d4d0-660b-4602-8535-214734da550e)

2024-06-09 01:24 UTC, jinxyou approved these changes
All test cases have passed without exceptions. Great work!
![Screenshot 2024-06-08 202419](https://github.com/OneCommunityGlobal/HGNRest/assets/13797542/79b55394-aa10-42a7-97d1-54b6ded11452)

2024-06-09 03:10 UTC, KaushikMreddy approved these changes
Hi, 
The test cases are very thorough and they all work. Great work!

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/144624017/8b8ebf96-0361-422b-bb9a-6178af0c3ab4)

2024-06-13 00:17 UTC, akshit0211 commented
Hi, all test cases passed. Good job!

<img width="795" alt="all test cases passed 1" src="https://github.com/OneCommunityGlobal/HGNRest/assets/112666943/822a7ed7-5180-473d-bfaf-564fa3932882">
<img width="790" alt="all test cases passed 2" src="https://github.com/OneCommunityGlobal/HGNRest/assets/112666943/75835885-5272-453a-977e-03c0f5791a01">

2024-06-13 00:17 UTC, akshit0211 approved these changes

2024-06-16 03:04 UTC, mianmiantea2019 commented
Hi, all test cases passed. Good job!

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/59427068/6e917175-da7f-487f-8f15-c392fecd52f1)

2024-06-27 18:40 UTC, Trip2310 approved these changes
All tests are passed as expected
<img width="736" alt="PR_973" src="https://github.com/OneCommunityGlobal/HGNRest/assets/113469900/9441ee8b-18c9-4750-a67c-bb76beff43c8">

2024-06-28 21:22 UTC, HowieMiao approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/73614967/af6fdf6a-29be-4b26-bd37-876423d7b180)

2024-07-12 20:51 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (79)](https://github.com/user-attachments/assets/3ab1a986-8a70-463e-bbd9-680307b3e6f0)

2024-07-13 20:25 UTC, Rishitha1309 approved these changes
All test cases passed successfully

![973](https://github.com/user-attachments/assets/a0e9c7cc-4720-445a-bb77-0215eac41f7d)

2024-07-28 06:19 UTC, Chetan0606 approved these changes
Everything looks good. Please find the attached image.
![image](https://github.com/user-attachments/assets/342e15a4-7015-4688-b6f6-34c023f71ea4)

2024-08-03 18:19 UTC, KurtisIvey approved these changes
![Screenshot 2024-08-03 at 1 17 15 PM](https://github.com/user-attachments/assets/9a04ad93-b257-474d-a875-67f3341a6367)



Everything passes without issue, you've got proper response error codes, and you have really comprehensive coverage. Fantastic job with all you've done here. 


If you could clear up the merge conflict please, I'd love to get this rereviewed and merged asap.

2024-08-13 00:42 UTC, SatyashanthiT approved these changes
After running the tests locally, I confirmed that all test cases pass successfully, indicating that the unit tests are functioning as expected. The newly added `projectController.spec.js` file covers the necessary scenarios, and the test results align with the intended functionality, so I am approving this PR.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/e0913403-cb0a-4ceb-b614-fbc7bfb26361">

2024-08-16 23:10 UTC, Gmon-k commented
After running the test, all the test cases has passed and Below is the screenshot for it.

<img width="1024" alt="7" src="https://github.com/user-attachments/assets/7ca06439-b9e3-4222-a950-440cb93bfa10">

2024-08-17 11:31 UTC, linkhanthtel approved these changes
All test cases passed! Nice work! 

<img width="1144" alt="PR #973" src="https://github.com/user-attachments/assets/ec4db072-d0ad-48ea-9462-347db92fb398">

2024-09-05 18:10 UTC, AJAYINAVOLU approved these changes
Tests are passing without any errors.

<img width="717" alt="image" src="https://github.com/user-attachments/assets/c27c30d6-a733-4a7c-9e86-bc41eef49f82">


Thank You

2024-09-06 02:23 UTC, manikittu810 approved these changes
Hello @SushmithaPrathap 
Everything is working fine as mentioned.Every test passed.
<img width="1349" alt="Screenshot 2024-09-05 at 7 21 53 PM" src="https://github.com/user-attachments/assets/8ddf9e2b-a130-4c6d-b8fb-616e037f7d62">

Thank you.

2024-09-11 19:42 UTC, ddshah878 approved these changes
All the test cases passed as expected. Good job!

![image](https://github.com/user-attachments/assets/3cc1de80-51ad-4253-81f3-463cd4e1656d)

2024-09-12 07:08 UTC, neeharikakoniki requested changes
No tests found despite added projectController.spec.js
![image](https://github.com/user-attachments/assets/a798e3e5-2bf0-45e5-a958-8e3f87900f30)

2024-09-12 07:15 UTC, neeharikakoniki approved these changes

2024-09-20 03:21 UTC, geetamatkar commented
Hi @SushmithaPrathap ,
I tested this PR and all test cases have passed.

<img width="1086" alt="PR973" src="https://github.com/user-attachments/assets/6de1173d-209e-46c5-9117-bad38d28767b">

2024-09-22 06:38 UTC, j-corp-25 approved these changes
<img width="1097" alt="Screenshot 2024-09-22 at 2 38 13 AM" src="https://github.com/user-attachments/assets/3b75d4e8-c1a5-47a7-bc04-19069b0648d5">
All tests are passing! awesome stuff

2024-10-13 05:26 UTC, mianmiantea2019 commented
All the test cases passed as expected. Good job!

![image](https://github.com/user-attachments/assets/56a22763-1e3f-4833-aa75-754da83bea8c)

2024-10-15 20:50 UTC, pallavithorat commented
All the test cases passed as expected.
<img width="927" alt="PR#973" src="https://github.com/user-attachments/assets/b4d7bbae-3bdb-40bb-9292-9c85fbdb6a2e">

2025-04-28 04:12 UTC, closed without merging