Jordy add roles controller unit tests
OneCommunityGlobal/HGNRest pull request #981
Opened 2024-06-08 06:30 UTC by j-corp-25

# Description

Unit tests for rolesController

## Related PRS (if any):
N/A

## Main changes explained:

- unit tests for `createNewRole`
- unit tests for `deleteRoleById`
- unit tests for `getAllRoles`
- unit tests for `getRoleById`
- unit tests for `updateRoleById`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm run test roles -- --verbose`

## Screenshots

![PRTest](https://github.com/OneCommunityGlobal/HGNRest/assets/95154804/39f8d2d1-9f45-4bd3-a8e0-e92b37bb7087)

## Note:

Check that all tests are passing
N/A

2024-06-08 15:38 UTC, Kavil-Jain-514 approved these changes
All test cases have passed

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/112303944/211b868c-0805-4adf-9bf5-f8b0a27ac8dd)

2024-06-08 20:35 UTC, jinxyou approved these changes
![Screenshot 2024-06-08 153336](https://github.com/OneCommunityGlobal/HGNRest/assets/13797542/415c875d-0531-4f25-89e2-26fb7b3992f1)
Hi I have done the testing according to the instruction. It seems no problem. Great work!

2024-06-08 21:53 UTC, akshit0211 commented
Hi Jordy, all test cases passed. Great work!

<img width="799" alt="all test cases passed" src="https://github.com/OneCommunityGlobal/HGNRest/assets/112666943/4da65ab5-ff80-4f1c-881e-c5a2a6d6d61f">

2024-06-08 21:53 UTC, akshit0211 approved these changes

2024-06-08 22:31 UTC, Logeshwari-Renu approved these changes
All the test cases are passed.! 

![PR981](https://github.com/OneCommunityGlobal/HGNRest/assets/166590596/bb24df6a-00ae-4f0d-af09-7e7bf9fc9732)

2024-06-09 00:46 UTC, Wenboooooo approved these changes
All tests have passed. Looks good to me.
<img width="676" alt="#981" src="https://github.com/OneCommunityGlobal/HGNRest/assets/114895283/a8c6f596-f20c-491d-9a14-96cea2f1849f">

2024-06-09 02:00 UTC, deepthikannan approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/83337914/2795fd3f-39c4-4f2e-8791-0de7d0dc6aba)
All test cases passed.

2024-06-09 02:52 UTC, KaushikMreddy approved these changes
Hi Jordy, all your test cases are working, please try to add a case where deleting a role fails if appropriate for the function.

![image](https://github.com/OneCommunityGlobal/HGNRest/assets/144624017/04d2f50c-15da-4625-8149-d9bf6d225a4d)

2024-06-10 18:15 UTC, TXMO-dev requested changes

2024-06-10 18:15 UTC, TXMO-dev commented on src/controllers/rolesController.js
> +const UserProfile = require('../models/userProfile');
Great job on the recent code! It shows a solid understanding of Node.js and Express for handling roles and permissions. Here are a few suggestions that could further enhance the readability, maintainability, and performance of your code:
1. Improve Error Handling:

Issue: Error handling could be more standardized and descriptive.
Suggestion: Consider using a centralized error handling middleware to maintain consistency across your application and provide more detailed error messages.

```
const errorHandler = (err, req, res, next) => {
  res.status(err.status || 500).send({ error: err.message || 'Internal Server Error' });
};
```
2. Consistent Asynchronous Code:

Issue: Mixing callback-based and async/await-based code can lead to inconsistencies.
Suggestion: Refactor your code to consistently use async/await.

```
const getAllRoles = async (req, res, next) => {
  try {
    const results = await Role.find({});
    res.status(200).send(results);
  } catch (error) {
    next(error);
  }
};

const createNewRole = async (req, res, next) => {
  try {
    const newRole = new Role({
      roleName: req.body.roleName,
      permissions: req.body.permissions,
    });
    const savedRole = await newRole.save();
    res.status(201).send(savedRole);
  } catch (error) {
    next(error);
  }
};
```
Enhanced Input Validation:

Issue: Current input validation is minimal and could be more robust.
Suggestion: Utilize a validation library like Joi or express-validator for more comprehensive input validation.

Summary of Changes:
Centralized Error Handling: Adds middleware for consistent error handling.
Consistent Async/Await Usage: Refactors functions to use async/await.
Permission Check Middleware: Moves permission checks to middleware.
Enhanced Input Validation: Adds middleware for more robust input validation.
These improvements will make your codebase more modular, readable, and easier to maintain. Keep up the fantastic work!

2024-06-15 09:58 UTC, aaryaneil approved these changes
Tested the PR and all the test cases passed.
<img width="1136" alt="Screenshot 2024-06-15 at 4 57 39 AM" src="https://github.com/OneCommunityGlobal/HGNRest/assets/39597927/4167ca31-3e15-4e84-884c-eedf3d3897e8">

2024-06-15 23:09 UTC, shradac approved these changes
All tests passed. The tests cover all specified scenarios. Good Work!

<img width="1040" alt="7" src="https://github.com/OneCommunityGlobal/HGNRest/assets/56028645/09d1c734-b223-454b-ab1a-f4019c780db7">

2024-06-16 03:01 UTC, mianmiantea2019 commented
All tests passed.  Good work!
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/59427068/4c0571fa-ca40-4cd2-aae2-15cd34ddd34d)

2024-06-21 00:11 UTC, sahithidhulipala9 commented
All test cases passed! 
![PR 981](https://github.com/OneCommunityGlobal/HGNRest/assets/60340387/05f50805-63ce-40b3-bf30-27f29b9ff22f)

2024-06-21 00:11 UTC, sahithidhulipala9 approved these changes

2024-07-04 04:54 UTC, Rishitha1309 approved these changes
All test cases passed successfully
![PR981](https://github.com/OneCommunityGlobal/HGNRest/assets/59167143/c1a91483-fc13-479f-8e45-098f827aa939)

2024-07-05 09:26 UTC, MinSun0814 approved these changes
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/145076494/0bf53851-289e-467c-8e50-77702319df02)

2024-07-10 01:18 UTC, nikhilpittala16 approved these changes
I have tested the PR and all the test cases have passed.
![Screenshot (53)](https://github.com/OneCommunityGlobal/HGNRest/assets/142841075/6a0e14c0-20da-470b-b7bb-2aab09cca003)

2024-07-11 14:35 UTC, gowthamdongari approved these changes
All test cases working as expected 
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/27274513/2cad3a4e-0ba6-4ad1-a5d0-f0149cb4f60f)

2024-07-21 04:17 UTC, merged