Jingyi edit header message permission
OneCommunityGlobal/HGNRest pull request #985
Opened 2024-06-12 00:13 UTC by Jingyii800

# Description
Gives the user permission to edit the message displayed in the header.

## Related PRS (if any):
To test this backend PR you need to checkout the [#2345](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345) frontend PR.
…

## Main changes explained:
- create a new initial permission for editing header message
- Add permission check before running backend logic
- 
## How to test:
1.check into current branch
2.do npm install npm run build and npm start to run this PR locally
3.Clear site data/cache
4. then Please refer to the frontend pull request

2024-06-12 01:33 UTC, Kavil-Jain-514 approved these changes
The functionality works as expected.
A volunteer user with edit header message permission can edit the error message without any errors or warnings.
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/112303944/d3d3024e-b6c9-4f2f-b71a-cfb81bd2bfc3)
![image](https://github.com/OneCommunityGlobal/HGNRest/assets/112303944/720245ea-bd36-4533-8aa0-a076e6d1568e)

2024-06-12 16:53 UTC, Logeshwari-Renu approved these changes
I have tested the PR and it works as expected. I have left a comment on the front-end [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345#pullrequestreview-2113583902)

2024-06-14 02:14 UTC, akshit0211 commented
I left a comment on the front-end PR. It is working as expected. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345#pullrequestreview-2117296163)

2024-06-14 02:15 UTC, akshit0211 approved these changes

2024-06-14 22:16 UTC, nathcarnevalli approved these changes
Left my review on [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345#pullrequestreview-2119429547).

2024-06-15 03:28 UTC, tianyangL11 approved these changes
left a comment on the front-end PR. It is working as expected.

2024-06-15 19:46 UTC, jinxyou approved these changes
I left a review at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345#pullrequestreview-2120835394

2024-06-16 00:06 UTC, nathanah requested changes

2024-06-16 00:06 UTC, nathanah commented on src/controllers/ownerMessageController.js
> +    ) {
```suggestion
    if (
      !(await helper.hasPermission(req.body.requestor, 'editHeaderMessage'))
    ) {
```
I think the permissions are supposed to be replacing role logic entirely. You add 'editHeaderMessage' in `createInitialPermissions.js`, so Owners should always have this permission. Not requiring them to be an owner allows for the header message to perhaps be delegated to a non-owner account.

2024-06-16 00:06 UTC, nathanah commented on src/controllers/ownerMessageController.js
> +    ) {
```suggestion
    if (
      !(await helper.hasPermission(req.body.requestor, 'editHeaderMessage'))
    ) {
```
Same as other comment

2024-06-18 19:00 UTC, Jingyii800 commented on src/controllers/ownerMessageController.js
> +    ) {
Thank you, Nathan! I will fix it

2024-06-19 22:35 UTC, sahithidhulipala9 commented
Left review at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345#pullrequestreview-2120835394

2024-06-19 22:35 UTC, sahithidhulipala9 approved these changes

2024-07-03 19:43 UTC, vishavk1992 reviewed
it works as expected and i left comment on frontend PR

2024-07-06 00:59 UTC, nikhilpittala16 approved these changes
I have tested the PR and it works as expected. I have left a PR review on the front-end. link can be found here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345#pullrequestreview-2161344009

2024-07-13 20:45 UTC, Rishitha1309 approved these changes
Left my review in the front-end PR. Everything worked as expected.

2024-07-31 13:49 UTC, Annezhang673 approved these changes
I have left a review on the frontend PR#2345. Function works as expected.

2024-08-23 20:04 UTC, SMitta11 approved these changes
I left a comment on the front-end PR. It is working as expected.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345#pullrequestreview-2258018110

2024-09-04 04:06 UTC, AJAYINAVOLU approved these changes
Reviewed this PR on the frontend [repo](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2345#pullrequestreview-2278947116).

2024-09-04 23:41 UTC, nathanah approved these changes

2024-09-05 04:43 UTC, one-community commented
Thank you all, merging!

2024-09-05 04:43 UTC, merged